/** Official USCIS English reading vocabulary (naturalization test). */
export const READING_VOCAB = {
  people: ["Abraham Lincoln", "George Washington"],
  civics: [
    "American flag",
    "Bill of Rights",
    "capital",
    "citizen",
    "city",
    "Congress",
    "country",
    "Father of Our Country",
    "government",
    "President",
    "right",
    "Senators",
    "state/states",
    "White House",
  ],
  places: ["America", "United States", "U.S."],
  holidays: [
    "Presidents' Day",
    "Memorial Day",
    "Flag Day",
    "Independence Day",
    "Labor Day",
    "Columbus Day",
    "Thanksgiving",
  ],
  questionWords: ["How", "What", "When", "Where", "Who", "Why"],
  verbs: [
    "can",
    "come",
    "do/does",
    "elects",
    "have/has",
    "is/are/was/be",
    "lives/lived",
    "meet",
    "name",
    "pay",
    "vote",
    "want",
  ],
  otherFunction: ["a", "for", "here", "in", "of", "on", "the", "to", "we"],
  otherContent: [
    "colors",
    "dollar bill",
    "first",
    "largest",
    "many",
    "most",
    "north",
    "one",
    "people",
    "second",
    "south",
  ],
} as const;

/** Official USCIS English writing vocabulary (naturalization test). */
export const WRITING_VOCAB = {
  people: ["Adams", "Lincoln", "Washington"],
  civics: [
    "American Indians",
    "capital",
    "citizens",
    "Civil War",
    "Congress",
    "Father of Our Country",
    "flag",
    "free",
    "freedom of speech",
    "President",
    "right",
    "Senators",
    "state/states",
    "White House",
  ],
  places: [
    "Alaska",
    "California",
    "Canada",
    "Delaware",
    "Mexico",
    "New York City",
    "United States",
    "Washington",
    "Washington, D.C.",
  ],
  months: [
    "February",
    "May",
    "June",
    "July",
    "September",
    "October",
    "November",
  ],
  holidays: [
    "Presidents' Day",
    "Memorial Day",
    "Flag Day",
    "Independence Day",
    "Labor Day",
    "Columbus Day",
    "Thanksgiving",
  ],
  verbs: [
    "can",
    "come",
    "elect",
    "have/has",
    "is/was/be",
    "lives/lived",
    "meets",
    "pay",
    "vote",
    "want",
  ],
  otherFunction: [
    "and",
    "during",
    "for",
    "here",
    "in",
    "of",
    "on",
    "the",
    "to",
    "we",
  ],
  otherContent: [
    "blue",
    "dollar bill",
    "fifty/50",
    "first",
    "largest",
    "most",
    "north",
    "one",
    "one hundred/100",
    "people",
    "red",
    "second",
    "south",
    "taxes",
    "white",
  ],
} as const;

/** Sample reading sentences built only from official reading vocabulary themes. */
export const READING_SENTENCES = [
  "Who was George Washington?",
  "What is the capital of the United States?",
  "When is Independence Day?",
  "Where is the White House?",
  "Why do we pay taxes?",
  "Who elects Congress?",
  "What are the colors of the American flag?",
  "Who lives in the White House?",
  "When do we vote for President?",
  "What is the Bill of Rights?",
];

/** Sample writing sentences (officer dictates; applicant writes). */
export const WRITING_SENTENCES = [
  "Citizens can vote.",
  "The President lives in the White House.",
  "Washington was the Father of Our Country.",
  "Congress meets in Washington, D.C.",
  "Independence Day is in July.",
  "Lincoln was President during the Civil War.",
  "People want freedom of speech.",
  "Senators meet in Congress.",
  "The flag is red, white, and blue.",
  "Citizens elect Congress.",
];
