/** Shared English dictionary — source of truth for keys. */
export const en = {
  brand: "USCivics Quiz",
  logoSubtitle: "Civics practice",
  siteName: "USCivics Quiz",
  tagline: "Free US citizenship civics test practice — 2008 & 2025 USCIS questions.",
  heroSupport:
    "Find your test version, then study with flashcards, smart review, oral practice, and a real interview simulation.",
  startEligibility: "Find my test version",
  practiceHeading: "Or jump straight into practice",
  practice2008: "2008 version",
  practice2008Meta: "100 questions · 10 asked · 6 to pass",
  practice2025: "2025 version",
  practice2025Meta: "128 questions · 20 asked · 12 to pass",
  freeBadge: "Free · No sign-up",
  bilingualBadge: "Multilingual",
  officialBadge: "Official USCIS questions",
  eligibilityTitle: "Which civics test do you take?",
  eligibilityLead: "Two quick questions. We’ll point you to the right practice set.",
  q1: "Did you file Form N-400 before October 20, 2025?",
  q2: "Are you 65 or older AND a permanent resident for 20+ years?",
  yes: "Yes",
  no: "No",
  notSure: "I'm not sure",
  resultSenior:
    "You qualify for the simplified 65/20 test: 10 questions from a marked set of 20 — need 6 correct.",
  result2008: "You take the 2008 version: up to 10 of 100 questions — need 6 correct.",
  result2025: "You take the 2025 version: up to 20 of 128 questions — need 12 correct.",
  startPractice: "Start practice",
  question: "Question",
  of: "of",
  showAnswer: "Reveal answer",
  didYouKnow: "Did you get it right?",
  next: "Next question",
  finish: "Finish",
  yourScore: "Your score",
  passed: "You would pass the interview threshold.",
  notPassed: "Keep going — review and try another round.",
  tryAgain: "Practice again",
  passNeed: "Need",
  correct: "correct",
  answersLabel: "Accepted answers",
  langSwitch: "Language",
  backHome: "Home",
  disclaimer:
    "Not affiliated with or endorsed by USCIS or the U.S. government. Practice questions are for study only.",
  stepOf: "Step",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Study in order — flip, mark, move on",
  modeRandom: "Random",
  modeRandomHint: "Shuffle like the real pool",
  modeSmart: "Smart review",
  modeSmartHint: "Prioritize weak & unseen questions",
  modeSimulate: "Simulate interview",
  modeSimulateHint: "Stops at pass or fail — like USCIS",
  modeBrowse: "Browse all",
  modeBrowseHint: "Search the full pool and jump to any question",
  browseSearch: "Search questions…",
  browseEmpty: "No questions match your search.",
  browseStudy: "Study this card",
  browseSeen: "Seen",
  browseWeak: "Needs work",
  browseStrong: "Strong",
  browseNew: "New",
  zipTitle: "Your local officials (by ZIP)",
  zipLead:
    "Answers for your senators, representative, governor, and state capital depend on where you live. Enter your ZIP to study the right names.",
  zipPlaceholder: "ZIP code",
  zipSubmit: "Look up",
  zipLoading: "Looking up…",
  zipInvalid: "Enter a valid 5-digit U.S. ZIP code.",
  zipError: "Could not look up this ZIP. Try again.",
  zipAmbiguous:
    "This ZIP covers more than one House district — learn which is yours before the interview.",
  zipSenators: "U.S. Senators",
  zipRepresentatives: "U.S. Representative(s)",
  zipGovernor: "Governor",
  zipCapital: "State capital",
  zipVerify: "Always verify current officials before your interview.",
  filterAll: "All",
  progressTitle: "Your progress",
  seen: "Seen",
  streak: "Streak",
  bestStreak: "Best",
  accuracy: "Accuracy",
  weak: "Weak",
  mastered: "Strong",
  resetProgress: "Reset progress",
  resetConfirm: "Clear saved progress for this version?",
  sims: "Sims passed",
  seniorBadge: "65/20",
  changingBannerTitle: "Answers that change",
  changingBannerBody:
    "Some answers depend on elections or appointments. Always verify current officials before your interview.",
  changingBannerLink: "Check USCIS test updates",
  changingCardNote: "This answer can change — verify at USCIS before your interview.",
  interviewHowTitle: "How the real interview works",
  interviewHow1: "The officer asks questions aloud from the official pool.",
  interviewHow2: "They stop when you pass or fail the threshold.",
  interviewHow3: "Think your answer, reveal, then mark honestly.",
  correctCount: "Correct",
  wrongCount: "Wrong",
  failAt: "Fail at",
  passAt: "Pass at",
  stoppedPass: "Interview stopped — you reached the pass score.",
  stoppedFail: "Interview stopped — too many wrong answers.",
  endTest: "End test",
  startSim: "Start simulation",
  nextRandom: "Next random",
  prev: "Previous",
  flip: "Flip",
  nextCard: "Next",
  keyboardHint: "Space reveal · Y / N mark · ← → navigate",
  categoryMastery: "By category",
  poolSize: "In this pool",
  noQuestions: "No questions match this filter.",
  saidCorrectly: "I said it correctly",
  gotWrong: "I got it wrong",
  moreAnswers: "Acceptable answers",
  speakQuestion: "Hear question (EN)",
  speakAnswers: "Hear answers (EN)",
  speakPractice: "Say it out loud in English — the interview is oral.",
  navPractice: "Practice",
  navLearn: "Learn",
  menuOpen: "Open menu",
  menuClose: "Close menu",
  navHome: "Home",
  themeToLight: "Switch to light mode",
  themeToDark: "Switch to dark mode",
  govBannerLead:
    "An unofficial practice website — not a U.S. government site.",
  govBannerHow: "Here’s how you know",
  govBannerOfficial:
    "Official USCIS websites use .gov and are published by the U.S. government. This site is an independent study tool.",
  govBannerSecure:
    "Always verify changing answers and rules on uscis.gov before your interview.",
  uscisAlertTitle: "Which civics test do you take?",
  uscisAlertBody:
    "File Form N-400 before Oct 20, 2025 → 2008 test (100 questions). On or after that date → 2025 test (128 questions). Confirm on USCIS.",
  uscisResourcesHeading: "Official USCIS resources",
  uscisResourcesLead:
    "Study materials and updates from U.S. Citizenship and Immigration Services. We link out — we do not host official PDFs.",
  uscisStudyTitle: "Study for the Test",
  uscisStudyBlurb: "English + civics overview and free study materials",
  uscisUpdatesTitle: "Check for Test Updates",
  uscisUpdatesBlurb: "Officials and answers that change with elections",
  uscis2025Title: "2025 Civics Test",
  uscis2025Blurb: "Policy page for the 2025 naturalization civics test",
  uscisExceptionsTitle: "Exceptions & accommodations",
  uscisExceptionsBlurb: "65/20 and English test exceptions",
  uscisN400Title: "Form N-400",
  uscisN400Blurb: "Application for Naturalization",
  uscisPdf128Title: "128 questions PDF (2025)",
  uscisPdf128Blurb: "Official English Q&A list",
  uscisPdf100Title: "100 questions PDF (2008)",
  uscisPdf100Blurb: "Official English Q&A list",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "Official U.S. Citizenship and Immigration Services site",
  learnTitle: "Study guide & FAQ",
  learnLead: "Key numbers, facts, and answers to common questions about the civics test.",
  keyNumbersTitle: "Critical numbers to memorize",
  faqTitle: "Frequently asked questions",
  guideBranchesTitle: "Three branches of government",
  guideAmendmentsTitle: "Key amendments",
  guideTipsTitle: "How to study",
  tip1: "Say answers out loud — this is an oral interview.",
  tip2: "Practice 15–20 minutes daily for 4–6 weeks.",
  tip3: "Use Smart review for weak questions, then simulate until you pass 3 times in a row.",
  tip4: "Verify changing answers at USCIS before your interview.",
  faqQ1: "Which test version do I take?",
  faqA1:
    "If you filed Form N-400 before October 20, 2025, you take the 2008 test (100 questions). On or after that date, you take the 2025 test (128 questions).",
  faqQ2: "How does the interview scoring work?",
  faqA2:
    "2025: up to 20 questions, need 12 correct; officer stops at 12 correct or 9 wrong. 2008: up to 10 questions, need 6 correct (stops at 6 correct or 5 wrong).",
  faqQ3: "What is the 65/20 special consideration?",
  faqA3:
    "If you are 65+ and a permanent resident for 20+ years, you study only 20 starred questions. The officer asks 10; you need 6 correct. You may take the civics test in your language of choice.",
  faqQ4: "Can I take the civics test in my language?",
  faqA4:
    "Normally the civics test is in English. Exceptions: 65/20 (language of choice), and English exemptions 50/20 or 55/15 for the English portion with an interpreter for civics.",
  faqQ5: "Do some answers change?",
  faqA5:
    "Yes — president, vice president, speaker, chief justice, your senators, representative, governor, and state capital. Check uscis.gov/citizenship/testupdates and use our ZIP lookup.",
  federalTitle: "Current federal officials",
  federalLead:
    "These answers change with elections or appointments. Study the accepted names USCIS lists.",
  federalPresident: "President",
  federalVP: "Vice President",
  federalSpeaker: "Speaker of the House",
  federalChief: "Chief Justice",
  federalParty: "President’s party",
  federalAsOf: "Verified as of",
  modeSpeak: "Speak aloud",
  modeSpeakHint:
    "Hear the English question, then answer with your microphone — like the real interview.",
  speakStart: "Speak my answer",
  speakStop: "Stop listening",
  speakHeard: "You said",
  speakMatch: "Good — that matches an accepted answer.",
  speakNoMatch: "Not a clear match yet. Accepted answers:",
  speakUnsupported:
    "Speech recognition is not available in this browser. Try Chrome, or use Hear answers and self-check.",
  navEnglish: "English test",
  englishTitle: "English reading & writing",
  englishLead:
    "Practice the USCIS English reading and writing vocabulary used in the naturalization interview.",
  readingTitle: "Reading",
  writingTitle: "Writing",
  readingHint: "Read the sentence out loud. Tap play to hear it first.",
  writingHint: "Listen to the sentence, then type it. Spelling counts.",
  writingPrompt: "Write what you hear",
  writingCheck: "Check spelling",
  writingCorrect: "Correct!",
  writingTryAgain: "Try again — target sentence",
  nextSentence: "Next sentence",
} as const;

export type DictKeys = keyof typeof en;
export type Dictionary = Record<DictKeys, string>;
