/** Shared English dictionary — source of truth for keys. */
export const en = {
  brand: "USCivics Quiz",
  logoSubtitle: "Civics practice",
  siteName: "USCivics Quiz",
  homeMetaTitle:
    "USCivics Quiz (uscivics-quiz) — Free USCIS Civics Practice",
  homeMetaDescription:
    "USCivics Quiz at uscivics-quiz.com — free USCIS naturalization civics practice. Official 2008 & 2025 questions, audio, flashcards, interview simulation. No sign-up.",
  tagline:
    "Free USCIS civics practice — know your N-400 filing date, then start in seconds.",
  heroSupport:
    "Official question bank with audio, flashcards, and interview simulation in 10+ languages. No sign-up.",
  startEligibility: "Find my test version",
  practiceHeading: "Start practicing",
  practiceCta: "Open practice",
  practice2008: "2008 civics practice — official questions",
  practice2008Meta: "100 questions · 10 asked · 6 to pass",
  practice2025: "2025 civics practice — official questions",
  practice2025Meta: "128 questions · 20 asked · 12 to pass",
  practiceHubLead:
    "No sign-up. Official USCIS bank with audio and interview simulation — start in seconds.",
  practiceMetaTitleSuffix: "Free USCIS Interview Simulation",
  freeBadge: "Free · No sign-up · Seconds",
  bilingualBadge: "10+ languages",
  officialBadge: "Official USCIS questions",
  diffNoSignup: "Free · No sign-up · Start in seconds",
  diffRightBank:
    "Know which bank to study: N-400 filing date (2008 vs 2025) or 65/20 senior",
  diffOfficialPractice: "Official USCIS questions · Audio · Interview simulation",
  diffLanguages: "Practice in 10+ languages — not an English-only app",
  diffStripAria: "Why practice here",
  startInSecondsCta: "Start practice in seconds",
  linkN400Filing: "N-400 filing date (2008 vs 2025)",
  link6520: "65/20 special consideration",
  linkHowMany: "How many questions are asked",
  linkPassScore: "What score to pass",
  link2025Changes: "2025 civics changes",
  linkPractice2025Senior: "2025 · 65/20 practice",
  linkPractice2008Senior: "2008 · 65/20 practice",
  linkWhichCivicsTest: "Which civics test do I take?",
  linkFailTest: "If you fail the test",
  linkStudyPlan: "30-day study plan",
  linkReadingWriting: "English reading & writing",
  eligibilityTitle: "Which civics test do you take?",
  eligibilityMetaTitle: "Which USCIS Civics Test? 2008, 2025 or 65/20",
  eligibilityLead:
    "A few quick questions. We’ll point you to the right question bank before you study — 2008, 2025, or 65/20. Always confirm on uscis.gov.",
  practiceSeoTitle2008: "2008 Civics Practice — Free USCIS Test",
  practiceSeoTitle2025: "2025 Civics Practice — Free USCIS Test",
  dateUpdatedLabel: "Updated",
  q1: "Did you file Form N-400 before October 20, 2025?",
  q1Hint:
    "Your filing date decides 2008 vs 2025. If you are not sure, check your N-400 receipt or uscis.gov — you can still practice either bank.",
  q2: "Are you 65 or older AND a permanent resident for 20+ years?",
  q2Age: "Are you 65 or older?",
  q2Years: "Have you been a lawful permanent resident (green card) for 20 years or more?",
  yes: "Yes",
  no: "No",
  notSure: "I'm not sure",
  resultSenior:
    "You may qualify for the simplified 65/20 civics test: 10 questions from a marked set of 20 — need 6 correct. Confirm eligibility with USCIS.",
  result2008: "You take the 2008 version: up to 10 of 100 questions — need 6 correct.",
  result2025: "You take the 2025 version: up to 20 of 128 questions — need 12 correct.",
  resultUnsure:
    "We can’t safely pick 2008 vs 2025 without your N-400 filing date. Practice either bank, or confirm on uscis.gov before your interview.",
  eligibilityEnglishExemptNote:
    "Separate English exemptions (for example 50/20 or 55/15) do not change which civics bank you study — only the English reading/writing parts. See our English practice and uscis.gov.",
  eligibilityOfficialNote:
    "This helper is educational only. USCIS decides your test version — verify at uscis.gov before interview day.",
  startPractice: "Start practice",
  question: "Question",
  of: "of",
  showAnswer: "Reveal answer",
  didYouKnow: "Did you get it right?",
  next: "Next question",
  finish: "Finish",
  yourScore: "Your score",
  passed: "You would pass the interview threshold.",
  notPassed: "Keep going — review and try another round.",
  tryAgain: "Practice again",
  passNeed: "Need",
  correct: "correct",
  answersLabel: "Accepted answers",
  langSwitch: "Language",
  backHome: "Home",
  disclaimer:
    "Not affiliated with or endorsed by USCIS or the U.S. government. Practice questions are for study only.",
  stepOf: "Step",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Study in order — flip, mark, move on",
  modeRandom: "Random",
  modeRandomHint: "Shuffle like the real pool",
  modeSmart: "Smart review",
  modeSmartHint: "Prioritize weak & unseen questions",
  modeSimulate: "Simulate interview",
  modeSimulateHint: "Stops at pass or fail — like USCIS",
  modeBrowse: "Browse all",
  modeBrowseHint: "Search the full pool and jump to any question",
  browseSearch: "Search questions…",
  browseEmpty: "No questions match your search.",
  browseStudy: "Study this card",
  browseSeen: "Seen",
  browseWeak: "Needs work",
  browseStrong: "Strong",
  browseNew: "New",
  zipTitle: "Your local officials (by ZIP)",
  zipLead:
    "Answers for your senators, representative, governor, and state capital depend on where you live. Enter your ZIP to study the right names.",
  zipPlaceholder: "ZIP code",
  zipSubmit: "Look up",
  zipLoading: "Looking up…",
  zipInvalid: "Enter a valid 5-digit U.S. ZIP code.",
  zipError: "Could not look up this ZIP. Try again.",
  zipAmbiguous:
    "This ZIP covers more than one House district — learn which is yours before the interview.",
  zipSenators: "U.S. Senators",
  zipRepresentatives: "U.S. Representative(s)",
  zipGovernor: "Governor",
  zipCapital: "State capital",
  zipVerify: "Always verify current officials before your interview.",
  filterAll: "All",
  progressTitle: "Your progress",
  seen: "Seen",
  streak: "Streak",
  bestStreak: "Best",
  accuracy: "Accuracy",
  weak: "Weak",
  mastered: "Strong",
  resetProgress: "Reset progress",
  resetConfirm: "Clear saved progress for this version?",
  sims: "Sims passed",
  seniorBadge: "65/20",
  changingBannerTitle: "Answers that change",
  changingBannerBody:
    "Some answers depend on elections or appointments. Always verify current officials before your interview.",
  changingBannerLink: "Open civics test updates",
  changingCardNote: "This answer can change — verify at USCIS before your interview.",
  interviewHowTitle: "How the real interview works",
  interviewHow1: "The officer asks questions aloud from the official pool.",
  interviewHow2: "They stop when you pass or fail the threshold.",
  interviewHow3: "Think your answer, reveal, then mark honestly.",
  correctCount: "Correct",
  wrongCount: "Wrong",
  failAt: "Fail at",
  passAt: "Pass at",
  stoppedPass: "Interview stopped — you reached the pass score.",
  stoppedFail: "Interview stopped — too many wrong answers.",
  endTest: "End test",
  startSim: "Start simulation",
  nextRandom: "Next random",
  prev: "Previous",
  flip: "Flip",
  nextCard: "Next",
  keyboardHint: "Space reveal · Y / N mark · ← → navigate",
  categoryMastery: "By category",
  poolSize: "In this pool",
  noQuestions: "No questions match this filter.",
  saidCorrectly: "I said it correctly",
  gotWrong: "I got it wrong",
  moreAnswers: "Acceptable answers",
  speakQuestion: "Hear question (EN)",
  speakAnswers: "Hear answers (EN)",
  speakPractice: "Say it out loud in English — the interview is oral.",
  navPractice: "Practice",
  navLearn: "Guides",
  navUpdates: "Updates",
  navCitizenship: "My version",
  govBannerBadge: "Not .gov",
  govBannerLead:
    "Independent civics practice — not a U.S. government website.",
  govBannerHow: "Here’s how you know",
  govBannerOfficialTitle: "Official sites use .gov",
  govBannerOfficial:
    "USCIS and other U.S. government sites end in .gov. This site is a free, independent study tool — not affiliated with or endorsed by USCIS.",
  govBannerSecureTitle: "Verify before interview day",
  govBannerSecure:
    "Always confirm changing answers and test rules on uscis.gov before your interview.",
  updatesHubTitle: "Civics test updates",
  updatesHubLead:
    "Filing date (2008 vs 2025), officials that change, and ZIP lookup — a narrow exam changelog, not a news feed.",
  updatesPolicyHeading: "Policy & exam notes",
  updatesLiveHeading: "Live officials & local answers",
  updatesLiveBadge: "Live",
  updatesCachedBadge: "Cached",
  updatesVerifyNote:
    "Confirm names the week of your interview. Elections and appointments can change accepted answers.",
  homeLiveHeading: "Current officials",
  homeLiveLead:
    "Live federal names for interview day — plus ZIP lookup for senators, representative, governor, and capital.",
  homeLiveCta: "Open test updates",
  navCivicsTest: "Civics Test",
  navReadingTest: "Reading Test",
  navWritingTest: "Writing Test",
  navTest2025: "Civics 2025",
  navTest2008: "Civics 2008",
  navSenior: "65/20",
  menuOpen: "Open menu",
  menuClose: "Close menu",
  navHome: "Home",
  themeToLight: "Switch to light mode",
  themeToDark: "Switch to dark mode",
  uscisUpdatesPageTitle: "Check for Test Updates",
  uscisAlertLabel: "ALERT:",
  uscisAlertBody:
    "USCIS is implementing the 2025 naturalization civics test to align with Executive Order 14161. Aliens who file Form N-400 to apply for naturalization before Oct. 20, 2025, will take the 2008 naturalization civics test. Aliens who file Form N-400 to apply for naturalization on or after Oct. 20, 2025, will take the 2025 test. The new 2025 test is based on the 2020 naturalization civics test, with some modifications to the administration of the test.",
  uscisFilingColDate: "N-400 Filing Date",
  uscisFilingColVersion: "Version of Civics Test",
  uscisFilingBefore: "Before Oct. 20, 2025",
  uscisFilingBeforeVersion: "2008 Naturalization Civics Test",
  uscisFilingAfter: "On or After Oct. 20, 2025",
  uscisFilingAfterVersion: "2025 Naturalization Civics Test",
  uscis2008Heading: "2008 Naturalization Civics Test",
  uscis2008Body:
    "We will administer the 2008 naturalization civics test to aliens applying for naturalization who file a Form N-400 naturalization application before Oct. 20, 2025.",
  uscis2025Heading: "2025 Naturalization Civics Test",
  uscis2025Body:
    "We will administer the 2025 naturalization civics test to aliens applying for naturalization who file Form N-400 on or after Oct. 20, 2025.",
  uscisResourcesHeading: "Official USCIS resources",
  uscisResourcesLead:
    "Study materials and updates from U.S. Citizenship and Immigration Services. We link out — we do not host official PDFs.",
  uscisStudyTitle: "Study for the Test",
  uscisStudyBlurb: "English + civics overview and free study materials",
  uscisUpdatesTitle: "Check for Test Updates",
  uscisUpdatesBlurb: "Officials and answers that change with elections",
  uscis2025Title: "2025 Civics Test",
  uscis2025Blurb: "Policy page for the 2025 naturalization civics test",
  uscisExceptionsTitle: "Exceptions & accommodations",
  uscisExceptionsBlurb: "65/20 and English test exceptions",
  uscisN400Title: "Form N-400",
  uscisN400Blurb: "Application for Naturalization",
  uscisPdf128Title: "128 questions PDF (2025)",
  uscisPdf128Blurb: "Official English Q&A list",
  uscisPdf100Title: "100 questions PDF (2008)",
  uscisPdf100Blurb: "Official English Q&A list",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "Official U.S. Citizenship and Immigration Services site",
  learnTitle: "Study guide & FAQ",
  learnLead: "Key numbers, facts, and answers to common questions about the civics test.",
  keyNumbersTitle: "Critical numbers to memorize",
  faqTitle: "Frequently asked questions",
  guideBranchesTitle: "Three branches of government",
  guideAmendmentsTitle: "Key amendments",
  guideTipsTitle: "How to study",
  tip1: "Say answers out loud — this is an oral interview.",
  tip2: "Practice 15–20 minutes daily for 4–6 weeks.",
  tip3: "Use Smart review for weak questions, then simulate until you pass 3 times in a row.",
  tip4: "Verify changing answers at USCIS before your interview.",
  faqQ1: "Which test version do I take?",
  faqA1:
    "If you filed Form N-400 before October 20, 2025, you take the 2008 test (100 questions). On or after that date, you take the 2025 test (128 questions).",
  faqQ2: "How does the interview scoring work?",
  faqA2:
    "2025: up to 20 questions, need 12 correct; officer stops at 12 correct or 9 wrong. 2008: up to 10 questions, need 6 correct (stops at 6 correct or 5 wrong).",
  faqQ3: "What is the 65/20 special consideration?",
  faqA3:
    "If you are 65+ and a permanent resident for 20+ years, you study only 20 starred questions. The officer asks 10; you need 6 correct. You may take the civics test in your language of choice.",
  faqQ4: "Can I take the civics test in my language?",
  faqA4:
    "Normally the civics test is in English. Exceptions: 65/20 (language of choice), and English exemptions 50/20 or 55/15 for the English portion with an interpreter for civics.",
  faqQ5: "Do some answers change?",
  faqA5:
    "Yes — president, vice president, speaker, chief justice, your senators, representative, governor, and state capital. Use our current officials list and ZIP lookup to stay up to date.",
  federalTitle: "Current federal officials",
  federalLead:
    "These answers change with elections or appointments. Study the accepted names USCIS lists.",
  federalPresident: "President",
  federalVP: "Vice President",
  federalSpeaker: "Speaker of the House",
  federalChief: "Chief Justice",
  federalParty: "President’s party",
  federalAsOf: "Verified as of",
  modeSpeak: "Speak aloud",
  modeSpeakHint:
    "Hear the English question, then answer with your microphone — like the real interview.",
  speakStart: "Speak my answer",
  speakStop: "Stop listening",
  speakHeard: "You said",
  speakMatch: "Good — that matches an accepted answer.",
  speakNoMatch: "Not a clear match yet. Accepted answers:",
  speakUnsupported:
    "Speech recognition is not available in this browser. Try Chrome, or use Hear answers and self-check.",
  navEnglish: "English test",
  englishTitle: "English reading & writing",
  englishLead:
    "Practice the USCIS English reading and writing vocabulary used in the naturalization interview.",
  readingTitle: "Reading",
  writingTitle: "Writing",
  readingHint: "Read the sentence out loud. Tap play to hear it first.",
  writingHint: "Listen to the sentence, then type it. Spelling counts.",
  writingPrompt: "Write what you hear",
  writingCheck: "Check spelling",
  writingCorrect: "Correct!",
  writingTryAgain: "Try again — target sentence",
  nextSentence: "Next sentence",
  navQuestions: "Questions",
  navResources: "Resources",
  seoQuestionsHubTitle: "USCIS civics questions — free study landings",
  seoQuestionsHubLead:
    "Browse all 100 and 128 official civics questions by version, topic, 65/20, or top states — with free audio.",
  seoAll128Title: "All 128 Civics Questions (2025) — Free",
  seoAll128Lead:
    "Every official 2025 USCIS question with free audio — no sign-up, start in seconds. Then run the interview simulation. Available in 10+ languages.",
  seoAll100Title: "All 100 Civics Questions (2008) — Free",
  seoAll100Lead:
    "Full 2008 bank for N-400 filings before October 20, 2025. Free audio, no account — practice the interview simulation when ready.",
  seoSeniorTitle: "65/20 Starred Civics Questions — Free Practice",
  seoSeniorLead:
    "Age 65+ and 20 years LPR? Study only 20 starred questions (10 asked, 6 to pass). Free audio, no sign-up — start in seconds. 10+ languages.",
  seoStartPractice: "Open interactive practice",
  seoAllLandings: "All question landings",
  seoQuestionsCount: "questions on this page",
  seoBadge2025: "2025 test · 128 questions",
  seoBadge2008: "2008 test · 100 questions",
  seoTopicsHeading: "Practice by topic",
  seoStatesHeading: "Top state study pages",
  seoStateLead:
    "Review your state capital and governor for changing civics answers, then practice the full interview set. Use ZIP lookup in practice for senators and your representative.",
  seoStateCapital: "State capital",
  seoStateGovernor: "Governor",
  seoStatePractice: "Practice civics for your interview",
  seoReadingTitle: "English reading practice — USCIS vocabulary",
  seoReadingLead:
    "Practice reading sentences built from the official USCIS English reading vocabulary for the naturalization interview.",
  seoWritingTitle: "English writing practice — USCIS vocabulary",
  seoWritingLead:
    "Listen and write sentences using the official USCIS English writing vocabulary. Spelling counts on test day.",
  learnPostsHeading: "Guides & resources",
  learnPostBack: "Back to learn",
  learnReadMore: "Read more",
  legalBadge: "Legal & trust",
  navAbout: "About",
  navContact: "Contact",
  navPrivacy: "Privacy",
  navTerms: "Terms",
  seoDrillsHeading: "Special study drills",
  seoDrillsLead:
    "Focus on the hardest clusters: key dates, famous names, and officials whose answers change with elections — free audio on every question.",
  seoStatesCount: "state & DC study pages",
  questionsSearchLabel: "Search civics questions",
  questionsSearchSubmit: "Search",
  questionsSearchHint:
    "Search by question number, keywords, or answers across the 2008 and 2025 banks.",
  questionsSearchResults: "Matches",
  exportProgress: "Export progress",
  importProgress: "Import progress",
  exportProgressHint: "Save a backup file to move progress to another device.",
  importProgressDone: "Progress imported.",
  importProgressError: "Could not import that file. Use an export from USCivics Quiz.",
  relatedStudyHeading: "Keep studying",
  relatedStudyLead:
    "Jump between guides, question landings, and interview practice for the same topic.",
  relatedLearn: "Guides",
  relatedQuestions: "Question lists",
  relatedPractice: "Practice",
  errorPageTitle: "Something went wrong",
  errorPageLead:
    "We logged the error so we can fix it. You can try again or go back home.",
  errorPageRetry: "Try again",
  errorPageHome: "Back home",
  notFoundTitle: "Page not found",
  notFoundLead:
    "That link does not match a page on USCivics Quiz. Check the URL or continue studying from home.",
  notFoundHome: "Back home",
  contactFormLead:
    "Send a message — we read every email. Do not include sensitive immigration case numbers you would not put in email.",
  contactFormName: "Your name",
  contactFormEmail: "Your email",
  contactFormMessage: "Message",
  contactFormSubmit: "Send message",
  contactFormSending: "Sending…",
  contactFormSuccess: "Thanks — your message was sent. We will reply by email.",
  contactFormError: "Could not send through the form.",
  contactFormFallback: "Open your email app instead",
  accountSyncTitle: "Optional cloud sync",
  accountSyncLead:
    "Practice stays free without an account. Sign in to back up progress across devices. We never put the question bank behind a paywall.",
  accountEmail: "Email",
  accountPassword: "Password (min 8 characters)",
  accountSignIn: "Sign in",
  accountCreate: "Create account",
  accountSignOut: "Sign out",
  accountSyncNow: "Sync progress now",
  accountSynced: "Progress synced.",
  accountSyncError: "Could not sync. Check your connection and try again.",
  accountSignedInAs: "Signed in as",
  accountUnavailable:
    "Cloud sync is not configured on this deployment yet. Export/import still works offline.",
  accountDeleted: "Account deleted.",
  accountDeleteConfirm: "Delete your account and cloud progress? Local progress on this device stays until you clear site data.",
  accountDelete: "Delete account",
  accountResetSent: "Password reset email sent — check your inbox.",
  accountResetPassword: "Reset password",
  skipToContent: "Skip to main content",
  linkUpdates: "Civics test updates",
  affiliateHeading: "Related prep (optional)",
  affiliateLead:
    "Core practice on this site stays free. Some learners also use a physical book or flashcards — links below may earn us a small commission.",
  affiliateDisclosure:
    "As an Amazon Associate we may earn from qualifying purchases. We are not affiliated with USCIS. Always verify rules on uscis.gov.",
  affiliateItemFlashcards: "Civics flash cards",
  affiliateItemFlashcardsBlurb:
    "Physical cards for oral drill away from the screen.",
  affiliateItemGuide: "Naturalization study guide",
  affiliateItemGuideBlurb:
    "Printed overview to pair with the official USCIS question bank here.",
  affiliateItemEnglish: "English for citizenship practice",
  affiliateItemEnglishBlurb:
    "Extra reading/writing support — still use our free sentence drills too.",
} as const;

export type DictKeys = keyof typeof en;
export type Dictionary = Record<DictKeys, string>;
