import type { Dictionary } from "./en";

export const es: Dictionary = {
  brand: "USCivics Quiz",
  siteName: "USCivics Quiz",
  tagline:
    "Práctica gratis del examen cívico de ciudadanía de EE.UU. — preguntas USCIS 2008 y 2025.",
  heroSupport:
    "Descubrí qué versión te toca y estudiá con flashcards, repaso inteligente, práctica oral y simulación real.",
  startEligibility: "Descubrir mi versión",
  practiceHeading: "O entrá directo a practicar",
  practice2008: "Versión 2008",
  practice2008Meta: "100 preguntas · 10 en el examen · 6 para aprobar",
  practice2025: "Versión 2025",
  practice2025Meta: "128 preguntas · 20 en el examen · 12 para aprobar",
  freeBadge: "Gratis · Sin registro",
  bilingualBadge: "Multilingüe",
  officialBadge: "Preguntas oficiales USCIS",
  eligibilityTitle: "¿Qué examen cívico te toca?",
  eligibilityLead: "Dos preguntas rápidas. Te llevamos al set de práctica correcto.",
  q1: "¿Presentaste el Formulario N-400 antes del 20 de octubre de 2025?",
  q2: "¿Tenés 65 años o más Y sos residente permanente desde hace 20+ años?",
  yes: "Sí",
  no: "No",
  notSure: "No estoy seguro/a",
  resultSenior:
    "Calificás para el examen simplificado 65/20: 10 preguntas de un set marcado de 20 — necesitás 6 correctas.",
  result2008: "Te toca la versión 2008: hasta 10 de 100 preguntas — necesitás 6 correctas.",
  result2025: "Te toca la versión 2025: hasta 20 de 128 preguntas — necesitás 12 correctas.",
  startPractice: "Empezar práctica",
  question: "Pregunta",
  of: "de",
  showAnswer: "Ver respuesta",
  didYouKnow: "¿La acertaste?",
  next: "Siguiente pregunta",
  finish: "Terminar",
  yourScore: "Tu puntaje",
  passed: "Alcanzarías el umbral de aprobación.",
  notPassed: "Seguí — repasá e intentá otra ronda.",
  tryAgain: "Practicar de nuevo",
  passNeed: "Necesitás",
  correct: "correctas",
  answersLabel: "Respuestas aceptadas",
  langSwitch: "Idioma",
  backHome: "Inicio",
  disclaimer:
    "No estamos afiliados ni respaldados por USCIS ni por el gobierno de EE.UU. Las preguntas son solo para estudio.",
  stepOf: "Paso",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Estudiá en orden — volteá, marcá, seguí",
  modeRandom: "Aleatorio",
  modeRandomHint: "Mezcla como el banco real",
  modeSmart: "Repaso smart",
  modeSmartHint: "Prioriza débiles y no vistas",
  modeSimulate: "Simular entrevista",
  modeSimulateHint: "Para al aprobar o fallar — como USCIS",
  modeBrowse: "Ver todas",
  modeBrowseHint: "Buscá en el banco completo y abrí cualquier pregunta",
  browseSearch: "Buscar preguntas…",
  browseEmpty: "Ninguna pregunta coincide con tu búsqueda.",
  browseStudy: "Estudiar esta tarjeta",
  browseSeen: "Vista",
  browseWeak: "A reforzar",
  browseStrong: "Fuerte",
  browseNew: "Nueva",
  zipTitle: "Tus oficiales locales (por ZIP)",
  zipLead:
    "Las respuestas de senadores, representante, gobernador y capital dependen de dónde vivís. Ingresá tu ZIP para estudiar los nombres correctos.",
  zipPlaceholder: "Código ZIP",
  zipSubmit: "Buscar",
  zipLoading: "Buscando…",
  zipInvalid: "Ingresá un ZIP de EE.UU. de 5 dígitos.",
  zipError: "No se pudo consultar este ZIP. Intentá de nuevo.",
  zipAmbiguous:
    "Este ZIP cubre más de un distrito de la Cámara — confirmá cuál es el tuyo antes de la entrevista.",
  zipSenators: "Senadores de EE.UU.",
  zipRepresentatives: "Representante(s)",
  zipGovernor: "Gobernador/a",
  zipCapital: "Capital del estado",
  zipVerify: "Verificá siempre a los oficiales actuales antes de tu entrevista.",
  filterAll: "Todas",
  progressTitle: "Tu progreso",
  seen: "Vistas",
  streak: "Racha",
  bestStreak: "Mejor",
  accuracy: "Precisión",
  weak: "Débiles",
  mastered: "Fuertes",
  resetProgress: "Reiniciar progreso",
  resetConfirm: "¿Borrar el progreso guardado de esta versión?",
  sims: "Sims aprobadas",
  seniorBadge: "65/20",
  changingBannerTitle: "Respuestas que cambian",
  changingBannerBody:
    "Algunas respuestas dependen de elecciones o nombramientos. Verificá siempre a los oficiales actuales antes de tu entrevista.",
  changingBannerLink: "Ver actualizaciones USCIS",
  changingCardNote: "Esta respuesta puede cambiar — verificá en USCIS antes de tu entrevista.",
  interviewHowTitle: "Cómo funciona la entrevista real",
  interviewHow1: "El oficial pregunta en voz alta del banco oficial.",
  interviewHow2: "Para cuando alcanzás aprobar o reprobar.",
  interviewHow3: "Pensá la respuesta, revelá y marcá con honestidad.",
  correctCount: "Correctas",
  wrongCount: "Incorrectas",
  failAt: "Reprobás con",
  passAt: "Aprobás con",
  stoppedPass: "Entrevista detenida — alcanzaste el puntaje de aprobación.",
  stoppedFail: "Entrevista detenida — demasiadas incorrectas.",
  endTest: "Terminar examen",
  startSim: "Iniciar simulación",
  nextRandom: "Siguiente al azar",
  prev: "Anterior",
  flip: "Voltear",
  nextCard: "Siguiente",
  keyboardHint: "Espacio revelar · Y / N marcar · ← → navegar",
  categoryMastery: "Por categoría",
  poolSize: "En este set",
  noQuestions: "No hay preguntas con este filtro.",
  saidCorrectly: "La dije bien",
  gotWrong: "La dije mal",
  moreAnswers: "Respuestas aceptables",
  speakQuestion: "Oír pregunta (EN)",
  speakAnswers: "Oír respuestas (EN)",
  speakPractice: "Decí la respuesta en inglés en voz alta — la entrevista es oral.",
  navPractice: "Practicar",
  navLearn: "Aprender",
  menuOpen: "Abrir menú",
  menuClose: "Cerrar menú",
  navHome: "Inicio",
  learnTitle: "Guía de estudio y FAQ",
  learnLead: "Números clave, datos y respuestas a preguntas frecuentes sobre el examen cívico.",
  keyNumbersTitle: "Números críticos para memorizar",
  faqTitle: "Preguntas frecuentes",
  guideBranchesTitle: "Tres poderes del gobierno",
  guideAmendmentsTitle: "Enmiendas clave",
  guideTipsTitle: "Cómo estudiar",
  tip1: "Decí las respuestas en voz alta — es una entrevista oral.",
  tip2: "Practicá 15–20 minutos diarios durante 4–6 semanas.",
  tip3: "Usá el repaso smart para lo débil y simulá hasta aprobar 3 veces seguidas.",
  tip4: "Verificá las respuestas que cambian en USCIS antes de tu entrevista.",
  faqQ1: "¿Qué versión del examen me toca?",
  faqA1:
    "Si presentaste el N-400 antes del 20 de octubre de 2025, te toca 2008 (100 preguntas). Ese día o después, te toca 2025 (128 preguntas).",
  faqQ2: "¿Cómo se califica la entrevista?",
  faqA2:
    "2025: hasta 20 preguntas, 12 correctas; el oficial para con 12 bien o 9 mal. 2008: hasta 10, 6 correctas (para con 6 bien o 5 mal).",
  faqQ3: "¿Qué es la consideración especial 65/20?",
  faqA3:
    "Si tenés 65+ y sos residente permanente hace 20+ años, estudiás solo 20 preguntas con estrella. El oficial pregunta 10; necesitás 6. Podés rendir civics en el idioma que elijas.",
  faqQ4: "¿Puedo rendir el examen cívico en mi idioma?",
  faqA4:
    "Normalmente es en inglés. Excepciones: 65/20 (idioma de elección) y exenciones de inglés 50/20 o 55/15 con intérprete para civics.",
  faqQ5: "¿Algunas respuestas cambian?",
  faqA5:
    "Sí — presidente, vicepresidente, speaker, juez presidente, senadores, representante, gobernador y capital. Revisá uscis.gov/citizenship/testupdates y usá la búsqueda por ZIP.",
  federalTitle: "Oficiales federales actuales",
  federalLead:
    "Estas respuestas cambian con elecciones o nombramientos. Estudiá los nombres que acepta USCIS.",
  federalPresident: "Presidente",
  federalVP: "Vicepresidente",
  federalSpeaker: "Speaker de la Cámara",
  federalChief: "Juez presidente",
  federalParty: "Partido del presidente",
  federalAsOf: "Verificado al",
  modeSpeak: "Hablar en voz alta",
  modeSpeakHint:
    "Escuchá la pregunta en inglés y respondé con el micrófono — como en la entrevista real.",
  speakStart: "Decir mi respuesta",
  speakStop: "Dejar de escuchar",
  speakHeard: "Dijiste",
  speakMatch: "Bien — coincide con una respuesta aceptada.",
  speakNoMatch: "Aún no coincide claro. Respuestas aceptadas:",
  speakUnsupported:
    "El reconocimiento de voz no está disponible en este navegador. Probá Chrome, o usá Oír respuestas.",
  navEnglish: "Inglés",
  englishTitle: "Reading y writing en inglés",
  englishLead:
    "Practicá el vocabulario oficial USCIS de lectura y escritura de la entrevista de naturalización.",
  readingTitle: "Reading",
  writingTitle: "Writing",
  readingHint: "Leé la oración en voz alta. Tocá play para oírla primero.",
  writingHint: "Escuchá la oración y escribila. Cuenta la ortografía.",
  writingPrompt: "Escribí lo que escuchás",
  writingCheck: "Revisar",
  writingCorrect: "¡Correcto!",
  writingTryAgain: "Intentá de nuevo — oración objetivo",
  nextSentence: "Siguiente oración",
};
