import type { Dictionary } from "./en";

export const es: Dictionary = {
  brand: "USCivics Quiz",
  logoSubtitle: "Práctica cívica",
  siteName: "USCivics Quiz",
  homeMetaTitle:
    "USCivics Quiz (uscivics-quiz) — Práctica cívica USCIS gratis",
  homeMetaDescription:
    "USCivics Quiz en uscivics-quiz.com — práctica gratuita de civismo USCIS. Preguntas oficiales 2008 y 2025, audio, flashcards y simulación de entrevista. Sin registro.",
  tagline:
    "Práctica cívica USCIS gratis — sabé tu fecha de N-400 y empezá en segundos.",
  heroSupport:
    "Banco oficial con audio, flashcards y simulación de entrevista en más de 10 idiomas. Sin registro.",
  startEligibility: "Descubrir mi versión",
  practiceHeading: "Empezar a practicar",
  practiceCta: "Abrir práctica",
  practice2008: "Práctica cívica 2008 — preguntas oficiales",
  practice2008Meta: "100 preguntas · 10 en el examen · 6 para aprobar",
  practice2025: "Práctica cívica 2025 — preguntas oficiales",
  practice2025Meta: "128 preguntas · 20 en el examen · 12 para aprobar",
  practiceHubLead:
    "Sin registro. Banco oficial USCIS con audio y simulación de entrevista — empezá en segundos.",
  practiceMetaTitleSuffix: "Simulación de entrevista USCIS gratis",
  freeBadge: "Gratis · Sin registro · Segundos",
  bilingualBadge: "Más de 10 idiomas",
  officialBadge: "Preguntas oficiales USCIS",
  diffNoSignup: "Gratis · Sin registro · Empezá en segundos",
  diffRightBank:
    "Sabé qué banco estudiar: fecha de N-400 (2008 vs 2025) o 65/20 senior",
  diffOfficialPractice: "Preguntas oficiales USCIS · Audio · Simulación de entrevista",
  diffLanguages: "Practicá en más de 10 idiomas — no solo en inglés",
  diffStripAria: "Por qué practicar acá",
  startInSecondsCta: "Empezar a practicar en segundos",
  linkN400Filing: "Fecha de N-400 (2008 vs 2025)",
  link6520: "Consideración especial 65/20",
  linkHowMany: "Cuántas preguntas hacen",
  linkPassScore: "Qué puntaje necesitás",
  link2025Changes: "Cambios del civismo 2025",
  linkPractice2025Senior: "2025 · práctica 65/20",
  linkPractice2008Senior: "2008 · práctica 65/20",
  linkWhichCivicsTest: "¿Qué examen cívico me toca?",
  linkFailTest: "Si reprobás el examen",
  linkStudyPlan: "Plan de 30 días",
  linkReadingWriting: "Inglés: lectura y escritura",
  eligibilityTitle: "¿Qué examen cívico te toca?",
  eligibilityMetaTitle: "¿Qué examen cívico USCIS? 2008, 2025 o 65/20",
  eligibilityLead:
    "Dos preguntas rápidas. Te llevamos al banco correcto antes de estudiar — 2008, 2025 o 65/20.",
  practiceSeoTitle2008: "Práctica cívica 2008 — USCIS gratis",
  practiceSeoTitle2025: "Práctica cívica 2025 — USCIS gratis",
  dateUpdatedLabel: "Actualizado",
  q1: "¿Presentaste el Formulario N-400 antes del 20 de octubre de 2025?",
  q2: "¿Tenés 65 años o más Y sos residente permanente desde hace 20+ años?",
  yes: "Sí",
  no: "No",
  notSure: "No estoy seguro/a",
  resultSenior:
    "Calificás para el examen simplificado 65/20: 10 preguntas de un set marcado de 20 — necesitás 6 correctas.",
  result2008: "Te toca la versión 2008: hasta 10 de 100 preguntas — necesitás 6 correctas.",
  result2025: "Te toca la versión 2025: hasta 20 de 128 preguntas — necesitás 12 correctas.",
  startPractice: "Empezar práctica",
  question: "Pregunta",
  of: "de",
  showAnswer: "Ver respuesta",
  didYouKnow: "¿La acertaste?",
  next: "Siguiente pregunta",
  finish: "Terminar",
  yourScore: "Tu puntaje",
  passed: "Alcanzarías el umbral de aprobación.",
  notPassed: "Seguí — repasá e intentá otra ronda.",
  tryAgain: "Practicar de nuevo",
  passNeed: "Necesitás",
  correct: "correctas",
  answersLabel: "Respuestas aceptadas",
  langSwitch: "Idioma",
  backHome: "Inicio",
  disclaimer:
    "No estamos afiliados ni respaldados por USCIS ni por el gobierno de EE.UU. Las preguntas son solo para estudio.",
  stepOf: "Paso",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Estudiá en orden — volteá, marcá, seguí",
  modeRandom: "Aleatorio",
  modeRandomHint: "Mezcla como el banco real",
  modeSmart: "Repaso smart",
  modeSmartHint: "Prioriza débiles y no vistas",
  modeSimulate: "Simular entrevista",
  modeSimulateHint: "Para al aprobar o fallar — como USCIS",
  modeBrowse: "Ver todas",
  modeBrowseHint: "Buscá en el banco completo y abrí cualquier pregunta",
  browseSearch: "Buscar preguntas…",
  browseEmpty: "Ninguna pregunta coincide con tu búsqueda.",
  browseStudy: "Estudiar esta tarjeta",
  browseSeen: "Vista",
  browseWeak: "A reforzar",
  browseStrong: "Fuerte",
  browseNew: "Nueva",
  zipTitle: "Tus oficiales locales (por ZIP)",
  zipLead:
    "Las respuestas de senadores, representante, gobernador y capital dependen de dónde vivís. Ingresá tu ZIP para estudiar los nombres correctos.",
  zipPlaceholder: "Código ZIP",
  zipSubmit: "Buscar",
  zipLoading: "Buscando…",
  zipInvalid: "Ingresá un ZIP de EE.UU. de 5 dígitos.",
  zipError: "No se pudo consultar este ZIP. Intentá de nuevo.",
  zipAmbiguous:
    "Este ZIP cubre más de un distrito de la Cámara — confirmá cuál es el tuyo antes de la entrevista.",
  zipSenators: "Senadores de EE.UU.",
  zipRepresentatives: "Representante(s)",
  zipGovernor: "Gobernador/a",
  zipCapital: "Capital del estado",
  zipVerify: "Verificá siempre a los oficiales actuales antes de tu entrevista.",
  filterAll: "Todas",
  progressTitle: "Tu progreso",
  seen: "Vistas",
  streak: "Racha",
  bestStreak: "Mejor",
  accuracy: "Precisión",
  weak: "Débiles",
  mastered: "Fuertes",
  resetProgress: "Reiniciar progreso",
  resetConfirm: "¿Borrar el progreso guardado de esta versión?",
  sims: "Sims aprobadas",
  seniorBadge: "65/20",
  changingBannerTitle: "Respuestas que cambian",
  changingBannerBody:
    "Algunas respuestas dependen de elecciones o nombramientos. Verificá siempre a los oficiales actuales antes de tu entrevista.",
  changingBannerLink: "Abrir actualizaciones del examen",
  changingCardNote: "Esta respuesta puede cambiar — verificá en USCIS antes de tu entrevista.",
  interviewHowTitle: "Cómo funciona la entrevista real",
  interviewHow1: "El oficial pregunta en voz alta del banco oficial.",
  interviewHow2: "Para cuando alcanzás aprobar o reprobar.",
  interviewHow3: "Pensá la respuesta, revelá y marcá con honestidad.",
  correctCount: "Correctas",
  wrongCount: "Incorrectas",
  failAt: "Reprobás con",
  passAt: "Aprobás con",
  stoppedPass: "Entrevista detenida — alcanzaste el puntaje de aprobación.",
  stoppedFail: "Entrevista detenida — demasiadas incorrectas.",
  endTest: "Terminar examen",
  startSim: "Iniciar simulación",
  nextRandom: "Siguiente al azar",
  prev: "Anterior",
  flip: "Voltear",
  nextCard: "Siguiente",
  keyboardHint: "Espacio revelar · Y / N marcar · ← → navegar",
  categoryMastery: "Por categoría",
  poolSize: "En este set",
  noQuestions: "No hay preguntas con este filtro.",
  saidCorrectly: "La dije bien",
  gotWrong: "La dije mal",
  moreAnswers: "Respuestas aceptables",
  speakQuestion: "Oír pregunta (EN)",
  speakAnswers: "Oír respuestas (EN)",
  speakPractice: "Decí la respuesta en inglés en voz alta — la entrevista es oral.",
  navPractice: "Practicar",
  navLearn: "Guías",
  navCitizenship: "Mi versión",
  navCivicsTest: "Examen cívico",
  navReadingTest: "Reading test",
  navWritingTest: "Writing test",
  navTest2025: "Cívico 2025",
  navTest2008: "Cívico 2008",
  navSenior: "65/20",
  menuOpen: "Abrir menú",
  menuClose: "Cerrar menú",
  navHome: "Inicio",
  themeToLight: "Cambiar a modo claro",
  themeToDark: "Cambiar a modo oscuro",
  uscisUpdatesPageTitle: "Consultar actualizaciones del examen",
  uscisAlertLabel: "ALERTA:",
  uscisAlertBody:
    "USCIS está implementando el examen de educación cívica de naturalización 2025 para alinearlo con la Orden Ejecutiva 14161. Las personas que presenten el Formulario N-400 para solicitar la naturalización antes del 20 de oct. de 2025 tomarán el examen de educación cívica de naturalización 2008. Las personas que presenten el Formulario N-400 el 20 de oct. de 2025 o después tomarán el examen 2025. El nuevo examen 2025 se basa en el examen de educación cívica de naturalización 2020, con algunas modificaciones en la administración del examen.",
  uscisFilingColDate: "Fecha de presentación del N-400",
  uscisFilingColVersion: "Versión del examen de educación cívica",
  uscisFilingBefore: "Antes del 20 de oct. de 2025",
  uscisFilingBeforeVersion: "Examen de educación cívica de naturalización 2008",
  uscisFilingAfter: "El 20 de oct. de 2025 o después",
  uscisFilingAfterVersion: "Examen de educación cívica de naturalización 2025",
  uscis2008Heading: "Examen de educación cívica de naturalización 2008",
  uscis2008Body:
    "Administraremos el examen de educación cívica de naturalización 2008 a las personas que soliciten la naturalización y presenten el Formulario N-400 antes del 20 de oct. de 2025.",
  uscis2025Heading: "Examen de educación cívica de naturalización 2025",
  uscis2025Body:
    "Administraremos el examen de educación cívica de naturalización 2025 a las personas que soliciten la naturalización y presenten el Formulario N-400 el 20 de oct. de 2025 o después.",
  uscisResourcesHeading: "Recursos oficiales de USCIS",
  uscisResourcesLead:
    "Materiales y actualizaciones de U.S. Citizenship and Immigration Services. Enlazamos a USCIS — no alojamos PDFs oficiales.",
  uscisStudyTitle: "Estudiar para el examen",
  uscisStudyBlurb: "Resumen de inglés + civismo y materiales gratis",
  uscisUpdatesTitle: "Actualizaciones del examen",
  uscisUpdatesBlurb: "Funcionarios y respuestas que cambian con elecciones",
  uscis2025Title: "Examen cívico 2025",
  uscis2025Blurb: "Página de política del examen 2025",
  uscisExceptionsTitle: "Excepciones y adaptaciones",
  uscisExceptionsBlurb: "65/20 y excepciones del examen de inglés",
  uscisN400Title: "Formulario N-400",
  uscisN400Blurb: "Solicitud de naturalización",
  uscisPdf128Title: "PDF 128 preguntas (2025)",
  uscisPdf128Blurb: "Lista oficial EN de preguntas y respuestas",
  uscisPdf100Title: "PDF 100 preguntas (2008)",
  uscisPdf100Blurb: "Lista oficial EN de preguntas y respuestas",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "Sitio oficial de USCIS",
  learnTitle: "Guía de estudio y FAQ",
  learnLead: "Números clave, datos y respuestas a preguntas frecuentes sobre el examen cívico.",
  keyNumbersTitle: "Números críticos para memorizar",
  faqTitle: "Preguntas frecuentes",
  guideBranchesTitle: "Tres poderes del gobierno",
  guideAmendmentsTitle: "Enmiendas clave",
  guideTipsTitle: "Cómo estudiar",
  tip1: "Decí las respuestas en voz alta — es una entrevista oral.",
  tip2: "Practicá 15–20 minutos diarios durante 4–6 semanas.",
  tip3: "Usá el repaso smart para lo débil y simulá hasta aprobar 3 veces seguidas.",
  tip4: "Verificá las respuestas que cambian en USCIS antes de tu entrevista.",
  faqQ1: "¿Qué versión del examen me toca?",
  faqA1:
    "Si presentaste el N-400 antes del 20 de octubre de 2025, te toca 2008 (100 preguntas). Ese día o después, te toca 2025 (128 preguntas).",
  faqQ2: "¿Cómo se califica la entrevista?",
  faqA2:
    "2025: hasta 20 preguntas, 12 correctas; el oficial para con 12 bien o 9 mal. 2008: hasta 10, 6 correctas (para con 6 bien o 5 mal).",
  faqQ3: "¿Qué es la consideración especial 65/20?",
  faqA3:
    "Si tenés 65+ y sos residente permanente hace 20+ años, estudiás solo 20 preguntas con estrella. El oficial pregunta 10; necesitás 6. Podés rendir civics en el idioma que elijas.",
  faqQ4: "¿Puedo rendir el examen cívico en mi idioma?",
  faqA4:
    "Normalmente es en inglés. Excepciones: 65/20 (idioma de elección) y exenciones de inglés 50/20 o 55/15 con intérprete para civics.",
  faqQ5: "¿Algunas respuestas cambian?",
  faqA5:
    "Sí — presidente, vicepresidente, speaker, juez presidente, senadores, representante, gobernador y capital. Usá nuestra lista de oficiales y la búsqueda por ZIP.",
  federalTitle: "Oficiales federales actuales",
  federalLead:
    "Estas respuestas cambian con elecciones o nombramientos. Estudiá los nombres que acepta USCIS.",
  federalPresident: "Presidente",
  federalVP: "Vicepresidente",
  federalSpeaker: "Speaker de la Cámara",
  federalChief: "Juez presidente",
  federalParty: "Partido del presidente",
  federalAsOf: "Verificado al",
  modeSpeak: "Hablar en voz alta",
  modeSpeakHint:
    "Escuchá la pregunta en inglés y respondé con el micrófono — como en la entrevista real.",
  speakStart: "Decir mi respuesta",
  speakStop: "Dejar de escuchar",
  speakHeard: "Dijiste",
  speakMatch: "Bien — coincide con una respuesta aceptada.",
  speakNoMatch: "Aún no coincide claro. Respuestas aceptadas:",
  speakUnsupported:
    "El reconocimiento de voz no está disponible en este navegador. Probá Chrome, o usá Oír respuestas.",
  navEnglish: "Inglés",
  englishTitle: "Reading y writing en inglés",
  englishLead:
    "Practicá el vocabulario oficial USCIS de lectura y escritura de la entrevista de naturalización.",
  readingTitle: "Reading",
  writingTitle: "Writing",
  readingHint: "Leé la oración en voz alta. Tocá play para oírla primero.",
  writingHint: "Escuchá la oración y escribila. Cuenta la ortografía.",
  writingPrompt: "Escribí lo que escuchás",
  writingCheck: "Revisar",
  writingCorrect: "¡Correcto!",
  writingTryAgain: "Intentá de nuevo — oración objetivo",
  nextSentence: "Siguiente oración",
  navQuestions: "Preguntas",
  navResources: "Recursos",
  seoQuestionsHubTitle: "Preguntas cívicas USCIS — landings gratis",
  seoQuestionsHubLead:
    "Explorá las 100 y 128 preguntas oficiales por versión, tema, 65/20 o estados principales — con audio gratis.",
  seoAll128Title: "Las 128 preguntas cívicas (2025) — Gratis",
  seoAll128Lead:
    "Las 128 preguntas oficiales USCIS 2025 con audio gratis — sin registro, empezá en segundos. Después simulá la entrevista. En más de 10 idiomas.",
  seoAll100Title: "Las 100 preguntas cívicas (2008) — Gratis",
  seoAll100Lead:
    "Banco 2008 completo si presentaste el N-400 antes del 20 de octubre de 2025. Audio gratis, sin cuenta — simulá la entrevista cuando quieras.",
  seoSeniorTitle: "Preguntas 65/20 con estrella — Práctica gratis",
  seoSeniorLead:
    "¿65+ y 20 años LPR? Estudiá solo 20 con estrella (piden 10; necesitás 6). Audio gratis, sin registro — empezá en segundos. Más de 10 idiomas.",
  seoStartPractice: "Abrir práctica interactiva",
  seoAllLandings: "Todas las landings",
  seoQuestionsCount: "preguntas en esta página",
  seoBadge2025: "Examen 2025 · 128 preguntas",
  seoBadge2008: "Examen 2008 · 100 preguntas",
  seoTopicsHeading: "Practicar por tema",
  seoStatesHeading: "Páginas por estado (top)",
  seoStateLead:
    "Revisá capital y gobernador para respuestas que cambian, y practicá el set completo. Usá ZIP en la práctica para senadores y representante.",
  seoStateCapital: "Capital del estado",
  seoStateGovernor: "Gobernador/a",
  seoStatePractice: "Practicar civismo para tu entrevista",
  seoReadingTitle: "Práctica de reading en inglés — vocabulario USCIS",
  seoReadingLead:
    "Practicá oraciones con el vocabulario oficial de reading del examen de naturalización.",
  seoWritingTitle: "Práctica de writing en inglés — vocabulario USCIS",
  seoWritingLead:
    "Escuchá y escribí oraciones con el vocabulario oficial de writing. La ortografía cuenta.",
  learnPostsHeading: "Guías y recursos",
  learnPostBack: "Volver a aprender",
  learnReadMore: "Leer más",
  legalBadge: "Legal y confianza",
  navAbout: "Acerca de",
  navContact: "Contacto",
  navPrivacy: "Privacidad",
  navTerms: "Términos",
  seoDrillsHeading: "Drills especiales",
  seoDrillsLead:
    "Enfocate en lo más difícil: fechas clave, nombres famosos y oficiales cuyas respuestas cambian con las elecciones — audio gratis en cada pregunta.",
  seoStatesCount: "páginas de estados y DC",
  questionsSearchLabel: "Buscar preguntas cívicas",
  questionsSearchSubmit: "Buscar",
  questionsSearchHint:
    "Buscá por número de pregunta, palabras clave o respuestas en los bancos de 2008 y 2025.",
  questionsSearchResults: "Coincidencias",
  exportProgress: "Exportar progreso",
  importProgress: "Importar progreso",
  exportProgressHint: "Guarda un archivo de respaldo para pasar el progreso a otro dispositivo.",
  importProgressDone: "Progreso importado.",
  importProgressError: "No se pudo importar ese archivo. Usa una exportación de USCivics Quiz.",
  relatedStudyHeading: "Seguí estudiando",
  relatedStudyLead: "Saltá entre guías, listados de preguntas y práctica de entrevista del mismo tema.",
  relatedLearn: "Guías",
  relatedQuestions: "Listas de preguntas",
  relatedPractice: "Práctica",

  errorPageTitle: "Algo salió mal",
  errorPageLead: "Registramos el error para poder corregirlo. Podés reintentar o volver al inicio.",
  errorPageRetry: "Reintentar",
  errorPageHome: "Volver al inicio",
  notFoundTitle: "Página no encontrada",
  notFoundLead: "Ese enlace no coincide con una página de USCivics Quiz. Revisá la URL o seguí estudiando desde el inicio.",
  notFoundHome: "Volver al inicio",

  contactFormLead: "Enviá un mensaje — leemos cada email. No incluyas números de caso sensibles que no pondrías en un correo.",
  contactFormName: "Tu nombre",
  contactFormEmail: "Tu email",
  contactFormMessage: "Mensaje",
  contactFormSubmit: "Enviar mensaje",
  contactFormSending: "Enviando…",
  contactFormSuccess: "Gracias — tu mensaje se envió. Te responderemos por email.",
  contactFormError: "No se pudo enviar por el formulario.",
  contactFormFallback: "Abrí tu app de email",
  q1Hint: "Tu fecha de presentación decide 2008 vs 2025. Si no estás seguro, revisá el recibo N-400 o uscis.gov — igual podés practicar cualquiera de los dos bancos.",
  q2Age: "¿Tenés 65 años o más?",
  q2Years: "¿Sos residente permanente legal (green card) hace 20 años o más?",
  resultUnsure: "No podemos elegir con seguridad 2008 vs 2025 sin tu fecha de N-400. Practicá cualquiera de los bancos, o confirmá en uscis.gov antes de la entrevista.",
  eligibilityEnglishExemptNote: "Las exenciones de inglés (por ejemplo 50/20 o 55/15) no cambian qué banco de civismo estudiás — solo lectura/escritura. Ver nuestra práctica de inglés y uscis.gov.",
  eligibilityOfficialNote: "Este asistente es solo educativo. USCIS decide tu versión del examen — verificá en uscis.gov antes del día de la entrevista.",
  accountSyncTitle: "Sync opcional en la nube",
  accountSyncLead: "La práctica sigue gratis sin cuenta. Iniciá sesión para respaldar el progreso entre dispositivos. Nunca ponemos el banco de preguntas detrás de un paywall.",
  accountEmail: "Email",
  accountPassword: "Contraseña (mín. 8 caracteres)",
  accountSignIn: "Iniciar sesión",
  accountCreate: "Crear cuenta",
  accountSignOut: "Cerrar sesión",
  accountSyncNow: "Sincronizar ahora",
  accountSynced: "Progreso sincronizado.",
  accountSyncError: "No se pudo sincronizar. Revisá la conexión e intentá de nuevo.",
  accountSignedInAs: "Sesión iniciada como",
  accountUnavailable: "El sync en la nube no está configurado en este deploy. Exportar/importar sigue funcionando sin conexión.",
  accountDeleted: "Cuenta eliminada.",
  accountDeleteConfirm: "¿Eliminar tu cuenta y el progreso en la nube? El progreso local en este dispositivo queda hasta que borres los datos del sitio.",
  accountDelete: "Eliminar cuenta",
  accountResetSent: "Email de restablecimiento enviado — revisá tu bandeja.",
  accountResetPassword: "Restablecer contraseña",
  navUpdates: "Actualizaciones",
  govBannerLead: "Práctica cívica independiente — no es un sitio del gobierno de EE. UU.",
  govBannerHow: "Así lo sabés",
  govBannerSecureTitle: "Verificá antes de la entrevista",
  govBannerOfficialTitle: "Los sitios oficiales usan .gov",
  govBannerBadge: "No es .gov",
  govBannerOfficial: "USCIS y otros sitios del gobierno de EE. UU. terminan en .gov. Este sitio es una herramienta de estudio gratuita e independiente — sin afiliación ni respaldo de USCIS.",
  govBannerSecure: "Confirmá siempre las respuestas que cambian y las reglas del examen en uscis.gov antes de tu entrevista.",
  updatesHubTitle: "Actualizaciones del examen cívico",
  updatesHubLead: "Fecha de presentación (2008 vs 2025), funcionarios que cambian y búsqueda por ZIP — changelog estrecho del examen, no un feed de noticias.",
  updatesPolicyHeading: "Notas de política y examen",
  updatesLiveHeading: "Funcionarios en vivo y respuestas locales",
  updatesLiveBadge: "En vivo",
  updatesCachedBadge: "En caché",
  updatesVerifyNote: "Confirmá los nombres la semana de tu entrevista. Elecciones y nombramientos pueden cambiar las respuestas aceptadas.",
  homeLiveHeading: "Funcionarios actuales",
  homeLiveLead: "Nombres federales en vivo para el día de la entrevista — más búsqueda por ZIP para senadores, representante, gobernador y capital.",
  homeLiveCta: "Abrir actualizaciones",
  skipToContent: "Saltar al contenido principal",

  linkUpdates: "Actualizaciones del examen cívico",
  affiliateHeading: "Prep relacionado (opcional)",
  affiliateLead: "La práctica central en este sitio sigue gratis. Algunos también usan un libro o flashcards — los enlaces de abajo pueden darnos una comisión pequeña.",
  affiliateDisclosure: "Como Amazon Associate podemos ganar con compras calificadas. No estamos afiliados a USCIS. Verificá siempre las reglas en uscis.gov.",
  affiliateItemFlashcards: "Flashcards de civics",
  affiliateItemFlashcardsBlurb: "Tarjetas físicas para practicar en voz alta fuera de la pantalla.",
  affiliateItemGuide: "Guía de naturalización",
  affiliateItemGuideBlurb: "Resumen impreso para combinar con el banco oficial USCIS aquí.",
  affiliateItemEnglish: "Inglés para ciudadanía",
  affiliateItemEnglishBlurb: "Apoyo extra de lectura/escritura — seguí usando nuestros drills gratis.",
};
