import type { Dictionary } from "./en";

export const fr: Dictionary = {
  brand: "USCivics Quiz",
  logoSubtitle: "Pratique de civisme",
  siteName: "USCivics Quiz",
  tagline: "Pratique civique USCIS gratuite — connaissez votre date de dépôt N-400 (2008 vs 2025) et commencez en quelques secondes. Sans inscription.",
  heroSupport: "Banque officielle avec audio, flashcards et simulation d'entretien — en plus de 10 langues.",
  startEligibility: "Trouver ma version",
  practiceHeading: "Commencer la pratique",
  practiceCta: "Ouvrir la pratique",
  practice2008: "Pratique civique 2008 — questions officielles",
  practice2008Meta: "100 questions · 10 posées · 6 pour réussir",
  practice2025: "Pratique civique 2025 — questions officielles",
  practice2025Meta: "128 questions · 20 posées · 12 pour réussir",
  freeBadge: "Gratuit · Sans inscription · Secondes",
  bilingualBadge: "Plus de 10 langues",
  officialBadge: "Questions officielles USCIS",
  practiceHubLead: "Sans inscription. Banque USCIS officielle avec audio et simulation d'entretien — commencez en quelques secondes.",
  practiceMetaTitleSuffix: "Simulation d'entretien USCIS gratuite",
  diffNoSignup: "Gratuit · Sans inscription · Commencez en quelques secondes",
  diffRightBank: "Sachez quelle banque étudier : date N-400 (2008 vs 2025) ou 65/20 senior",
  diffOfficialPractice: "Questions USCIS officielles · Audio · Simulation d'entretien",
  diffLanguages: "Pratiquez en plus de 10 langues — pas seulement en anglais",
  diffStripAria: "Pourquoi s'entraîner ici",
  startInSecondsCta: "Commencer en quelques secondes",
  linkN400Filing: "Date de dépôt N-400 (2008 vs 2025)",
  link6520: "Considération spéciale 65/20",
  linkHowMany: "Combien de questions sont posées",
  linkPassScore: "Quel score pour réussir",
  link2025Changes: "Changements civiques 2025",
  linkPractice2025Senior: "2025 · pratique 65/20",
  linkPractice2008Senior: "2008 · pratique 65/20",
  linkWhichCivicsTest: "Quel test de civisme ?",
  linkFailTest: "Si vous échouez au test",
  linkStudyPlan: "Plan 30 jours",
  linkReadingWriting: "Anglais lecture et écriture",
  eligibilityTitle: "Quel test de civisme passez-vous ?",
  eligibilityLead: "Deux questions rapides. Nous vous orientons vers la bonne banque avant d'étudier — 2008, 2025 ou 65/20.",
  q1: "Avez-vous déposé le formulaire N-400 avant le 20 octobre 2025 ?",
  q2: "Avez-vous 65 ans ou plus ET êtes-vous résident permanent depuis 20 ans ou plus ?",
  yes: "Oui",
  no: "Non",
  notSure: "Je ne suis pas sûr(e)",
  resultSenior:
    "Vous êtes admissible au test simplifié 65/20 : 10 questions parmi un ensemble marqué de 20 — 6 correctes requises.",
  result2008: "Vous passez la version 2008 : jusqu'à 10 questions sur 100 — 6 correctes requises.",
  result2025: "Vous passez la version 2025 : jusqu'à 20 questions sur 128 — 12 correctes requises.",
  startPractice: "Commencer la pratique",
  question: "Question",
  of: "sur",
  showAnswer: "Révéler la réponse",
  didYouKnow: "Avez-vous bien répondu ?",
  next: "Question suivante",
  finish: "Terminer",
  yourScore: "Votre score",
  passed: "Vous atteindriez le seuil de réussite de l'entretien.",
  notPassed: "Continuez — révisez et réessayez.",
  tryAgain: "Pratiquer à nouveau",
  passNeed: "Il faut",
  correct: "correctes",
  answersLabel: "Réponses acceptées",
  langSwitch: "Langue",
  backHome: "Accueil",
  disclaimer:
    "Non affilié à l'USCIS ou au gouvernement des États-Unis, et non approuvé par eux. Les questions de pratique sont uniquement à des fins d'étude.",
  stepOf: "Étape",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Étudiez dans l'ordre — retournez, marquez, continuez",
  modeRandom: "Aléatoire",
  modeRandomHint: "Mélange comme le vrai lot de questions",
  modeSmart: "Révision intelligente",
  modeSmartHint: "Priorité aux questions faibles et non vues",
  modeSimulate: "Simuler l'entretien",
  modeSimulateHint: "S'arrête en cas de réussite ou d'échec — comme à l'USCIS",
  modeBrowse: "Tout parcourir",
  modeBrowseHint: "Recherchez dans tout le lot et accédez à n'importe quelle question",
  browseSearch: "Rechercher des questions…",
  browseEmpty: "Aucune question ne correspond à votre recherche.",
  browseStudy: "Étudier cette carte",
  browseSeen: "Vue",
  browseWeak: "À travailler",
  browseStrong: "Solide",
  browseNew: "Nouvelle",
  zipTitle: "Vos élus locaux (par code ZIP)",
  zipLead:
    "Les réponses concernant vos sénateurs, votre représentant, votre gouverneur et la capitale de votre État dépendent de votre lieu de résidence. Entrez votre code ZIP pour étudier les bons noms.",
  zipPlaceholder: "Code ZIP",
  zipSubmit: "Rechercher",
  zipLoading: "Recherche en cours…",
  zipInvalid: "Entrez un code ZIP américain valide à 5 chiffres.",
  zipError: "Impossible de trouver ce code ZIP. Réessayez.",
  zipAmbiguous:
    "Ce code ZIP couvre plusieurs circonscriptions de la Chambre — découvrez laquelle est la vôtre avant l'entretien.",
  zipSenators: "Sénateurs des États-Unis",
  zipRepresentatives: "Représentant(s) des États-Unis",
  zipGovernor: "Gouverneur",
  zipCapital: "Capitale de l'État",
  zipVerify: "Vérifiez toujours les élus actuels avant votre entretien.",
  filterAll: "Toutes",
  progressTitle: "Votre progression",
  seen: "Vues",
  streak: "Série",
  bestStreak: "Meilleure",
  accuracy: "Précision",
  weak: "Faibles",
  mastered: "Solides",
  resetProgress: "Réinitialiser la progression",
  resetConfirm: "Effacer la progression enregistrée pour cette version ?",
  sims: "Simulations réussies",
  seniorBadge: "65/20",
  changingBannerTitle: "Réponses qui changent",
  changingBannerBody:
    "Certaines réponses dépendent des élections ou des nominations. Vérifiez toujours les élus actuels avant votre entretien.",
  changingBannerLink: "Consulter les mises à jour du test USCIS",
  changingCardNote: "Cette réponse peut changer — vérifiez sur le site de l'USCIS avant votre entretien.",
  interviewHowTitle: "Comment se déroule le véritable entretien",
  interviewHow1: "L'agent pose les questions à voix haute à partir du lot officiel.",
  interviewHow2: "Il s'arrête lorsque vous atteignez le seuil de réussite ou d'échec.",
  interviewHow3: "Réfléchissez à votre réponse, révélez-la, puis marquez honnêtement.",
  correctCount: "Correctes",
  wrongCount: "Incorrectes",
  failAt: "Échec à",
  passAt: "Réussite à",
  stoppedPass: "Entretien arrêté — vous avez atteint le score de réussite.",
  stoppedFail: "Entretien arrêté — trop de réponses incorrectes.",
  endTest: "Terminer le test",
  startSim: "Démarrer la simulation",
  nextRandom: "Suivant aléatoire",
  prev: "Précédent",
  flip: "Retourner",
  nextCard: "Suivant",
  keyboardHint: "Espace pour révéler · Y/N pour marquer · ← → pour naviguer",
  categoryMastery: "Par catégorie",
  poolSize: "Dans ce lot",
  noQuestions: "Aucune question ne correspond à ce filtre.",
  saidCorrectly: "Je l'ai dit correctement",
  gotWrong: "Je me suis trompé(e)",
  moreAnswers: "Réponses acceptables",
  speakQuestion: "Écouter la question (EN)",
  speakAnswers: "Écouter les réponses (EN)",
  speakPractice: "Dites-le à voix haute en anglais — l'entretien est oral.",
  navPractice: "Pratique",
  navLearn: "Apprendre",
  navCitizenship: "Citoyenneté américaine",
  navCivicsTest: "Test de civisme",
  navReadingTest: "Test de lecture",
  navWritingTest: "Test d'écriture",
  navTest2025: "Civisme 2025",
  navTest2008: "Civisme 2008",
  navSenior: "65/20",
  menuOpen: "Ouvrir le menu",
  menuClose: "Fermer le menu",
  navHome: "Accueil",
  themeToLight: "Passer en mode clair",
  themeToDark: "Passer en mode sombre",
  uscisUpdatesPageTitle: "Consulter les mises à jour du test",
  uscisAlertLabel: "ALERTE :",
  uscisAlertBody:
    "L'USCIS met en œuvre le test de civisme de naturalisation 2025 conformément au décret présidentiel 14161. Les étrangers qui déposent le formulaire N-400 pour demander la naturalisation avant le 20 octobre 2025 passeront le test de civisme de naturalisation 2008. Ceux qui le déposent le 20 octobre 2025 ou après passeront le test 2025. Le nouveau test 2025 est basé sur le test de civisme de naturalisation 2020, avec certaines modifications dans son administration.",
  uscisFilingColDate: "Date de dépôt du N-400",
  uscisFilingColVersion: "Version du test de civisme",
  uscisFilingBefore: "Avant le 20 octobre 2025",
  uscisFilingBeforeVersion: "Test de civisme de naturalisation 2008",
  uscisFilingAfter: "Le 20 octobre 2025 ou après",
  uscisFilingAfterVersion: "Test de civisme de naturalisation 2025",
  uscis2008Heading: "Test de civisme de naturalisation 2008",
  uscis2008Body:
    "Nous administrerons le test de civisme de naturalisation 2008 aux étrangers demandant la naturalisation qui déposent une demande N-400 avant le 20 octobre 2025.",
  uscis2025Heading: "Test de civisme de naturalisation 2025",
  uscis2025Body:
    "Nous administrerons le test de civisme de naturalisation 2025 aux étrangers demandant la naturalisation qui déposent le formulaire N-400 le 20 octobre 2025 ou après.",
  uscisResourcesHeading: "Ressources officielles de l'USCIS",
  uscisResourcesLead:
    "Documents d'étude et mises à jour des services de citoyenneté et d'immigration des États-Unis (USCIS). Nous ne faisons que renvoyer vers eux — nous n'hébergeons pas les PDF officiels.",
  uscisStudyTitle: "Étudier pour le test",
  uscisStudyBlurb: "Aperçu de l'anglais et du civisme, et documents d'étude gratuits",
  uscisUpdatesTitle: "Consulter les mises à jour du test",
  uscisUpdatesBlurb: "Élus et réponses qui changent avec les élections",
  uscis2025Title: "Test de civisme 2025",
  uscis2025Blurb: "Page de politique du test de civisme de naturalisation 2025",
  uscisExceptionsTitle: "Exceptions et aménagements",
  uscisExceptionsBlurb: "Exceptions 65/20 et pour le test d'anglais",
  uscisN400Title: "Formulaire N-400",
  uscisN400Blurb: "Demande de naturalisation",
  uscisPdf128Title: "PDF de 128 questions (2025)",
  uscisPdf128Blurb: "Liste officielle des questions-réponses en anglais",
  uscisPdf100Title: "PDF de 100 questions (2008)",
  uscisPdf100Blurb: "Liste officielle des questions-réponses en anglais",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "Site officiel des services de citoyenneté et d'immigration des États-Unis",
  learnTitle: "Guide d'étude et FAQ",
  learnLead: "Chiffres clés, faits et réponses aux questions courantes sur le test de civisme.",
  keyNumbersTitle: "Chiffres essentiels à mémoriser",
  faqTitle: "Questions fréquentes",
  guideBranchesTitle: "Les trois pouvoirs du gouvernement",
  guideAmendmentsTitle: "Amendements clés",
  guideTipsTitle: "Comment étudier",
  tip1: "Dites les réponses à voix haute — c'est un entretien oral.",
  tip2: "Pratiquez 15 à 20 minutes par jour pendant 4 à 6 semaines.",
  tip3: "Utilisez la révision intelligente pour les questions faibles, puis simulez jusqu'à réussir 3 fois de suite.",
  tip4: "Vérifiez les réponses variables sur le site de l'USCIS avant votre entretien.",
  faqQ1: "Quelle version du test dois-je passer ?",
  faqA1:
    "Si vous avez déposé le formulaire N-400 avant le 20 octobre 2025, vous passez le test 2008 (100 questions). À cette date ou après, vous passez le test 2025 (128 questions).",
  faqQ2: "Comment fonctionne la notation de l'entretien ?",
  faqA2:
    "2025 : jusqu'à 20 questions, 12 correctes requises ; l'agent s'arrête à 12 correctes ou 9 incorrectes. 2008 : jusqu'à 10 questions, 6 correctes requises (s'arrête à 6 correctes ou 5 incorrectes).",
  faqQ3: "Qu'est-ce que la considération spéciale 65/20 ?",
  faqA3:
    "Si vous avez 65 ans ou plus et êtes résident permanent depuis 20 ans ou plus, vous n'étudiez que 20 questions marquées d'une étoile. L'agent en pose 10 ; il en faut 6 correctes. Vous pouvez passer le test de civisme dans la langue de votre choix.",
  faqQ4: "Puis-je passer le test de civisme dans ma langue ?",
  faqA4:
    "Normalement, le test de civisme se déroule en anglais. Exceptions : 65/20 (langue au choix), et les exemptions d'anglais 50/20 ou 55/15 pour la partie anglaise, avec un interprète pour le civisme.",
  faqQ5: "Certaines réponses changent-elles ?",
  faqA5:
    "Oui — le président, le vice-président, le président de la Chambre, le juge en chef, vos sénateurs, votre représentant, votre gouverneur et la capitale de l'État. Utilisez notre liste d'élus actuels et la recherche par ZIP pour rester à jour.",
  federalTitle: "Élus fédéraux actuels",
  federalLead: "Ces réponses changent avec les élections ou les nominations. Étudiez les noms acceptés répertoriés par l'USCIS.",
  federalPresident: "Président",
  federalVP: "Vice-président",
  federalSpeaker: "Président de la Chambre des représentants",
  federalChief: "Juge en chef",
  federalParty: "Parti du président",
  federalAsOf: "Vérifié au",
  modeSpeak: "Parler à voix haute",
  modeSpeakHint:
    "Écoutez la question en anglais, puis répondez avec votre microphone — comme lors du véritable entretien.",
  speakStart: "Dire ma réponse",
  speakStop: "Arrêter l'écoute",
  speakHeard: "Vous avez dit",
  speakMatch: "Bien — cela correspond à une réponse acceptée.",
  speakNoMatch: "Pas encore de correspondance claire. Réponses acceptées :",
  speakUnsupported:
    "La reconnaissance vocale n'est pas disponible dans ce navigateur. Essayez Chrome, ou utilisez « Écouter les réponses » pour vous vérifier vous-même.",
  navEnglish: "Test d'anglais",
  englishTitle: "Lecture et écriture en anglais",
  englishLead:
    "Pratiquez le vocabulaire de lecture et d'écriture en anglais de l'USCIS utilisé lors de l'entretien de naturalisation.",
  readingTitle: "Lecture",
  writingTitle: "Écriture",
  readingHint: "Lisez la phrase à voix haute. Appuyez sur lecture pour l'écouter d'abord.",
  writingHint: "Écoutez la phrase, puis tapez-la. L'orthographe compte.",
  writingPrompt: "Écrivez ce que vous entendez",
  writingCheck: "Vérifier l'orthographe",
  writingCorrect: "Correct !",
  writingTryAgain: "Réessayez — phrase cible",
  nextSentence: "Phrase suivante",
  navQuestions: "Questions",
  navResources: "Ressources",
  seoQuestionsHubTitle: "Questions de civisme USCIS — pages d'étude gratuites",
  seoQuestionsHubLead:
    "Parcourez les 100 et 128 questions officielles de civisme par version, thème, 65/20 ou principaux États — avec audio gratuit.",
  seoAll128Title: "Les 128 questions de civisme USCIS (2025)",
  seoAll128Lead: "Les 128 questions officielles USCIS 2025 avec audio gratuit — sans inscription, en quelques secondes. Puis simulez l'entretien. Plus de 10 langues.",
  seoAll100Title: "Les 100 questions de civisme USCIS (2008)",
  seoAll100Lead: "Banque 2008 complète si vous avez déposé le N-400 avant le 20 octobre 2025. Audio gratuit, sans compte — simulez l'entretien quand vous voulez.",
  seoSeniorTitle: "Questions de civisme spéciales 65/20",
  seoSeniorLead: "65 ans+ et 20 ans LPR ? Étudiez seulement 20 questions étoilées (10 posées, 6 pour réussir). Audio gratuit, sans inscription — en quelques secondes. Plus de 10 langues.",
  seoStartPractice: "Ouvrir la pratique interactive",
  seoAllLandings: "Toutes les pages de questions",
  seoQuestionsCount: "questions sur cette page",
  seoBadge2025: "Test 2025 · 128 questions",
  seoBadge2008: "Test 2008 · 100 questions",
  seoTopicsHeading: "Pratiquer par thème",
  seoStatesHeading: "Pages d'étude des principaux États",
  seoStateLead:
    "Révisez la capitale et le gouverneur de votre État pour les réponses de civisme qui changent, puis pratiquez l'ensemble complet de l'entretien. Utilisez la recherche par ZIP dans la pratique pour les sénateurs et votre représentant.",
  seoStateCapital: "Capitale de l'État",
  seoStateGovernor: "Gouverneur",
  seoStatePractice: "Pratiquer le civisme pour votre entretien",
  seoReadingTitle: "Pratique de lecture en anglais — vocabulaire USCIS",
  seoReadingLead:
    "Pratiquez la lecture de phrases construites à partir du vocabulaire officiel de lecture en anglais de l'USCIS pour l'entretien de naturalisation.",
  seoWritingTitle: "Pratique d'écriture en anglais — vocabulaire USCIS",
  seoWritingLead:
    "Écoutez et écrivez des phrases en utilisant le vocabulaire officiel d'écriture en anglais de l'USCIS. L'orthographe compte le jour du test.",
  learnPostsHeading: "Guides et ressources",
  learnPostBack: "Retour à Apprendre",
  learnReadMore: "Lire la suite",
  legalBadge: "Mentions légales et confiance",
  navAbout: "À propos",
  navContact: "Contact",
  navPrivacy: "Confidentialité",
  navTerms: "Conditions",
  seoDrillsHeading: "Exercices d'étude spéciaux",
  seoDrillsLead:
    "Concentrez-vous sur les groupes les plus difficiles : dates clés, noms célèbres et élus dont les réponses changent avec les élections — audio gratuit sur chaque question.",
  seoStatesCount: "pages d'étude des États et de DC",
  questionsSearchLabel: "Rechercher des questions de civisme",
  questionsSearchSubmit: "Rechercher",
  questionsSearchHint: "Recherchez par numéro de question, mots-clés ou réponses dans les banques 2008 et 2025.",
  questionsSearchResults: "Résultats",
  exportProgress: "Exporter la progression",
  importProgress: "Importer la progression",
  exportProgressHint: "Enregistrez une sauvegarde pour transférer la progression sur un autre appareil.",
  importProgressDone: "Progression importée.",
  importProgressError: "Impossible d'importer ce fichier. Utilisez une exportation USCivics Quiz.",
  relatedStudyHeading: "Continuer a etudier",
  relatedStudyLead: "Passez entre guides, listes de questions et pratique d'entretien pour le meme sujet.",
  relatedLearn: "Guides",
  relatedQuestions: "Listes de questions",
  relatedPractice: "Pratique",
};
