import { completeDict } from "./complete";

export const fr = completeDict({
  tagline: "Préparez gratuitement le test de civisme pour la citoyenneté américaine — questions USCIS 2008 et 2025.",
  heroSupport:
    "Trouvez votre version du test, puis étudiez avec flashcards, révision intelligente, pratique orale et simulation d’entretien.",
  startEligibility: "Trouver ma version",
  practiceHeading: "Ou passez directement à la pratique",
  practice2008: "Version 2008",
  practice2008Meta: "100 questions · 10 posées · 6 pour réussir",
  practice2025: "Version 2025",
  practice2025Meta: "128 questions · 20 posées · 12 pour réussir",
  freeBadge: "Gratuit · Sans inscription",
  officialBadge: "Questions officielles USCIS",
  eligibilityTitle: "Quel test de civisme passez-vous ?",
  eligibilityLead: "Deux questions rapides pour vous orienter vers le bon ensemble.",
  q1: "Avez-vous déposé le formulaire N-400 avant le 20 octobre 2025 ?",
  q2: "Avez-vous 65 ans ou plus ET êtes-vous résident permanent depuis 20+ ans ?",
  yes: "Oui",
  no: "Non",
  notSure: "Je ne suis pas sûr(e)",
  resultSenior: "Vous êtes admissible au test simplifié 65/20 : 10 questions sur 20 marquées — 6 correctes requises.",
  result2008: "Vous passez la version 2008 : jusqu’à 10 sur 100 — 6 correctes.",
  result2025: "Vous passez la version 2025 : jusqu’à 20 sur 128 — 12 correctes.",
  startPractice: "Commencer la pratique",
  question: "Question",
  of: "sur",
  showAnswer: "Afficher la réponse",
  didYouKnow: "Avez-vous bien répondu ?",
  yourScore: "Votre score",
  passed: "Vous atteindriez le seuil de réussite de l’entretien.",
  notPassed: "Continuez — révisez et réessayez.",
  tryAgain: "Pratiquer à nouveau",
  answersLabel: "Réponses acceptées",
  langSwitch: "Langue",
  disclaimer: "Non affilié ni approuvé par l’USCIS ou le gouvernement des États-Unis. Questions à des fins d’étude uniquement.",
  modeFlashcards: "Flashcards",
  modeRandom: "Aléatoire",
  modeSmart: "Révision intelligente",
  modeSimulate: "Simuler l’entretien",
  modeBrowse: "Tout parcourir",
  browseSearch: "Rechercher des questions…",
  zipTitle: "Vos élus locaux (par ZIP)",
  zipLead: "Sénateurs, représentant, gouverneur et capitale d’État dépendent de votre lieu de résidence.",
  zipPlaceholder: "Code ZIP",
  zipSubmit: "Rechercher",
  zipSenators: "Sénateurs des É.-U.",
  zipRepresentatives: "Représentant(s)",
  zipGovernor: "Gouverneur",
  zipCapital: "Capitale de l’État",
  filterAll: "Toutes",
  progressTitle: "Votre progression",
  speakQuestion: "Écouter la question (EN)",
  speakAnswers: "Écouter les réponses (EN)",
  speakPractice: "Dites la réponse à voix haute en anglais — l’entretien est oral.",
  navPractice: "Pratiquer",
  navLearn: "Apprendre",
  learnTitle: "Guide d’étude et FAQ",
  learnLead: "Chiffres clés, faits et questions fréquentes sur le test de civisme.",
  keyNumbersTitle: "Chiffres critiques à mémoriser d’abord",
  faqTitle: "Questions fréquentes",
  guideBranchesTitle: "Les trois pouvoirs",
  guideAmendmentsTitle: "Amendements clés",
  guideTipsTitle: "Comment étudier",
  tip1: "Dites les réponses à voix haute — c’est un entretien oral.",
  tip2: "Pratiquez 15–20 minutes par jour pendant 4–6 semaines.",
  tip3: "Utilisez la révision intelligente pour les points faibles, puis simulez jusqu’à 3 réussites d’affilée.",
  tip4: "Vérifiez les réponses variables sur USCIS avant l’entretien.",
  faqQ1: "Quelle version dois-je passer ?",
  faqA1: "N-400 déposé avant le 20 octobre 2025 → 2008 (100). À partir de cette date → 2025 (128).",
  faqQ2: "Comment le score de l’entretien fonctionne-t-il ?",
  faqA2: "2025 : jusqu’à 20 questions, 12 correctes ; arrêt à 12 correctes ou 9 fausses. 2008 : jusqu’à 10, 6 correctes.",
  faqQ3: "Qu’est-ce que le 65/20 ?",
  faqA3: "65+ ans et résident permanent 20+ ans : seulement 20 questions marquées. 10 posées, 6 correctes. Civisme dans la langue de votre choix.",
  faqQ4: "Puis-je passer le civisme dans ma langue ?",
  faqA4: "En général en anglais. Exceptions : 65/20 et exemptions d’anglais 50/20 ou 55/15 avec interprète.",
  faqQ5: "Certaines réponses changent-elles ?",
  faqA5: "Oui — président, vice-président, speaker, juge en chef, sénateurs, représentant, gouverneur, capitale. Voir USCIS et ZIP.",
  saidCorrectly: "Je l’ai dit correctement",
  gotWrong: "Je me suis trompé(e)",
  changingBannerTitle: "Réponses qui changent",
  changingBannerLink: "Mises à jour du test USCIS",
});
