import { completeDict } from "./complete";

export const ht = completeDict({
  tagline: "Pratik gratis tès sivik sitwayènte Etazini — kesyon USCIS 2008 ak 2025.",
  heroSupport: "Jwenn vèsyon tès ou, epi etidye ak flashcard, revizyon entelijan, pratik oral, ak simulasyon.",
  startEligibility: "Jwenn vèsyon mwen",
  practiceHeading: "Oswa kòmanse pratike dirèkteman",
  practice2008: "Vèsyon 2008",
  practice2008Meta: "100 kesyon · 10 yo poze · 6 pou pase",
  practice2025: "Vèsyon 2025",
  practice2025Meta: "128 kesyon · 20 yo poze · 12 pou pase",
  freeBadge: "Gratis · Pa bezwen enskri",
  officialBadge: "Kesyon ofisyèl USCIS",
  eligibilityTitle: "Ki tès sivik ou pral pran?",
  eligibilityLead: "De kesyon rapid pou mennen ou nan bon seri pratik.",
  q1: "Èske ou te depoze Fòm N-400 anvan 20 oktòb 2025?",
  q2: "Èske ou gen 65 an oswa plis EPI ou se rezidan pèmanan depi 20+ ane?",
  yes: "Wi",
  no: "Non",
  notSure: "Mwen pa sèten",
  resultSenior: "Ou kalifye pou tès 65/20: 10 kesyon nan 20 ki make — bezwen 6 kòrèk.",
  result2008: "Ou pran vèsyon 2008: jiska 10 nan 100 — bezwen 6 kòrèk.",
  result2025: "Ou pran vèsyon 2025: jiska 20 nan 128 — bezwen 12 kòrèk.",
  startPractice: "Kòmanse pratike",
  question: "Kesyon",
  of: "nan",
  showAnswer: "Montre repons",
  didYouKnow: "Èske ou te reponn kòrèkteman?",
  yourScore: "Nòt ou",
  passed: "Ou ta rive nan papòt pase entèvyou a.",
  notPassed: "Kontinye — revize epi eseye ankò.",
  tryAgain: "Pratike ankò",
  answersLabel: "Repons akseptab",
  langSwitch: "Lang",
  disclaimer: "Nou pa afilye ak USCIS ni gouvènman Etazini. Kesyon yo se pou etid sèlman.",
  modeFlashcards: "Flashcards",
  modeRandom: "O aza",
  modeSmart: "Revizyon entelijan",
  modeSimulate: "Simile entèvyou",
  modeBrowse: "Gade tout",
  browseSearch: "Chèche kesyon…",
  zipTitle: "Ofisyèl lokal ou (ZIP)",
  zipLead: "Senatè, reprezantan, gouvènè ak kapital eta a depann de kote ou rete.",
  zipPlaceholder: "Kòd ZIP",
  zipSubmit: "Chèche",
  zipSenators: "Senatè Etazini",
  zipRepresentatives: "Reprezantan",
  zipGovernor: "Gouvènè",
  zipCapital: "Kapital eta a",
  filterAll: "Tout",
  progressTitle: "Pwogrè ou",
  speakQuestion: "Tande kesyon (EN)",
  speakAnswers: "Tande repons (EN)",
  speakPractice: "Di repons lan byen fò ann angle — entèvyou a se oral.",
  navPractice: "Pratike",
  navLearn: "Aprann",
  learnTitle: "Gid etid ak FAQ",
  learnLead: "Nimewo kle, enfòmasyon, ak kesyon souvan poze sou tès sivik la.",
  keyNumbersTitle: "Nimewo kritik pou memorize an premye",
  faqTitle: "Kesyon souvan poze",
  guideBranchesTitle: "Twa branch gouvènman an",
  guideAmendmentsTitle: "Amannman kle",
  guideTipsTitle: "Kijan pou etidye",
  tip1: "Di repons yo byen fò — se yon entèvyou oral.",
  tip2: "Pratike 15–20 minit chak jou pandan 4–6 semèn.",
  tip3: "Sèvi ak revizyon entelijan pou kesyon fèb, epi simile jiskaske ou pase 3 fwa youn apre lòt.",
  tip4: "Verifye repons ki chanje sou USCIS anvan entèvyou ou.",
  faqQ1: "Ki vèsyon mwen pral pran?",
  faqA1: "Si ou te depoze N-400 anvan 20 oktòb 2025 → 2008 (100). Apati jou sa a → 2025 (128).",
  faqQ2: "Kijan yo kalkile nòt entèvyou a?",
  faqA2: "2025: jiska 20, bezwen 12 kòrèk; sispann nan 12 kòrèk oswa 9 pa kòrèk. 2008: jiska 10, bezwen 6.",
  faqQ3: "Kisa 65/20 ye?",
  faqA3: "Si ou gen 65+ epi rezidan pèmanan 20+ ane: etidye sèlman 20 kesyon ak zetwal. Yo poze 10; bezwen 6. Ou ka fè sivik nan lang ou chwazi.",
  faqQ4: "Èske mwen ka fè tès sivik nan lang mwen?",
  faqA4: "Nòmalman ann angle. Eksepsyon: 65/20 ak egzanpsyon angle 50/20 oswa 55/15 ak entèprèt.",
  faqQ5: "Èske gen repons ki chanje?",
  faqA5: "Wi — prezidan, vis-prezidan, speaker, jij an chèf, senatè ou, reprezantan, gouvènè, kapital. Tcheke USCIS ak ZIP.",
  saidCorrectly: "Mwen te di li kòrèkteman",
  gotWrong: "Mwen te fo",
  changingBannerTitle: "Repons ki chanje",
  changingBannerLink: "Mizajou tès USCIS",
});
