import type { Dictionary } from "./en";

export const ht: Dictionary = {
  brand: "USCivics Quiz",
  logoSubtitle: "Pratik sivik",
  siteName: "USCivics Quiz",
  homeMetaTitle:
    "USCivics Quiz (uscivics-quiz) — Pratik sivik USCIS gratis",
  homeMetaDescription:
    "USCivics Quiz sou uscivics-quiz.com — pratik sivik USCIS gratis. Kesyon ofisyèl 2008 ak 2025, odyo, flashcards, simulasyon entèvyou. Pa gen enskripsyon.",
  tagline:
    "USCivics Quiz — pratik sivik USCIS gratis. Konnen dat depoze N-400 ou (2008 vs 2025), epi kòmanse an kèk segonn. Pa gen enskripsyon.",
  heroSupport:
    "Pratike sou uscivics-quiz.com ak bank kesyon ofisyèl la — odyo, flashcards, ak simulasyon entèvyou nan plis pase 10 lang.",
  startEligibility: "Jwenn vèsyon mwen",
  practiceHeading: "Kòmanse pratike",
  practiceCta: "Louvri pratik la",
  practice2008: "Pratik sitwayèn 2008 — kesyon ofisyèl",
  practice2008Meta: "100 kesyon · 10 yo poze · 6 pou pase",
  practice2025: "Pratik sitwayèn 2025 — kesyon ofisyèl",
  practice2025Meta: "128 kesyon · 20 yo poze · 12 pou pase",
  freeBadge: "Gratis · Pa enskripsyon · Segonn",
  bilingualBadge: "Plis pase 10 lang",
  officialBadge: "Kesyon ofisyèl USCIS",
  practiceHubLead: "Pa gen enskripsyon. Bank USCIS ofisyèl ak odyo ak simulasyon entèvyou — kòmanse an kèk segonn.",
  practiceMetaTitleSuffix: "Simulasyon entèvyou USCIS gratis",
  diffNoSignup: "Gratis · Pa enskripsyon · Kòmanse an kèk segonn",
  diffRightBank: "Konnen ki bank pou etidye: dat N-400 (2008 vs 2025) oswa 65/20",
  diffOfficialPractice: "Kesyon USCIS ofisyèl · Odyo · Simulasyon entèvyou",
  diffLanguages: "Pratike nan plis pase 10 lang — pa sèlman angle",
  diffStripAria: "Poukisa pratike isit la",
  startInSecondsCta: "Kòmanse pratike an kèk segonn",
  linkN400Filing: "Dat depo N-400 (2008 vs 2025)",
  link6520: "Konsiderasyon espesyal 65/20",
  linkHowMany: "Konbyen kesyon yo poze",
  linkPassScore: "Ki nòt pou pase",
  link2025Changes: "Chanjman sitwayèn 2025",
  linkPractice2025Senior: "2025 · pratik 65/20",
  linkPractice2008Senior: "2008 · pratik 65/20",
  linkWhichCivicsTest: "Ki tès sitwayèn?",
  linkFailTest: "Si ou echwe tès la",
  linkStudyPlan: "Plan 30 jou",
  linkReadingWriting: "Angle: lekti ak ekriti",
  eligibilityTitle: "Ki tès sivik ou pral pran?",
  eligibilityLead: "De kesyon rapid. N ap mennen ou nan bon bank anvan ou etidye — 2008, 2025 oswa 65/20.",
  q1: "Èske ou te depoze Fòm N-400 anvan 20 oktòb 2025?",
  q2: "Èske ou gen 65 an oswa plis EPI ou se rezidan pèmanan depi 20+ ane?",
  yes: "Wi",
  no: "Non",
  notSure: "Mwen pa sèten",
  resultSenior:
    "Ou kalifye pou tès senplifye 65/20 la: 10 kesyon nan yon seri 20 ki make — bezwen 6 kòrèk.",
  result2008: "Ou pran vèsyon 2008: jiska 10 nan 100 kesyon — bezwen 6 kòrèk.",
  result2025: "Ou pran vèsyon 2025: jiska 20 nan 128 kesyon — bezwen 12 kòrèk.",
  startPractice: "Kòmanse pratike",
  question: "Kesyon",
  of: "nan",
  showAnswer: "Devwale repons",
  didYouKnow: "Èske ou te reponn kòrèkteman?",
  next: "Kesyon annapre",
  finish: "Fini",
  yourScore: "Nòt ou",
  passed: "Ou ta rive nan papòt pase entèvyou a.",
  notPassed: "Kontinye — revize epi eseye yon lòt fwa.",
  tryAgain: "Pratike ankò",
  passNeed: "Bezwen",
  correct: "kòrèk",
  answersLabel: "Repons akseptab",
  langSwitch: "Lang",
  backHome: "Akèy",
  disclaimer:
    "Nou pa afilye ak, ni apwouve pa, USCIS oswa gouvènman Etazini an. Kesyon pratik yo se pou etid sèlman.",
  stepOf: "Etap",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Etidye an lòd — vire, make, kontinye",
  modeRandom: "O aza",
  modeRandomHint: "Melanje tankou vrè pòl la",
  modeSmart: "Revizyon entelijan",
  modeSmartHint: "Bay priyorite a kesyon fèb ak kesyon ou poko wè",
  modeSimulate: "Simile entèvyou",
  modeSimulateHint: "Sispann lè ou pase oswa echwe — tankou USCIS",
  modeBrowse: "Gade tout",
  modeBrowseHint: "Chèche nan tout pòl la epi ale nan nenpòt kesyon",
  browseSearch: "Chèche kesyon…",
  browseEmpty: "Pa gen kesyon ki koresponn ak rechèch ou.",
  browseStudy: "Etidye kat sa a",
  browseSeen: "Wè",
  browseWeak: "Bezwen travay",
  browseStrong: "Fò",
  browseNew: "Nouvo",
  zipTitle: "Ofisyèl lokal ou (dapre ZIP)",
  zipLead:
    "Repons pou senatè, reprezantan, gouvènè, ak kapital eta ou depann de kote ou rete. Antre ZIP ou pou etidye bon non yo.",
  zipPlaceholder: "Kòd ZIP",
  zipSubmit: "Chèche",
  zipLoading: "N ap chèche…",
  zipInvalid: "Antre yon kòd ZIP Ameriken ki gen 5 chif ki valab.",
  zipError: "Pa t kapab chèche ZIP sa a. Eseye ankò.",
  zipAmbiguous: "ZIP sa a kouvri plis pase yon distri Chanm Reprezantan — aprann kilès ki pa w anvan entèvyou a.",
  zipSenators: "Senatè Etazini",
  zipRepresentatives: "Reprezantan Etazini",
  zipGovernor: "Gouvènè",
  zipCapital: "Kapital eta a",
  zipVerify: "Toujou verifye ofisyèl aktyèl yo anvan entèvyou ou.",
  filterAll: "Tout",
  progressTitle: "Pwogrè ou",
  seen: "Wè",
  streak: "Suit",
  bestStreak: "Pi bon",
  accuracy: "Presizyon",
  weak: "Fèb",
  mastered: "Fò",
  resetProgress: "Reyajiste pwogrè",
  resetConfirm: "Efase pwogrè ki sove pou vèsyon sa a?",
  sims: "Simulasyon reyisi",
  seniorBadge: "65/20",
  changingBannerTitle: "Repons ki chanje",
  changingBannerBody:
    "Gen kèk repons ki depann de eleksyon oswa nominasyon. Toujou verifye ofisyèl aktyèl yo anvan entèvyou ou.",
  changingBannerLink: "Louvri mizajou tès yo",
  changingCardNote: "Repons sa a ka chanje — verifye sou USCIS anvan entèvyou ou.",
  interviewHowTitle: "Kijan vrè entèvyou a fonksyone",
  interviewHow1: "Ofisye a poze kesyon awotvwa nan pòl ofisyèl la.",
  interviewHow2: "Yo sispann lè w pase oswa echwe papòt la.",
  interviewHow3: "Reflechi sou repons ou, devwale l, epi make onètman.",
  correctCount: "Kòrèk",
  wrongCount: "Enkòrèk",
  failAt: "Echwe nan",
  passAt: "Pase nan",
  stoppedPass: "Entèvyou a sispann — ou rive nan nòt pou pase.",
  stoppedFail: "Entèvyou a sispann — twòp repons ki enkòrèk.",
  endTest: "Fini tès la",
  startSim: "Kòmanse simulasyon",
  nextRandom: "Pwochen o aza",
  prev: "Anvan",
  flip: "Vire",
  nextCard: "Annapre",
  keyboardHint: "Espas pou devwale · Y/N pou make · ← → pou navige",
  categoryMastery: "Pa kategori",
  poolSize: "Nan pòl sa a",
  noQuestions: "Pa gen kesyon ki koresponn ak filt sa a.",
  saidCorrectly: "Mwen te di li kòrèkteman",
  gotWrong: "Mwen te twonpe",
  moreAnswers: "Repons akseptab",
  speakQuestion: "Tande kesyon (EN)",
  speakAnswers: "Tande repons (EN)",
  speakPractice: "Di li byen fò ann angle — entèvyou a se oral.",
  navPractice: "Pratik",
  navLearn: "Gid",
  navCitizenship: "Vèsyon mwen",
  navCivicsTest: "Tès Sivik",
  navReadingTest: "Tès Lekti",
  navWritingTest: "Tès Ekriti",
  navTest2025: "Sivik 2025",
  navTest2008: "Sivik 2008",
  navSenior: "65/20",
  menuOpen: "Louvri meni",
  menuClose: "Fèmen meni",
  navHome: "Akèy",
  themeToLight: "Chanje pou mòd klè",
  themeToDark: "Chanje pou mòd fonse",
  uscisUpdatesPageTitle: "Tcheke Mizajou Tès la",
  uscisAlertLabel: "ALÈT:",
  uscisAlertBody:
    "USCIS ap aplike tès sivik natiralizasyon 2025 la pou l aliyen ak Dekrè Egzekitif 14161. Etranje ki depoze Fòm N-400 pou aplike pou natiralizasyon anvan 20 oktòb 2025 pral pran tès sivik natiralizasyon 2008 la. Etranje ki depoze Fòm N-400 pou aplike pou natiralizasyon nan dat 20 oktòb 2025 oswa apre pral pran tès 2025 la. Nouvo tès 2025 la baze sou tès sivik natiralizasyon 2020 la, ak kèk modifikasyon nan fason yo administre tès la.",
  uscisFilingColDate: "Dat Depo N-400",
  uscisFilingColVersion: "Vèsyon Tès Sivik la",
  uscisFilingBefore: "Anvan 20 oktòb 2025",
  uscisFilingBeforeVersion: "Tès Sivik Natiralizasyon 2008",
  uscisFilingAfter: "Nan oswa Apre 20 oktòb 2025",
  uscisFilingAfterVersion: "Tès Sivik Natiralizasyon 2025",
  uscis2008Heading: "Tès Sivik Natiralizasyon 2008",
  uscis2008Body:
    "Nou pral administre tès sivik natiralizasyon 2008 la bay etranje k ap aplike pou natiralizasyon ki depoze yon aplikasyon Fòm N-400 anvan 20 oktòb 2025.",
  uscis2025Heading: "Tès Sivik Natiralizasyon 2025",
  uscis2025Body:
    "Nou pral administre tès sivik natiralizasyon 2025 la bay etranje k ap aplike pou natiralizasyon ki depoze Fòm N-400 nan oswa apre 20 oktòb 2025.",
  uscisResourcesHeading: "Resous ofisyèl USCIS",
  uscisResourcesLead:
    "Materyèl etid ak mizajou nan U.S. Citizenship and Immigration Services. Nou fè lyen ale deyò — nou pa ebèje PDF ofisyèl yo.",
  uscisStudyTitle: "Etidye pou Tès la",
  uscisStudyBlurb: "Apèsi angle + sivik ak materyèl etid gratis",
  uscisUpdatesTitle: "Tcheke Mizajou Tès la",
  uscisUpdatesBlurb: "Ofisyèl ak repons ki chanje ak eleksyon",
  uscis2025Title: "Tès Sivik 2025",
  uscis2025Blurb: "Paj politik pou tès sivik natiralizasyon 2025 la",
  uscisExceptionsTitle: "Eksepsyon ak akomodasyon",
  uscisExceptionsBlurb: "Eksepsyon 65/20 ak tès angle",
  uscisN400Title: "Fòm N-400",
  uscisN400Blurb: "Aplikasyon pou Natiralizasyon",
  uscisPdf128Title: "PDF 128 kesyon (2025)",
  uscisPdf128Blurb: "Lis ofisyèl Kesyon-Repons an Angle",
  uscisPdf100Title: "PDF 100 kesyon (2008)",
  uscisPdf100Blurb: "Lis ofisyèl Kesyon-Repons an Angle",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "Sit ofisyèl U.S. Citizenship and Immigration Services",
  learnTitle: "Gid Etid ak FAQ",
  learnLead: "Nimewo kle, enfòmasyon, ak repons pou kesyon komen sou tès sivik la.",
  keyNumbersTitle: "Nimewo enpòtan pou memorize",
  faqTitle: "Kesyon Souvan Poze",
  guideBranchesTitle: "Twa Branch Gouvènman an",
  guideAmendmentsTitle: "Amannman Kle",
  guideTipsTitle: "Kijan pou Etidye",
  tip1: "Di repons yo byen fò — se yon entèvyou oral.",
  tip2: "Pratike 15–20 minit chak jou pandan 4–6 semèn.",
  tip3: "Sèvi ak revizyon entelijan pou kesyon fèb yo, epi simile jiskaske ou pase 3 fwa youn apre lòt.",
  tip4: "Verifye repons ki chanje sou USCIS anvan entèvyou ou.",
  faqQ1: "Ki vèsyon tès mwen pral pran?",
  faqA1:
    "Si ou te depoze Fòm N-400 anvan 20 oktòb 2025, ou pran tès 2008 la (100 kesyon). Nan dat sa a oswa apre, ou pran tès 2025 la (128 kesyon).",
  faqQ2: "Kijan yo kalkile nòt entèvyou a?",
  faqA2:
    "2025: jiska 20 kesyon, bezwen 12 kòrèk; ofisye a sispann nan 12 kòrèk oswa 9 enkòrèk. 2008: jiska 10 kesyon, bezwen 6 kòrèk (sispann nan 6 kòrèk oswa 5 enkòrèk).",
  faqQ3: "Kisa konsiderasyon espesyal 65/20 la ye?",
  faqA3:
    "Si ou gen 65+ an epi ou se rezidan pèmanan depi 20+ ane, ou etidye sèlman 20 kesyon ak zetwal. Ofisye a poze 10; ou bezwen 6 kòrèk. Ou ka pran tès sivik la nan lang ou chwazi.",
  faqQ4: "Èske mwen ka pran tès sivik la nan lang mwen?",
  faqA4:
    "Nòmalman tès sivik la an angle. Eksepsyon: 65/20 (lang ou chwazi), ak egzanpsyon angle 50/20 oswa 55/15 pou pati angle a, ak yon entèprèt pou sivik la.",
  faqQ5: "Èske gen kèk repons ki chanje?",
  faqA5:
    "Wi — prezidan, vis-prezidan, speaker, jij an chèf, senatè ou, reprezantan, gouvènè, ak kapital eta a. Sèvi ak lis ofisyèl aktyèl nou an ak rechèch ZIP pou rete ajou.",
  federalTitle: "Ofisyèl Federal Aktyèl yo",
  federalLead: "Repons sa yo chanje ak eleksyon oswa nominasyon. Etidye non aksepte USCIS make yo.",
  federalPresident: "Prezidan",
  federalVP: "Vis-Prezidan",
  federalSpeaker: "Speaker Chanm Reprezantan an",
  federalChief: "Jij an Chèf",
  federalParty: "Pati Prezidan an",
  federalAsOf: "Verifye depi",
  modeSpeak: "Pale awotvwa",
  modeSpeakHint: "Tande kesyon an angle a, epi reponn ak mikwofòn ou — tankou vrè entèvyou a.",
  speakStart: "Pale repons mwen",
  speakStop: "Sispann koute",
  speakHeard: "Ou te di",
  speakMatch: "Byen — sa koresponn ak yon repons ki aksepte.",
  speakNoMatch: "Poko gen yon konkòdans klè. Repons aksepte:",
  speakUnsupported:
    "Rekonesans vwa pa disponib nan navigatè sa a. Eseye Chrome, oswa itilize Tande repons pou tcheke tèt ou.",
  navEnglish: "Tès Angle",
  englishTitle: "Lekti ak Ekriti Angle",
  englishLead: "Pratike vokabilè lekti ak ekriti angle USCIS yo itilize nan entèvyou natiralizasyon an.",
  readingTitle: "Lekti",
  writingTitle: "Ekriti",
  readingHint: "Li fraz la byen fò. Tape play pou tande l anvan.",
  writingHint: "Koute fraz la, epi tape li. Otograf konte.",
  writingPrompt: "Ekri sa ou tande",
  writingCheck: "Tcheke otograf",
  writingCorrect: "Kòrèk!",
  writingTryAgain: "Eseye ankò — fraz sib la",
  nextSentence: "Fraz annapre",
  navQuestions: "Kesyon",
  navResources: "Resous",
  seoQuestionsHubTitle: "Kesyon sivik USCIS — paj etid gratis",
  seoQuestionsHubLead:
    "Gade tout 100 ak 128 kesyon sivik ofisyèl yo pa vèsyon, sijè, 65/20, oswa pi gwo eta yo — ak odyo gratis.",
  seoAll128Title: "Tout 128 Kesyon Sivik USCIS (2025)",
  seoAll128Lead: "Tout 128 kesyon ofisyèl USCIS 2025 ak odyo gratis — pa enskripsyon, kèk segonn. Apre sa simulasyon. Plis pase 10 lang.",
  seoAll100Title: "Tout 100 Kesyon Sivik USCIS (2008)",
  seoAll100Lead: "Bank 2008 konplè si ou te depoze N-400 anvan 20 oktòb 2025. Odyo gratis, pa kont — simule lè ou pare.",
  seoSeniorTitle: "Kesyon Sivik Espesyal 65/20",
  seoSeniorLead: "65+ ak 20 ane LPR? Etidye sèlman 20 kesyon zetwal (yo poze 10, ou bezwen 6). Odyo gratis, pa enskripsyon — kèk segonn. Plis pase 10 lang.",
  seoStartPractice: "Louvri pratik entèraktif la",
  seoAllLandings: "Tout paj kesyon yo",
  seoQuestionsCount: "kesyon sou paj sa a",
  seoBadge2025: "Tès 2025 · 128 kesyon",
  seoBadge2008: "Tès 2008 · 100 kesyon",
  seoTopicsHeading: "Pratike pa Sijè",
  seoStatesHeading: "Paj Etid pou Pi Gwo Eta yo",
  seoStateLead:
    "Revize kapital eta w ak gouvènè w pou repons sivik ki chanje, epi pratike tout seri entèvyou a. Sèvi ak rechèch ZIP nan pratik pou senatè ak reprezantan ou.",
  seoStateCapital: "Kapital eta a",
  seoStateGovernor: "Gouvènè",
  seoStatePractice: "Pratike sivik pou entèvyou ou",
  seoReadingTitle: "Pratik Lekti Angle — vokabilè USCIS",
  seoReadingLead:
    "Pratike li fraz ki fèt ak vokabilè lekti angle ofisyèl USCIS pou entèvyou natiralizasyon an.",
  seoWritingTitle: "Pratik Ekriti Angle — vokabilè USCIS",
  seoWritingLead:
    "Koute epi ekri fraz ak vokabilè ekriti angle ofisyèl USCIS. Otograf konte jou tès la.",
  learnPostsHeading: "Gid ak Resous",
  learnPostBack: "Retounen nan Aprann",
  learnReadMore: "Li plis",
  legalBadge: "Legal ak Konfyans",
  navAbout: "Konsènan",
  navContact: "Kontak",
  navPrivacy: "Konfidansyalite",
  navTerms: "Kondisyon",
  seoDrillsHeading: "Egzèsis Etid Espesyal",
  seoDrillsLead:
    "Konsantre sou gwoup ki pi difisil yo: dat kle, non selèb, ak ofisyèl ki gen repons ki chanje ak eleksyon — odyo gratis sou chak kesyon.",
  seoStatesCount: "paj etid eta ak DC",
  questionsSearchLabel: "Chèche kesyon sivik",
  questionsSearchSubmit: "Chèche",
  questionsSearchHint: "Chèche pa nimewo kesyon, mo kle, oswa repons nan bank 2008 ak 2025 yo.",
  questionsSearchResults: "Rezilta",
  exportProgress: "Ekspote pwogre",
  importProgress: "Enpote pwogre",
  exportProgressHint: "Sove yon fichye backup pou deplase pwogre a sou yon lòt aparèy.",
  importProgressDone: "Pwogre enpote.",
  importProgressError: "Pa t kapab enpote fichye sa a. Itilize yon ekspòtasyon USCivics Quiz.",
  relatedStudyHeading: "Kontinye etidye",
  relatedStudyLead: "Sote ant gid, lis kesyon, ak pratik entèvyou pou menm sijè a.",
  relatedLearn: "Gid",
  relatedQuestions: "Lis kesyon",
  relatedPractice: "Pratik",
  premiumWaitlistTitle: "Pwogrè sou plizyè aparèy (byento)",
  premiumWaitlistLead: "Pratik prensipal la rete gratis pou toutan. Antre nan waitlist pou sync nwaj opsyonèl — pa gen paywall sou bank kesyon yo.",
  premiumWaitlistCta: "Fè m konnen lè premium soti",
  premiumWaitlistDone: "Ou nan waitlist sou aparèy sa a.",
  navUpdates: "Mizajou",
  govBannerLead: "Pratik sivik endepandan — se pa yon sit wèb gouvènman Etazini.",
  govBannerHow: "Men kijan ou konnen",
  govBannerSecureTitle: "Verifye anvan jou entèvyou a",
  govBannerOfficialTitle: "Sit ofisyèl yo itilize .gov",
  govBannerBadge: "Pa .gov",
  govBannerOfficial: "USCIS ak lòt sit gouvènman Etazini fini ak .gov. Sit sa a se yon zouti etid gratis endepandan — san afilyasyon ni andòsman USCIS.",
  govBannerSecure: "Toujou konfime repons ki chanje ak règ tès yo sou uscis.gov anvan entèvyou ou.",
  updatesHubTitle: "Mizajou tès sivik",
  updatesHubLead: "Dat depoze (2008 vs 2025), ofisyèl ki chanje, ak rechèch ZIP — yon changelog etwat pou egzamen an, pa yon fil nouvèl.",
  updatesPolicyHeading: "Nòt politik ak egzamen",
  updatesLiveHeading: "Ofisyèl an dirèk ak repons lokal",
  updatesLiveBadge: "An dirèk",
  updatesCachedBadge: "Nan cache",
  updatesVerifyNote: "Konfime non yo nan semèn entèvyou a. Eleksyon ak nonmen ka chanje repons akseptab.",
  homeLiveHeading: "Ofisyèl aktyèl",
  homeLiveLead: "Non federal an dirèk pou jou entèvyou a — plis rechèch ZIP pou senatè, reprezantan, gouvènè ak kapital.",
  homeLiveCta: "Louvri mizajou tès yo",
  linkUpdates: "Mizajou tès sivik",
  affiliateHeading: "Preparasyon ki gen rapò (opsyonèl)",
  affiliateLead: "Pratik prensipal sou sit sa a rete gratis. Gen moun ki itilize liv oswa flashcards tou — lyen anba yo ka ban nou yon ti komisyon.",
  affiliateDisclosure: "Kòm Amazon Associate nou ka touche lajan nan acha ki kalifye. Nou pa afilye ak USCIS. Toujou verifye règ yo sou uscis.gov.",
  affiliateItemFlashcards: "Flashcards sivik",
  affiliateItemFlashcardsBlurb: "Kat fizik pou pratike pale san ekran.",
  affiliateItemGuide: "Gid etid natiralizasyon",
  affiliateItemGuideBlurb: "Rezime enprime pou asosye ak bank ofisyèl USCIS isit la.",
  affiliateItemEnglish: "Angle pou sitwayènte",
  affiliateItemEnglishBlurb: "Sipò lekti/ekri anplis — kontinye itilize egzèsis fraz gratis nou yo.",
};
