import type { Dictionary } from "./en";

export const ko: Dictionary = {
  brand: "USCivics Quiz",
  logoSubtitle: "시빅스 연습",
  siteName: "USCivics Quiz",
  tagline: "무료 USCIS 시민권 연습 — N-400 제출일(2008 vs 2025)을 확인한 뒤 몇 초 만에 시작. 가입 불필요.",
  heroSupport: "공식 문제은행 + 오디오, 플래시카드, 면접 시뮬레이션 — 10개 이상 언어.",
  startEligibility: "내 시험 버전 찾기",
  practiceHeading: "연습 시작하기",
  practiceCta: "연습 열기",
  practice2008: "2008 시민권 연습 — 공식 문제",
  practice2008Meta: "100문항 · 10문항 출제 · 6개 정답 필요",
  practice2025: "2025 시민권 연습 — 공식 문제",
  practice2025Meta: "128문항 · 20문항 출제 · 12개 정답 필요",
  freeBadge: "무료 · 가입 없음 · 즉시",
  bilingualBadge: "10개 이상 언어",
  officialBadge: "공식 USCIS 문제",
  practiceHubLead: "가입 불필요. 공식 USCIS 은행 + 오디오·면접 시뮬레이션 — 몇 초 만에 시작.",
  practiceMetaTitleSuffix: "무료 USCIS 면접 시뮬레이션",
  diffNoSignup: "무료 · 가입 없음 · 몇 초 만에 시작",
  diffRightBank: "어떤 은행을 공부할지: N-400 제출일(2008 vs 2025) 또는 65/20",
  diffOfficialPractice: "공식 USCIS 문제 · 오디오 · 면접 시뮬레이션",
  diffLanguages: "10개 이상 언어로 연습 — 영어만이 아님",
  diffStripAria: "여기서 연습하는 이유",
  startInSecondsCta: "몇 초 만에 연습 시작",
  linkN400Filing: "N-400 제출일 (2008 vs 2025)",
  link6520: "65/20 특별 고려",
  linkHowMany: "몇 문항을 묻는지",
  linkPassScore: "합격 점수",
  link2025Changes: "2025 시민권 변경",
  linkPractice2025Senior: "2025 · 65/20 연습",
  linkPractice2008Senior: "2008 · 65/20 연습",
  linkWhichCivicsTest: "어떤 시험을 보나요?",
  linkFailTest: "시험에 떨어지면",
  linkStudyPlan: "30일 학습 계획",
  linkReadingWriting: "영어 읽기·쓰기",
  eligibilityTitle: "어떤 시빅스 시험을 보나요?",
  eligibilityLead: "빠른 질문 두 개. 공부 전에 맞는 문제은행으로 안내합니다 — 2008, 2025 또는 65/20.",
  q1: "2025년 10월 20일 이전에 N-400 양식을 제출했나요?",
  q2: "만 65세 이상이며 영주권자로 20년 이상 거주했나요?",
  yes: "예",
  no: "아니요",
  notSure: "잘 모르겠어요",
  resultSenior: "65/20 간소화 시험 대상입니다: 표시된 20문항 중 10문항 출제 — 6개 정답 필요.",
  result2008: "2008 버전을 봅니다: 최대 100문항 중 10문항 — 6개 정답 필요.",
  result2025: "2025 버전을 봅니다: 최대 128문항 중 20문항 — 12개 정답 필요.",
  startPractice: "연습 시작",
  question: "문제",
  of: "/",
  showAnswer: "정답 공개",
  didYouKnow: "맞게 말했나요?",
  next: "다음 문제",
  finish: "완료",
  yourScore: "내 점수",
  passed: "면접 합격 기준에 도달했습니다.",
  notPassed: "계속하세요 — 복습 후 다시 도전하세요.",
  tryAgain: "다시 연습하기",
  passNeed: "필요",
  correct: "정답",
  answersLabel: "인정 답변",
  langSwitch: "언어",
  backHome: "홈",
  disclaimer:
    "USCIS 또는 미국 정부와 제휴하거나 승인받지 않았습니다. 연습 문제는 학습 목적으로만 제공됩니다.",
  stepOf: "단계",
  modeFlashcards: "플래시카드",
  modeFlashcardsHint: "순서대로 학습 — 뒤집고, 표시하고, 다음으로",
  modeRandom: "랜덤",
  modeRandomHint: "실제 문제 풀처럼 무작위로 섞기",
  modeSmart: "스마트 복습",
  modeSmartHint: "약한 문제와 안 본 문제를 우선 학습",
  modeSimulate: "면접 시뮬레이션",
  modeSimulateHint: "합격 또는 불합격 시 종료 — USCIS 방식과 동일",
  modeBrowse: "전체 보기",
  modeBrowseHint: "전체 문제 풀을 검색하고 원하는 문제로 이동",
  browseSearch: "문제 검색…",
  browseEmpty: "검색 결과와 일치하는 문제가 없습니다.",
  browseStudy: "이 카드 학습하기",
  browseSeen: "본 문제",
  browseWeak: "보완 필요",
  browseStrong: "능숙",
  browseNew: "신규",
  zipTitle: "내 지역 공직자 (ZIP 코드 기준)",
  zipLead:
    "상원의원, 하원의원, 주지사, 주도에 대한 답은 거주 지역에 따라 다릅니다. ZIP 코드를 입력해 정확한 이름을 학습하세요.",
  zipPlaceholder: "ZIP 코드",
  zipSubmit: "조회",
  zipLoading: "조회 중…",
  zipInvalid: "유효한 5자리 미국 ZIP 코드를 입력하세요.",
  zipError: "이 ZIP 코드를 조회할 수 없습니다. 다시 시도하세요.",
  zipAmbiguous: "이 ZIP 코드는 여러 하원 선거구를 포함합니다 — 면접 전에 본인의 선거구를 확인하세요.",
  zipSenators: "미국 상원의원",
  zipRepresentatives: "미국 하원의원",
  zipGovernor: "주지사",
  zipCapital: "주도",
  zipVerify: "면접 전 항상 현직 공직자를 확인하세요.",
  filterAll: "전체",
  progressTitle: "학습 진행 상황",
  seen: "본 문제",
  streak: "연속 정답",
  bestStreak: "최고 기록",
  accuracy: "정확도",
  weak: "약함",
  mastered: "능숙",
  resetProgress: "진행 상황 초기화",
  resetConfirm: "이 버전의 저장된 진행 상황을 지우시겠습니까?",
  sims: "시뮬레이션 합격",
  seniorBadge: "65/20",
  changingBannerTitle: "변동하는 답변",
  changingBannerBody:
    "일부 답변은 선거나 임명에 따라 달라집니다. 면접 전 항상 현직 공직자를 확인하세요.",
  changingBannerLink: "USCIS 시험 업데이트 확인",
  changingCardNote: "이 답변은 변경될 수 있습니다 — 면접 전 USCIS에서 확인하세요.",
  interviewHowTitle: "실제 면접 진행 방식",
  interviewHow1: "면접관이 공식 문제 풀에서 소리 내어 질문합니다.",
  interviewHow2: "합격 또는 불합격 기준에 도달하면 멈춥니다.",
  interviewHow3: "답을 생각한 뒤 공개하고 솔직하게 표시하세요.",
  correctCount: "정답",
  wrongCount: "오답",
  failAt: "불합격 기준",
  passAt: "합격 기준",
  stoppedPass: "면접 종료 — 합격 점수에 도달했습니다.",
  stoppedFail: "면접 종료 — 오답이 너무 많습니다.",
  endTest: "시험 종료",
  startSim: "시뮬레이션 시작",
  nextRandom: "다음 무작위 문제",
  prev: "이전",
  flip: "뒤집기",
  nextCard: "다음",
  keyboardHint: "스페이스 정답 공개 · Y/N 표시 · ← → 이동",
  categoryMastery: "카테고리별",
  poolSize: "이 문제 풀",
  noQuestions: "이 필터에 맞는 문제가 없습니다.",
  saidCorrectly: "맞게 말했어요",
  gotWrong: "틀렸어요",
  moreAnswers: "인정되는 답변",
  speakQuestion: "문제 듣기 (EN)",
  speakAnswers: "답변 듣기 (EN)",
  speakPractice: "영어로 크게 소리 내어 말하세요 — 면접은 구술로 진행됩니다.",
  navPractice: "연습",
  navLearn: "학습",
  navCitizenship: "미국 시민권",
  navCivicsTest: "시빅스 시험",
  navReadingTest: "읽기 시험",
  navWritingTest: "쓰기 시험",
  navTest2025: "시빅스 2025",
  navTest2008: "시빅스 2008",
  navSenior: "65/20",
  menuOpen: "메뉴 열기",
  menuClose: "메뉴 닫기",
  navHome: "홈",
  themeToLight: "라이트 모드로 전환",
  themeToDark: "다크 모드로 전환",
  uscisUpdatesPageTitle: "시험 업데이트 확인",
  uscisAlertLabel: "알림:",
  uscisAlertBody:
    "USCIS는 행정명령 14161호에 맞춰 2025년 귀화 시빅스 시험을 시행하고 있습니다. 2025년 10월 20일 이전에 귀화를 신청하며 N-400 양식을 제출한 외국인은 2008년 귀화 시빅스 시험을 봅니다. 2025년 10월 20일 또는 그 이후에 N-400 양식을 제출하는 외국인은 2025년 시험을 봅니다. 새로운 2025년 시험은 2020년 귀화 시빅스 시험을 기반으로 하며, 시험 시행 방식에 일부 변경 사항이 있습니다.",
  uscisFilingColDate: "N-400 제출일",
  uscisFilingColVersion: "시빅스 시험 버전",
  uscisFilingBefore: "2025년 10월 20일 이전",
  uscisFilingBeforeVersion: "2008년 귀화 시빅스 시험",
  uscisFilingAfter: "2025년 10월 20일 또는 그 이후",
  uscisFilingAfterVersion: "2025년 귀화 시빅스 시험",
  uscis2008Heading: "2008년 귀화 시빅스 시험",
  uscis2008Body:
    "2025년 10월 20일 이전에 N-400 귀화 신청서를 제출하는 귀화 신청 외국인에게는 2008년 귀화 시빅스 시험을 시행합니다.",
  uscis2025Heading: "2025년 귀화 시빅스 시험",
  uscis2025Body:
    "2025년 10월 20일 또는 그 이후에 N-400 양식을 제출하는 귀화 신청 외국인에게는 2025년 귀화 시빅스 시험을 시행합니다.",
  uscisResourcesHeading: "공식 USCIS 자료",
  uscisResourcesLead:
    "미 시민권 이민국(USCIS)의 학습 자료 및 업데이트입니다. 저희는 링크만 제공하며 공식 PDF를 직접 호스팅하지 않습니다.",
  uscisStudyTitle: "시험 학습하기",
  uscisStudyBlurb: "영어 + 시빅스 개요 및 무료 학습 자료",
  uscisUpdatesTitle: "시험 업데이트 확인",
  uscisUpdatesBlurb: "선거에 따라 바뀌는 공직자 및 답변",
  uscis2025Title: "2025 시빅스 시험",
  uscis2025Blurb: "2025년 귀화 시빅스 시험 정책 페이지",
  uscisExceptionsTitle: "예외 및 편의 제공",
  uscisExceptionsBlurb: "65/20 및 영어 시험 예외",
  uscisN400Title: "N-400 양식",
  uscisN400Blurb: "귀화 신청서",
  uscisPdf128Title: "128문항 PDF (2025)",
  uscisPdf128Blurb: "공식 영어 문답 목록",
  uscisPdf100Title: "100문항 PDF (2008)",
  uscisPdf100Blurb: "공식 영어 문답 목록",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "미 시민권 이민국 공식 사이트",
  learnTitle: "학습 가이드 및 FAQ",
  learnLead: "시빅스 시험에 관한 핵심 숫자, 정보, 자주 묻는 질문에 대한 답변입니다.",
  keyNumbersTitle: "꼭 외워야 할 핵심 숫자",
  faqTitle: "자주 묻는 질문",
  guideBranchesTitle: "정부의 삼권",
  guideAmendmentsTitle: "주요 수정 조항",
  guideTipsTitle: "학습 방법",
  tip1: "답을 소리 내어 말하세요 — 이것은 구술 면접입니다.",
  tip2: "매일 15~20분씩 4~6주간 연습하세요.",
  tip3: "약한 문제는 스마트 복습을 활용하고, 연속 3회 합격할 때까지 시뮬레이션하세요.",
  tip4: "면접 전 USCIS에서 변경 가능한 답변을 확인하세요.",
  faqQ1: "어떤 시험 버전을 봐야 하나요?",
  faqA1:
    "2025년 10월 20일 이전에 N-400 양식을 제출했다면 2008년 시험(100문항)을 봅니다. 그날 또는 이후라면 2025년 시험(128문항)을 봅니다.",
  faqQ2: "면접 채점은 어떻게 이루어지나요?",
  faqA2:
    "2025년: 최대 20문항, 12개 정답 필요; 12개 정답 또는 9개 오답 시 면접관이 중단합니다. 2008년: 최대 10문항, 6개 정답 필요 (6개 정답 또는 5개 오답 시 중단).",
  faqQ3: "65/20 특별 고려란 무엇인가요?",
  faqA3:
    "65세 이상이고 20년 이상 영주권자인 경우, 별표 표시된 20문항만 학습하면 됩니다. 면접관은 10문항을 질문하며 6개 정답이 필요합니다. 원하는 언어로 시빅스 시험을 볼 수 있습니다.",
  faqQ4: "모국어로 시빅스 시험을 볼 수 있나요?",
  faqA4:
    "일반적으로 시빅스 시험은 영어로 진행됩니다. 예외: 65/20(원하는 언어 선택 가능), 그리고 영어 면제 대상인 50/20 또는 55/15의 경우 영어 부분은 면제되며 시빅스는 통역사와 함께 볼 수 있습니다.",
  faqQ5: "일부 답변이 바뀌기도 하나요?",
  faqA5:
    "네 — 대통령, 부통령, 하원의장, 대법원장, 상원의원, 하원의원, 주지사, 주도가 해당됩니다. 최신 정보를 위해 현직 공직자 목록과 ZIP 조회 기능을 활용하세요.",
  federalTitle: "현직 연방 공직자",
  federalLead: "이 답변들은 선거나 임명에 따라 변경됩니다. USCIS가 인정하는 이름을 학습하세요.",
  federalPresident: "대통령",
  federalVP: "부통령",
  federalSpeaker: "하원의장",
  federalChief: "대법원장",
  federalParty: "대통령 소속 정당",
  federalAsOf: "확인 기준일",
  modeSpeak: "소리 내어 말하기",
  modeSpeakHint: "영어 문제를 듣고 마이크로 답하세요 — 실제 면접처럼요.",
  speakStart: "답변 말하기",
  speakStop: "듣기 중지",
  speakHeard: "말한 내용",
  speakMatch: "좋습니다 — 인정된 답변과 일치합니다.",
  speakNoMatch: "아직 명확히 일치하지 않습니다. 인정 답변:",
  speakUnsupported:
    "이 브라우저에서는 음성 인식을 사용할 수 없습니다. Chrome을 사용하거나 답변 듣기 기능으로 직접 확인하세요.",
  navEnglish: "영어 시험",
  englishTitle: "영어 읽기 및 쓰기",
  englishLead: "귀화 면접에서 사용되는 USCIS 영어 읽기 및 쓰기 어휘를 연습하세요.",
  readingTitle: "읽기",
  writingTitle: "쓰기",
  readingHint: "문장을 소리 내어 읽으세요. 먼저 재생 버튼을 눌러 들어보세요.",
  writingHint: "문장을 듣고 입력하세요. 철자가 중요합니다.",
  writingPrompt: "들은 내용을 적으세요",
  writingCheck: "철자 확인",
  writingCorrect: "정답입니다!",
  writingTryAgain: "다시 시도하세요 — 목표 문장",
  nextSentence: "다음 문장",
  navQuestions: "문제",
  navResources: "자료",
  seoQuestionsHubTitle: "USCIS 시빅스 문제 — 무료 학습 페이지",
  seoQuestionsHubLead:
    "버전, 주제, 65/20 또는 주요 주별로 100문항 및 128문항 공식 시빅스 문제를 무료 오디오와 함께 둘러보세요.",
  seoAll128Title: "USCIS 시빅스 문제 128개 전체 (2025)",
  seoAll128Lead: "2025 공식 USCIS 128문항 + 무료 오디오 — 가입 없이 몇 초. 이어서 면접 시뮬레이션. 10개 이상 언어.",
  seoAll100Title: "USCIS 시빅스 문제 100개 전체 (2008)",
  seoAll100Lead: "2025년 10월 20일 이전 N-400 제출자용 2008 전체 은행. 무료 오디오, 계정 없음 — 준비되면 시뮬레이션.",
  seoSeniorTitle: "65/20 특별 시빅스 문제",
  seoSeniorLead: "65세+ 및 LPR 20년? 별표 20문항만 (10문항, 6개 정답). 무료 오디오, 가입 없음 — 몇 초. 10개 이상 언어.",
  seoStartPractice: "인터랙티브 연습 열기",
  seoAllLandings: "모든 문제 페이지",
  seoQuestionsCount: "이 페이지의 문항 수",
  seoBadge2025: "2025년 시험 · 128문항",
  seoBadge2008: "2008년 시험 · 100문항",
  seoTopicsHeading: "주제별 연습",
  seoStatesHeading: "주요 주별 학습 페이지",
  seoStateLead:
    "변경 가능한 시빅스 답변인 주도와 주지사를 복습한 뒤 전체 면접 세트를 연습하세요. 상원의원 및 하원의원은 연습에서 ZIP 조회 기능을 이용하세요.",
  seoStateCapital: "주도",
  seoStateGovernor: "주지사",
  seoStatePractice: "면접을 위한 시빅스 연습",
  seoReadingTitle: "영어 읽기 연습 — USCIS 어휘",
  seoReadingLead:
    "귀화 면접용 공식 USCIS 영어 읽기 어휘로 구성된 문장 읽기를 연습하세요.",
  seoWritingTitle: "영어 쓰기 연습 — USCIS 어휘",
  seoWritingLead:
    "공식 USCIS 영어 쓰기 어휘로 문장을 듣고 적으세요. 시험 당일에는 철자가 중요합니다.",
  learnPostsHeading: "가이드 및 자료",
  learnPostBack: "학습으로 돌아가기",
  learnReadMore: "더 읽기",
  legalBadge: "법적 고지 및 신뢰",
  navAbout: "소개",
  navContact: "문의하기",
  navPrivacy: "개인정보처리방침",
  navTerms: "이용약관",
  seoDrillsHeading: "특별 학습 드릴",
  seoDrillsLead:
    "가장 어려운 부분에 집중하세요: 핵심 날짜, 유명 인물의 이름, 선거에 따라 바뀌는 공직자 — 모든 문제에 무료 오디오가 제공됩니다.",
  seoStatesCount: "주 및 워싱턴 D.C. 학습 페이지",
  questionsSearchLabel: "시빅스 문제 검색",
  questionsSearchSubmit: "검색",
  questionsSearchHint: "2008년 및 2025년 문제 은행에서 문제 번호, 키워드 또는 답변으로 검색하세요.",
  questionsSearchResults: "검색 결과",
  exportProgress: "진행 상황 내보내기",
  importProgress: "진행 상황 가져오기",
  exportProgressHint: "다른 기기로 진행 상황을 옮기려면 백업 파일을 저장하세요.",
  importProgressDone: "진행 상황을 가져왔습니다.",
  importProgressError: "파일을 가져올 수 없습니다. USCivics Quiz 내보내기 파일을 사용하세요.",
  relatedStudyHeading: "계속 공부하기",
  relatedStudyLead: "같은 주제의 가이드, 문제 목록, 면접 연습으로 이동하세요.",
  relatedLearn: "가이드",
  relatedQuestions: "문제 목록",
  relatedPractice: "연습",
};
