import { completeDict } from "./complete";

export const ko = completeDict({
  tagline: "미국 시민권 시빅스 시험 무료 연습 — USCIS 2008 & 2025 문제.",
  heroSupport: "시험 버전을 확인한 뒤 플래시카드, 스마트 복습, 구두 연습, 면접 시뮬레이션으로 준비하세요.",
  startEligibility: "내 시험 버전 찾기",
  practiceHeading: "또는 바로 연습 시작",
  practice2008: "2008 버전",
  practice2008Meta: "100문항 · 10문항 출제 · 6개 정답 필요",
  practice2025: "2025 버전",
  practice2025Meta: "128문항 · 20문항 출제 · 12개 정답 필요",
  freeBadge: "무료 · 가입 없음",
  officialBadge: "공식 USCIS 문제",
  eligibilityTitle: "어떤 시빅스 시험을 보나요?",
  eligibilityLead: "두 가지 질문으로 올바른 연습 세트를 안내합니다.",
  q1: "2025년 10월 20일 이전에 N-400을 제출했나요?",
  q2: "만 65세 이상이고 영주권 20년 이상인가요?",
  yes: "예",
  no: "아니요",
  notSure: "잘 모르겠어요",
  resultSenior: "65/20 간소화 시험 대상입니다: 표시된 20문항 중 10문항 — 6개 정답 필요.",
  result2008: "2008 버전입니다: 최대 10/100 — 6개 정답 필요.",
  result2025: "2025 버전입니다: 최대 20/128 — 12개 정답 필요.",
  startPractice: "연습 시작",
  question: "문제",
  of: "/",
  showAnswer: "정답 보기",
  didYouKnow: "맞게 말했나요?",
  yourScore: "점수",
  passed: "면접 합격 기준에 도달합니다.",
  notPassed: "계속하세요 — 복습 후 다시 도전하세요.",
  tryAgain: "다시 연습",
  passNeed: "필요",
  correct: "정답",
  answersLabel: "인정 답변",
  langSwitch: "언어",
  disclaimer: "USCIS 또는 미국 정부와 무관합니다. 학습용 문제입니다.",
  modeFlashcards: "플래시카드",
  modeFlashcardsHint: "순서대로 — 뒤집고, 표시하고, 다음으로",
  modeRandom: "랜덤",
  modeRandomHint: "실제 문제 풀처럼 섞기",
  modeSmart: "스마트 복습",
  modeSmartHint: "약한/안 본 문제 우선",
  modeSimulate: "면접 시뮬레이션",
  modeSimulateHint: "합격/불합격 시 중단 — USCIS처럼",
  modeBrowse: "전체 보기",
  modeBrowseHint: "전체 검색 후 원하는 문제로 이동",
  browseSearch: "문제 검색…",
  zipTitle: "지역 공직자 (ZIP)",
  zipLead: "상원의원, 하원의원, 주지사, 주도 답은 거주지에 따라 다릅니다.",
  zipPlaceholder: "ZIP 코드",
  zipSubmit: "조회",
  zipSenators: "미국 상원의원",
  zipRepresentatives: "하원의원",
  zipGovernor: "주지사",
  zipCapital: "주도",
  filterAll: "전체",
  progressTitle: "학습 진행",
  speakQuestion: "문제 듣기 (EN)",
  speakAnswers: "답 듣기 (EN)",
  speakPractice: "영어로 크게 말하세요 — 면접은 구술입니다.",
  navPractice: "연습",
  navLearn: "학습",
  learnTitle: "학습 가이드 & FAQ",
  learnLead: "핵심 숫자, 사실, 시빅스 시험 FAQ.",
  keyNumbersTitle: "먼저 외울 핵심 숫자",
  faqTitle: "자주 묻는 질문",
  guideBranchesTitle: "정부 삼권 분립",
  guideAmendmentsTitle: "주요 수정 조항",
  guideTipsTitle: "공부 방법",
  tip1: "답을 크게 말하세요 — 구술 면접입니다.",
  tip2: "매일 15–20분, 4–6주 연습하세요.",
  tip3: "스마트 복습으로 약점을 잡고 연속 3회 합격할 때까지 시뮬레이션하세요.",
  tip4: "면접 전 USCIS에서 변동 답을 확인하세요.",
  faqQ1: "어느 버전을 보나요?",
  faqA1: "2025년 10월 20일 전 N-400 제출 → 2008(100문항). 그날 이후 → 2025(128문항).",
  faqQ2: "면접 채점은 어떻게 되나요?",
  faqA2: "2025: 최대 20문항, 12개 정답; 12정답 또는 9오답 시 중단. 2008: 최대 10문항, 6개 정답.",
  faqQ3: "65/20 특별 고려란?",
  faqA3: "65세 이상 + 영주 20년 이상이면 별표 20문항만 공부. 10문항 중 6개 정답. 원하는 언어로 시빅스 가능.",
  faqQ4: "모국어로 시빅스 시험을 볼 수 있나요?",
  faqA4: "보통 영어. 예외: 65/20(선택 언어), 영어 면제 50/20 또는 55/15(통역사).",
  faqQ5: "답이 바뀌는 문제가 있나요?",
  faqA5: "네 — 대통령, 부통령, 하원의장, 대법원장, 상·하원의원, 주지사, 주도. USCIS 업데이트와 ZIP 조회를 이용하세요.",
  saidCorrectly: "맞게 말했어요",
  gotWrong: "틀렸어요",
  changingBannerTitle: "변동하는 답",
  changingBannerLink: "USCIS 시험 업데이트",
});
