import { completeDict } from "./complete";

export const tl = completeDict({
  brand: "USCivics Quiz",
  siteName: "USCivics Quiz",
  tagline:
    "Libre at libreng pagsasanay sa civics test ng pagkamamamayan — tanong ng USCIS 2008 at 2025.",
  heroSupport:
    "Alamin ang bersyon ng iyong pagsusulit, tapos mag-aral gamit ang flashcards, smart review, oral practice, at totoong simulation.",
  startEligibility: "Hanapin ang bersyon ko",
  practiceHeading: "O magsimulang magpraktis",
  practice2008: "Bersyon 2008",
  practice2008Meta: "100 tanong · 10 itatanong · 6 para pumasa",
  practice2025: "Bersyon 2025",
  practice2025Meta: "128 tanong · 20 itatanong · 12 para pumasa",
  freeBadge: "Libre · Walang sign-up",
  bilingualBadge: "Maraming wika",
  officialBadge: "Opisyal na tanong ng USCIS",
  eligibilityTitle: "Aling civics test ang kukunin mo?",
  eligibilityLead: "Dalawang mabilis na tanong para ituro ka sa tamang set.",
  q1: "Nag-file ka ba ng Form N-400 bago ang Oktubre 20, 2025?",
  q2: "Ikaw ba ay 65+ taong gulang AT permanent resident nang 20+ taon?",
  yes: "Oo",
  no: "Hindi",
  notSure: "Hindi ako sigurado",
  resultSenior:
    "Karapat-dapat ka sa 65/20: 10 tanong mula sa 20 may bituin — kailangan ng 6 na tama.",
  result2008: "Kukunin mo ang 2008: hanggang 10 sa 100 — kailangan ng 6 na tama.",
  result2025: "Kukunin mo ang 2025: hanggang 20 sa 128 — kailangan ng 12 na tama.",
  startPractice: "Magsimulang magpraktis",
  question: "Tanong",
  of: "sa",
  showAnswer: "Ipakita ang sagot",
  didYouKnow: "Nasagot mo ba nang tama?",
  next: "Susunod na tanong",
  finish: "Tapusin",
  yourScore: "Iyong iskor",
  passed: "Aaabot ka sa passing score ng interview.",
  notPassed: "Magpatuloy — mag-review at subukan ulit.",
  tryAgain: "Magpraktis ulit",
  passNeed: "Kailangan ng",
  correct: "tama",
  answersLabel: "Tinatanggap na mga sagot",
  langSwitch: "Wika",
  backHome: "Home",
  disclaimer:
    "Hindi kaakibat o sinusuportahan ng USCIS o ng gobyerno ng U.S. Ang mga tanong ay para sa pag-aaral lamang.",
  stepOf: "Hakbang",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Mag-aral nang sunod-sunod — i-flip, markahan, magpatuloy",
  modeRandom: "Random",
  modeRandomHint: "I-shuffle tulad ng totoong pool",
  modeSmart: "Smart review",
  modeSmartHint: "Unahin ang mahina at hindi pa nakikita",
  modeSimulate: "I-simulate ang interview",
  modeSimulateHint: "Titigil sa pase o bagsak — tulad ng USCIS",
  modeBrowse: "Tingnan lahat",
  modeBrowseHint: "Hanapin sa buong pool at buksan ang anumang tanong",
  browseSearch: "Maghanap ng tanong…",
  browseEmpty: "Walang tumugmang tanong.",
  browseStudy: "Aralin ang card na ito",
  browseSeen: "Nakita",
  browseWeak: "Kailangang pag-aralan",
  browseStrong: "Malakas",
  browseNew: "Bago",
  zipTitle: "Mga lokal na opisyal (sa ZIP)",
  zipLead:
    "Ang mga sagot para sa senador, kinatawan, gobernador, at kapital ay depende sa iyong tirahan. Ilagay ang ZIP para aralin ang tamang pangalan.",
  zipPlaceholder: "ZIP code",
  zipSubmit: "Hanapin",
  zipLoading: "Hinahanap…",
  zipInvalid: "Maglagay ng wastong 5-digit na U.S. ZIP.",
  zipError: "Hindi mahanap ang ZIP na ito. Subukan ulit.",
  zipAmbiguous:
    "Saklaw ng ZIP na ito ang higit sa isang distritong House — alamin ang iyo bago ang interview.",
  zipSenators: "Mga Senador ng U.S.",
  zipRepresentatives: "Kinatawan",
  zipGovernor: "Gobernador",
  zipCapital: "Kapital ng estado",
  zipVerify: "Laging beripikahin ang kasalukuyang opisyal bago ang interview.",
  filterAll: "Lahat",
  progressTitle: "Iyong progreso",
  seen: "Nakita",
  streak: "Streak",
  bestStreak: "Pinakamahusay",
  accuracy: "Katumpakan",
  weak: "Mahina",
  mastered: "Malakas",
  resetProgress: "I-reset ang progreso",
  resetConfirm: "Burahin ang naka-save na progreso para sa bersyong ito?",
  sims: "Pasadong sim",
  seniorBadge: "65/20",
  changingBannerTitle: "Mga sagot na nagbabago",
  changingBannerBody:
    "May mga sagot na nakadepende sa eleksyon o appointment. Beripikahin bago ang interview.",
  changingBannerLink: "Tingnan ang update ng USCIS",
  changingCardNote: "Maaaring magbago ang sagot na ito — beripikahin sa USCIS bago ang interview.",
  interviewHowTitle: "Paano gumagana ang totoong interview",
  interviewHow1: "Nagtatanong nang pasalita ang opisyal mula sa opisyal na pool.",
  interviewHow2: "Titigil sila kapag pumasa o bumagsak ka.",
  interviewHow3: "Isipin ang sagot, i-reveal, tapos markahan nang tapat.",
  correctCount: "Tama",
  wrongCount: "Mali",
  failAt: "Bagsak sa",
  passAt: "Pasa sa",
  stoppedPass: "Huminto ang interview — naabot mo ang passing score.",
  stoppedFail: "Huminto ang interview — sobra ang maling sagot.",
  endTest: "Tapusin ang pagsusulit",
  startSim: "Simulan ang simulation",
  nextRandom: "Susunod na random",
  prev: "Nakaraan",
  flip: "I-flip",
  nextCard: "Susunod",
  keyboardHint: "Space i-reveal · Y/N markahan · ← → mag-navigate",
  categoryMastery: "Ayon sa kategorya",
  poolSize: "Sa set na ito",
  noQuestions: "Walang tanong sa filter na ito.",
  saidCorrectly: "Nasabi ko nang tama",
  gotWrong: "Mali ang sinabi ko",
  moreAnswers: "Tinatanggap na mga sagot",
  speakQuestion: "Pakinggan ang tanong (EN)",
  speakAnswers: "Pakinggan ang sagot (EN)",
  speakPractice: "Sabihin nang malakas sa Ingles ang sagot — pasalita ang interview.",
  navPractice: "Magpraktis",
  navLearn: "Matuto",
  learnTitle: "Gabay sa pag-aaral at FAQ",
  learnLead: "Mahahalagang numero, kaalaman, at madalas itanong tungkol sa civics test.",
  keyNumbersTitle: "Mahahalagang numerong kabisaduhin muna",
  faqTitle: "Madalas itanong",
  guideBranchesTitle: "Tatlong sangay ng pamahalaan",
  guideAmendmentsTitle: "Mahahalagang susog",
  guideTipsTitle: "Paano mag-aral",
  tip1: "Sabihin nang malakas ang mga sagot — pasalita ang interview.",
  tip2: "Magpraktis ng 15–20 minuto araw-araw sa loob ng 4–6 na linggo.",
  tip3: "Gamitin ang smart review sa mahihinang tanong, tapos mag-simulate hanggang makapasa nang 3 beses sunod-sunod.",
  tip4: "Beripikahin ang nagbabagong sagot sa USCIS bago ang interview.",
  faqQ1: "Aling bersyon ang kukunin ko?",
  faqA1:
    "Kung nag-file ng N-400 bago ang Oktubre 20, 2025 → 2008 (100 tanong). Simula sa petsang iyon → 2025 (128 tanong).",
  faqQ2: "Paano ang pagmamarka sa interview?",
  faqA2:
    "2025: hanggang 20 tanong, kailangan ng 12 tama; titigil sa 12 tama o 9 mali. 2008: hanggang 10, kailangan ng 6 (titigil sa 6 tama o 5 mali).",
  faqQ3: "Ano ang 65/20 special consideration?",
  faqA3:
    "Kung 65+ at permanent resident nang 20+ taon, 20 starred questions lang. 10 ang itatanong; kailangan ng 6. Maaaring sa wika mong pipiliin ang civics test.",
  faqQ4: "Pwede ko bang kunin ang civics test sa sarili kong wika?",
  faqA4:
    "Karaniwang Ingles. Exceptions: 65/20 (sariling wika), at English exemptions 50/20 o 55/15 na may interpreter para sa civics.",
  faqQ5: "May mga sagot bang nagbabago?",
  faqA5:
    "Oo — presidente, bise presidente, speaker, chief justice, iyong mga senador, kinatawan, gobernador, at kapital. Tingnan ang USCIS updates at gamitin ang ZIP lookup.",
});
