import type { Dictionary } from "./en";

export const tl: Dictionary = {
  brand: "USCivics Quiz",
  logoSubtitle: "Opisyal na USCIS practice",
  siteName: "USCivics Quiz",
  tagline: "Libreng USCIS civics practice app — alamin ang N-400 filing date (2008 vs 2025), tapos magsimula sa ilang segundo. Walang sign-up.",
  heroSupport: "Opisyal na question bank na may audio, flashcards, at interview simulation — sa 10+ wika.",
  startEligibility: "Hanapin ang bersyon ko",
  practiceHeading: "Magsimulang magpraktis",
  practiceCta: "Buksan ang praktis",
  practice2008: "2008 civics practice — opisyal na tanong",
  practice2008Meta: "100 tanong · 10 itatanong · 6 para pumasa",
  practice2025: "2025 civics practice — opisyal na tanong",
  practice2025Meta: "128 tanong · 20 itatanong · 12 para pumasa",
  freeBadge: "Libre · Walang sign-up · Segundo",
  bilingualBadge: "10+ wika",
  officialBadge: "Opisyal na tanong ng USCIS",
  practiceHubLead: "Walang sign-up. Opisyal na USCIS bank na may audio at interview simulation — magsimula sa ilang segundo.",
  practiceMetaTitleSuffix: "Libreng USCIS Interview Simulation",
  diffNoSignup: "Libre · Walang sign-up · Magsimula sa ilang segundo",
  diffRightBank: "Alamin kung aling bank ang aaralin: N-400 filing date (2008 vs 2025) o 65/20",
  diffOfficialPractice: "Opisyal na USCIS questions · Audio · Interview simulation",
  diffLanguages: "Mag-practice sa 10+ wika — hindi English-only",
  diffStripAria: "Bakit mag-practice dito",
  startInSecondsCta: "Magsimula ng practice sa ilang segundo",
  linkN400Filing: "N-400 filing date (2008 vs 2025)",
  link6520: "65/20 special consideration",
  linkHowMany: "Ilang tanong ang tinatanong",
  linkPassScore: "Anong score para pumasa",
  link2025Changes: "2025 civics changes",
  linkPractice2025Senior: "2025 · 65/20 practice",
  linkPractice2008Senior: "2008 · 65/20 practice",
  linkWhichCivicsTest: "Aling civics test?",
  linkFailTest: "Kung bagsak sa test",
  linkStudyPlan: "30-araw na plan",
  linkReadingWriting: "English reading at writing",
  eligibilityTitle: "Aling civics test ang kukunin mo?",
  eligibilityLead: "Dalawang mabilis na tanong. Ituturo ka namin sa tamang question bank bago mag-aral — 2008, 2025, o 65/20.",
  q1: "Nag-file ka ba ng Form N-400 bago ang Oktubre 20, 2025?",
  q2: "Ikaw ba ay 65+ taong gulang AT permanent resident nang 20+ taon?",
  yes: "Oo",
  no: "Hindi",
  notSure: "Hindi ako sigurado",
  resultSenior:
    "Karapat-dapat ka sa 65/20: 10 tanong mula sa 20 may bituin — kailangan ng 6 na tama.",
  result2008: "Kukunin mo ang 2008: hanggang 10 sa 100 — kailangan ng 6 na tama.",
  result2025: "Kukunin mo ang 2025: hanggang 20 sa 128 — kailangan ng 12 na tama.",
  startPractice: "Magsimulang magpraktis",
  question: "Tanong",
  of: "sa",
  showAnswer: "Ipakita ang sagot",
  didYouKnow: "Nasagot mo ba nang tama?",
  next: "Susunod na tanong",
  finish: "Tapusin",
  yourScore: "Iyong iskor",
  passed: "Aaabot ka sa passing score ng interview.",
  notPassed: "Magpatuloy — mag-review at subukan ulit.",
  tryAgain: "Magpraktis ulit",
  passNeed: "Kailangan ng",
  correct: "tama",
  answersLabel: "Tinatanggap na mga sagot",
  langSwitch: "Wika",
  backHome: "Home",
  disclaimer:
    "Hindi kaakibat o sinusuportahan ng USCIS o ng gobyerno ng U.S. Ang mga tanong ay para sa pag-aaral lamang.",
  stepOf: "Hakbang",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Mag-aral nang sunod-sunod — i-flip, markahan, magpatuloy",
  modeRandom: "Random",
  modeRandomHint: "I-shuffle tulad ng totoong pool",
  modeSmart: "Smart review",
  modeSmartHint: "Unahin ang mahina at hindi pa nakikita",
  modeSimulate: "I-simulate ang interview",
  modeSimulateHint: "Titigil sa pase o bagsak — tulad ng USCIS",
  modeBrowse: "Tingnan lahat",
  modeBrowseHint: "Hanapin sa buong pool at buksan ang anumang tanong",
  browseSearch: "Maghanap ng tanong…",
  browseEmpty: "Walang tumugmang tanong.",
  browseStudy: "Aralin ang card na ito",
  browseSeen: "Nakita",
  browseWeak: "Kailangang pag-aralan",
  browseStrong: "Malakas",
  browseNew: "Bago",
  zipTitle: "Mga lokal na opisyal (sa ZIP)",
  zipLead:
    "Ang mga sagot para sa senador, kinatawan, gobernador, at kapital ay depende sa iyong tirahan. Ilagay ang ZIP para aralin ang tamang pangalan.",
  zipPlaceholder: "ZIP code",
  zipSubmit: "Hanapin",
  zipLoading: "Hinahanap…",
  zipInvalid: "Maglagay ng wastong 5-digit na U.S. ZIP.",
  zipError: "Hindi mahanap ang ZIP na ito. Subukan ulit.",
  zipAmbiguous:
    "Saklaw ng ZIP na ito ang higit sa isang distritong House — alamin ang iyo bago ang interview.",
  zipSenators: "Mga Senador ng U.S.",
  zipRepresentatives: "Kinatawan",
  zipGovernor: "Gobernador",
  zipCapital: "Kapital ng estado",
  zipVerify: "Laging beripikahin ang kasalukuyang opisyal bago ang interview.",
  filterAll: "Lahat",
  progressTitle: "Iyong progreso",
  seen: "Nakita",
  streak: "Streak",
  bestStreak: "Pinakamahusay",
  accuracy: "Katumpakan",
  weak: "Mahina",
  mastered: "Malakas",
  resetProgress: "I-reset ang progreso",
  resetConfirm: "Burahin ang naka-save na progreso para sa bersyong ito?",
  sims: "Pasadong sim",
  seniorBadge: "65/20",
  changingBannerTitle: "Mga sagot na nagbabago",
  changingBannerBody:
    "May mga sagot na nakadepende sa eleksyon o appointment. Beripikahin bago ang interview.",
  changingBannerLink: "Buksan ang mga update sa pagsusulit",
  changingCardNote: "Maaaring magbago ang sagot na ito — beripikahin sa USCIS bago ang interview.",
  interviewHowTitle: "Paano gumagana ang totoong interview",
  interviewHow1: "Nagtatanong nang pasalita ang opisyal mula sa opisyal na pool.",
  interviewHow2: "Titigil sila kapag pumasa o bumagsak ka.",
  interviewHow3: "Isipin ang sagot, i-reveal, tapos markahan nang tapat.",
  correctCount: "Tama",
  wrongCount: "Mali",
  failAt: "Bagsak sa",
  passAt: "Pasa sa",
  stoppedPass: "Huminto ang interview — naabot mo ang passing score.",
  stoppedFail: "Huminto ang interview — sobra ang maling sagot.",
  endTest: "Tapusin ang pagsusulit",
  startSim: "Simulan ang simulation",
  nextRandom: "Susunod na random",
  prev: "Nakaraan",
  flip: "I-flip",
  nextCard: "Susunod",
  keyboardHint: "Space i-reveal · Y/N markahan · ← → mag-navigate",
  categoryMastery: "Ayon sa kategorya",
  poolSize: "Sa set na ito",
  noQuestions: "Walang tanong sa filter na ito.",
  saidCorrectly: "Nasabi ko nang tama",
  gotWrong: "Mali ang sinabi ko",
  moreAnswers: "Tinatanggap na mga sagot",
  speakQuestion: "Pakinggan ang tanong (EN)",
  speakAnswers: "Pakinggan ang sagot (EN)",
  speakPractice: "Sabihin nang malakas sa Ingles ang sagot — pasalita ang interview.",
  navPractice: "Magpraktis",
  navLearn: "Mga gabay",
  navCitizenship: "Aking bersyon",
  navCivicsTest: "Civics Test",
  navReadingTest: "Reading Test",
  navWritingTest: "Writing Test",
  navTest2025: "Civics 2025",
  navTest2008: "Civics 2008",
  navSenior: "65/20",
  menuOpen: "Buksan ang menu",
  menuClose: "Isara ang menu",
  navHome: "Home",
  themeToLight: "Lumipat sa light mode",
  themeToDark: "Lumipat sa dark mode",
  uscisUpdatesPageTitle: "Tingnan ang mga Update sa Pagsusulit",
  uscisAlertLabel: "PAALALA:",
  uscisAlertBody:
    "Ipinapatupad ng USCIS ang 2025 naturalization civics test upang umayon sa Executive Order 14161. Ang mga aliens na mag-file ng Form N-400 para mag-apply ng naturalization bago ang Okt. 20, 2025, ay kukuha ng 2008 naturalization civics test. Ang mga mag-file ng Form N-400 sa o pagkatapos ng Okt. 20, 2025, ay kukuha ng 2025 na pagsusulit. Ang bagong 2025 na pagsusulit ay batay sa 2020 naturalization civics test, na may ilang pagbabago sa paraan ng pag-aadminister ng pagsusulit.",
  uscisFilingColDate: "Petsa ng Pag-file ng N-400",
  uscisFilingColVersion: "Bersyon ng Civics Test",
  uscisFilingBefore: "Bago ang Okt. 20, 2025",
  uscisFilingBeforeVersion: "2008 Naturalization Civics Test",
  uscisFilingAfter: "Sa o Pagkatapos ng Okt. 20, 2025",
  uscisFilingAfterVersion: "2025 Naturalization Civics Test",
  uscis2008Heading: "2008 Naturalization Civics Test",
  uscis2008Body:
    "Aadministrahin namin ang 2008 naturalization civics test sa mga aliens na mag-a-apply para sa naturalization na mag-file ng Form N-400 bago ang Okt. 20, 2025.",
  uscis2025Heading: "2025 Naturalization Civics Test",
  uscis2025Body:
    "Aadministrahin namin ang 2025 naturalization civics test sa mga aliens na mag-a-apply para sa naturalization na mag-file ng Form N-400 sa o pagkatapos ng Okt. 20, 2025.",
  uscisResourcesHeading: "Opisyal na mapagkukunan ng USCIS",
  uscisResourcesLead:
    "Mga materyal sa pag-aaral at update mula sa U.S. Citizenship and Immigration Services. Nagli-link kami palabas — hindi kami nag-i-host ng opisyal na mga PDF.",
  uscisStudyTitle: "Mag-aral para sa Pagsusulit",
  uscisStudyBlurb: "Buod ng Ingles + civics at libreng materyal sa pag-aaral",
  uscisUpdatesTitle: "Tingnan ang mga Update sa Pagsusulit",
  uscisUpdatesBlurb: "Mga opisyal at sagot na nagbabago sa bawat eleksyon",
  uscis2025Title: "2025 Civics Test",
  uscis2025Blurb: "Pahina ng patakaran para sa 2025 naturalization civics test",
  uscisExceptionsTitle: "Mga eksepsyon at akomodasyon",
  uscisExceptionsBlurb: "65/20 at mga eksepsyon sa English test",
  uscisN400Title: "Form N-400",
  uscisN400Blurb: "Application for Naturalization",
  uscisPdf128Title: "128 tanong na PDF (2025)",
  uscisPdf128Blurb: "Opisyal na listahan ng Q&A sa Ingles",
  uscisPdf100Title: "100 tanong na PDF (2008)",
  uscisPdf100Blurb: "Opisyal na listahan ng Q&A sa Ingles",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "Opisyal na website ng U.S. Citizenship and Immigration Services",
  learnTitle: "Gabay sa pag-aaral at FAQ",
  learnLead: "Mahahalagang numero, kaalaman, at madalas itanong tungkol sa civics test.",
  keyNumbersTitle: "Mahahalagang numerong kabisaduhin muna",
  faqTitle: "Madalas itanong",
  guideBranchesTitle: "Tatlong sangay ng pamahalaan",
  guideAmendmentsTitle: "Mahahalagang susog",
  guideTipsTitle: "Paano mag-aral",
  tip1: "Sabihin nang malakas ang mga sagot — pasalita ang interview.",
  tip2: "Magpraktis ng 15–20 minuto araw-araw sa loob ng 4–6 na linggo.",
  tip3: "Gamitin ang smart review sa mahihinang tanong, tapos mag-simulate hanggang makapasa nang 3 beses sunod-sunod.",
  tip4: "Beripikahin ang nagbabagong sagot sa USCIS bago ang interview.",
  faqQ1: "Aling bersyon ang kukunin ko?",
  faqA1:
    "Kung nag-file ng N-400 bago ang Oktubre 20, 2025 → 2008 (100 tanong). Simula sa petsang iyon → 2025 (128 tanong).",
  faqQ2: "Paano ang pagmamarka sa interview?",
  faqA2:
    "2025: hanggang 20 tanong, kailangan ng 12 tama; titigil sa 12 tama o 9 mali. 2008: hanggang 10, kailangan ng 6 (titigil sa 6 tama o 5 mali).",
  faqQ3: "Ano ang 65/20 special consideration?",
  faqA3:
    "Kung 65+ at permanent resident nang 20+ taon, 20 starred questions lang. 10 ang itatanong; kailangan ng 6. Maaaring sa wika mong pipiliin ang civics test.",
  faqQ4: "Pwede ko bang kunin ang civics test sa sarili kong wika?",
  faqA4:
    "Karaniwang Ingles. Exceptions: 65/20 (sariling wika), at English exemptions 50/20 o 55/15 na may interpreter para sa civics.",
  faqQ5: "May mga sagot bang nagbabago?",
  faqA5:
    "Oo — presidente, bise presidente, speaker, chief justice, iyong mga senador, kinatawan, gobernador, at kapital. Tingnan ang USCIS updates at gamitin ang ZIP lookup.",
  federalTitle: "Kasalukuyang mga pederal na opisyal",
  federalLead:
    "Nagbabago ang mga sagot na ito sa eleksyon o appointment. Aralin ang mga pangalang tinatanggap ng USCIS.",
  federalPresident: "Pangulo",
  federalVP: "Pangalawang Pangulo",
  federalSpeaker: "Speaker ng House",
  federalChief: "Punong Mahistrado",
  federalParty: "Partido ng Pangulo",
  federalAsOf: "Beripikado noong",
  modeSpeak: "Magsalita nang malakas",
  modeSpeakHint:
    "Pakinggan ang tanong sa Ingles, tapos sagutin gamit ang mikropono — tulad ng totoong interview.",
  speakStart: "Sabihin ang sagot ko",
  speakStop: "Ihinto ang pakikinig",
  speakHeard: "Sinabi mo",
  speakMatch: "Mahusay — tumutugma sa isang tinatanggap na sagot.",
  speakNoMatch: "Hindi pa malinaw na tugma. Mga tinatanggap na sagot:",
  speakUnsupported:
    "Hindi available ang speech recognition sa browser na ito. Subukan ang Chrome, o gamitin ang Pakinggan ang sagot para sarili mong tsekin.",
  navEnglish: "English test",
  englishTitle: "Pagbasa at pagsulat sa Ingles",
  englishLead:
    "Magsanay sa opisyal na bokabularyo ng USCIS sa pagbasa at pagsulat na ginagamit sa naturalization interview.",
  readingTitle: "Reading",
  writingTitle: "Writing",
  readingHint: "Basahin nang malakas ang pangungusap. Pindutin ang play para marinig muna.",
  writingHint: "Pakinggan ang pangungusap, tapos i-type ito. Mahalaga ang spelling.",
  writingPrompt: "Isulat ang naririnig mo",
  writingCheck: "Suriin ang spelling",
  writingCorrect: "Tama!",
  writingTryAgain: "Subukan ulit — target na pangungusap",
  nextSentence: "Susunod na pangungusap",
  navQuestions: "Mga Tanong",
  navResources: "Mga Resource",
  seoQuestionsHubTitle: "Mga tanong sa civics ng USCIS — libreng landing para mag-aral",
  seoQuestionsHubLead:
    "Tingnan lahat ng 100 at 128 opisyal na tanong sa civics ayon sa bersyon, paksa, 65/20, o mga nangungunang estado — may libreng audio.",
  seoAll128Title: "Lahat ng 128 Tanong sa Civics ng USCIS (2025)",
  seoAll128Lead: "Lahat ng 128 opisyal na 2025 USCIS question na may libreng audio — walang sign-up, ilang segundo. Pagkatapos ay interview simulation. 10+ wika.",
  seoAll100Title: "Lahat ng 100 Tanong sa Civics ng USCIS (2008)",
  seoAll100Lead: "Buong 2008 bank kung nag-file ng N-400 bago ang Oktubre 20, 2025. Libreng audio, walang account — mag-simulate kapag handa.",
  seoSeniorTitle: "Espesyal na Tanong sa Civics 65/20",
  seoSeniorLead: "65+ at 20 taon LPR? 20 starred questions lang (10 tinatanong, 6 para pumasa). Libreng audio, walang sign-up — ilang segundo. 10+ wika.",
  seoStartPractice: "Buksan ang interactive na praktis",
  seoAllLandings: "Lahat ng landing ng tanong",
  seoQuestionsCount: "tanong sa pahinang ito",
  seoBadge2025: "2025 na pagsusulit · 128 tanong",
  seoBadge2008: "2008 na pagsusulit · 100 tanong",
  seoTopicsHeading: "Magpraktis ayon sa paksa",
  seoStatesHeading: "Mga pahina ng pinakasikat na estado",
  seoStateLead:
    "Balikan ang kapital at gobernador ng iyong estado para sa mga nagbabagong sagot sa civics, tapos magpraktis sa buong interview set. Gamitin ang ZIP lookup sa praktis para sa senador at kinatawan mo.",
  seoStateCapital: "Kapital ng estado",
  seoStateGovernor: "Gobernador",
  seoStatePractice: "Magpraktis ng civics para sa iyong interview",
  seoReadingTitle: "Praktis sa pagbasa ng Ingles — bokabularyo ng USCIS",
  seoReadingLead:
    "Magsanay magbasa ng mga pangungusap na ginawa mula sa opisyal na bokabularyo ng pagbasa sa Ingles ng USCIS para sa naturalization interview.",
  seoWritingTitle: "Praktis sa pagsulat ng Ingles — bokabularyo ng USCIS",
  seoWritingLead:
    "Makinig at sumulat ng mga pangungusap gamit ang opisyal na bokabularyo ng pagsulat ng USCIS. Mahalaga ang spelling sa araw ng pagsusulit.",
  learnPostsHeading: "Mga gabay at resource",
  learnPostBack: "Bumalik sa matuto",
  learnReadMore: "Magbasa pa",
  legalBadge: "Legal at tiwala",
  navAbout: "Tungkol sa amin",
  navContact: "Makipag-ugnayan",
  navPrivacy: "Privacy",
  navTerms: "Mga Tuntunin",
  seoDrillsHeading: "Mga espesyal na drill sa pag-aaral",
  seoDrillsLead:
    "Mag-focus sa pinakamahirap na cluster: mahahalagang petsa, tanyag na pangalan, at mga opisyal na nagbabago ang sagot sa bawat eleksyon — libreng audio sa bawat tanong.",
  seoStatesCount: "pahina ng estado at DC",
  questionsSearchLabel: "Maghanap ng mga tanong sa civics",
  questionsSearchSubmit: "Maghanap",
  questionsSearchHint:
    "Maghanap ayon sa numero ng tanong, keyword, o sagot sa mga bangko ng 2008 at 2025.",
  questionsSearchResults: "Mga tugma",
  exportProgress: "I-export ang progreso",
  importProgress: "I-import ang progreso",
  exportProgressHint: "Mag-save ng backup file para ilipat ang progreso sa ibang device.",
  importProgressDone: "Na-import ang progreso.",
  importProgressError: "Hindi ma-import ang file. Gumamit ng export mula sa USCivics Quiz.",
  relatedStudyHeading: "Magpatuloy sa pag-aaral",
  relatedStudyLead: "Lumipat sa mga gabay, listahan ng tanong, at practice ng interview para sa parehong paksa.",
  relatedLearn: "Mga gabay",
  relatedQuestions: "Mga listahan ng tanong",
  relatedPractice: "Practice",
  premiumWaitlistTitle: "Progress sa ibang device (malapit na)",
  premiumWaitlistLead: "Libre magpakailanman ang core practice. Sumali sa waitlist para sa optional cloud sync — walang paywall sa question bank.",
  premiumWaitlistCta: "Abisuhan ako kapag may premium",
  premiumWaitlistDone: "Nasa waitlist ka na sa device na ito.",
  navUpdates: "Mga update",
  govBannerLead: "Hindi opisyal na practice site — hindi ito site ng gobyerno ng U.S.",
  govBannerHow: "Ganito mo malalaman",
  govBannerOfficial: "Ang opisyal na USCIS sites ay gumagamit ng .gov at inilathala ng gobyerno ng U.S. Ang site na ito ay independent study tool.",
  govBannerSecure: "Palaging i-verify ang changing answers at rules sa uscis.gov bago ang interview.",
  updatesHubTitle: "Mga update sa civics test",
  updatesHubLead: "Filing date (2008 vs 2025), opisyal na nagbabago, at ZIP lookup — makitid na exam changelog, hindi news feed.",
  updatesPolicyHeading: "Mga tala sa policy at exam",
  updatesLiveHeading: "Live na opisyal at lokal na sagot",
  updatesLiveBadge: "Live",
  updatesCachedBadge: "Cached",
  updatesVerifyNote: "Kumpirmahin ang mga pangalan sa linggo ng interview. Maaaring magbago ang sagot dahil sa eleksyon o appointment.",
  homeLiveHeading: "Kasalukuyang opisyal",
  homeLiveLead: "Live na federal names para sa araw ng interview — kasama ang ZIP lookup para sa senators, representative, governor, at capital.",
  homeLiveCta: "Buksan ang mga update",
  linkUpdates: "Mga update sa civics test",
};
