import type { Dictionary } from "./en";

export const vi: Dictionary = {
  brand: "USCivics Quiz",
  logoSubtitle: "Luyện thi công dân",
  siteName: "USCivics Quiz",
  tagline: "Luyện thi công dân USCIS miễn phí — biết ngày nộp N-400 (2008 vs 2025), bắt đầu trong vài giây. Không đăng ký.",
  heroSupport: "Ngân hàng câu hỏi chính thức với audio, flashcard và mô phỏng phỏng vấn — hơn 10 ngôn ngữ.",
  startEligibility: "Tìm phiên bản của tôi",
  practiceHeading: "Bắt đầu luyện tập",
  practiceCta: "Mở phần luyện tập",
  practice2008: "Luyện thi công dân 2008 — câu hỏi chính thức",
  practice2008Meta: "100 câu · hỏi 10 · cần 6 đúng",
  practice2025: "Luyện thi công dân 2025 — câu hỏi chính thức",
  practice2025Meta: "128 câu · hỏi 20 · cần 12 đúng",
  freeBadge: "Miễn phí · Không đăng ký · Vài giây",
  bilingualBadge: "Hơn 10 ngôn ngữ",
  officialBadge: "Câu hỏi chính thức USCIS",
  practiceHubLead: "Không đăng ký. Ngân hàng USCIS chính thức với audio và mô phỏng phỏng vấn — bắt đầu trong vài giây.",
  practiceMetaTitleSuffix: "Mô phỏng phỏng vấn USCIS miễn phí",
  diffNoSignup: "Miễn phí · Không đăng ký · Bắt đầu trong vài giây",
  diffRightBank: "Biết ngân hàng nào cần học: ngày nộp N-400 (2008 vs 2025) hoặc 65/20",
  diffOfficialPractice: "Câu hỏi USCIS chính thức · Audio · Mô phỏng phỏng vấn",
  diffLanguages: "Luyện hơn 10 ngôn ngữ — không chỉ tiếng Anh",
  diffStripAria: "Vì sao luyện ở đây",
  startInSecondsCta: "Bắt đầu luyện trong vài giây",
  linkN400Filing: "Ngày nộp N-400 (2008 vs 2025)",
  link6520: "Xét đặc biệt 65/20",
  linkHowMany: "Hỏi bao nhiêu câu",
  linkPassScore: "Điểm để đậu",
  link2025Changes: "Thay đổi công dân 2025",
  linkPractice2025Senior: "2025 · luyện 65/20",
  linkPractice2008Senior: "2008 · luyện 65/20",
  linkWhichCivicsTest: "Tôi thi bộ nào?",
  linkFailTest: "Nếu trượt bài thi",
  linkStudyPlan: "Kế hoạch 30 ngày",
  linkReadingWriting: "Đọc & viết tiếng Anh",
  eligibilityTitle: "Bạn thi phiên bản nào?",
  eligibilityLead: "Hai câu hỏi nhanh. Chúng tôi chỉ đúng ngân hàng trước khi bạn học — 2008, 2025 hoặc 65/20.",
  q1: "Bạn đã nộp Form N-400 trước ngày 20 tháng 10 năm 2025?",
  q2: "Bạn từ 65 tuổi trở lên VÀ là thường trú nhân từ 20 năm trở lên?",
  yes: "Có",
  no: "Không",
  notSure: "Tôi không chắc",
  resultSenior: "Bạn đủ điều kiện bài thi 65/20: 10 câu từ bộ 20 câu đánh dấu — cần 6 đúng.",
  result2008: "Bạn thi bản 2008: tối đa 10/100 câu — cần 6 đúng.",
  result2025: "Bạn thi bản 2025: tối đa 20/128 câu — cần 12 đúng.",
  startPractice: "Bắt đầu luyện",
  question: "Câu hỏi",
  of: "/",
  showAnswer: "Hiện đáp án",
  didYouKnow: "Bạn trả lời đúng chứ?",
  next: "Câu tiếp",
  finish: "Kết thúc",
  yourScore: "Điểm của bạn",
  passed: "Bạn đạt ngưỡng đậu phỏng vấn.",
  notPassed: "Tiếp tục — ôn lại và thử vòng khác.",
  tryAgain: "Luyện lại",
  passNeed: "Cần",
  correct: "đúng",
  answersLabel: "Đáp án chấp nhận",
  langSwitch: "Ngôn ngữ",
  backHome: "Trang chủ",
  disclaimer:
    "Không liên kết hoặc được USCIS hay chính phủ Hoa Kỳ chứng nhận. Câu hỏi chỉ để học.",
  stepOf: "Bước",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Học theo thứ tự — lật, đánh dấu, tiếp",
  modeRandom: "Ngẫu nhiên",
  modeRandomHint: "Xáo trộn như ngân hàng thật",
  modeSmart: "Ôn thông minh",
  modeSmartHint: "Ưu tiên câu yếu & chưa thấy",
  modeSimulate: "Mô phỏng phỏng vấn",
  modeSimulateHint: "Dừng khi đậu hoặc rớt — như USCIS",
  modeBrowse: "Xem tất cả",
  modeBrowseHint: "Tìm trong toàn bộ ngân hàng và mở bất kỳ câu nào",
  browseSearch: "Tìm câu hỏi…",
  browseEmpty: "Không có câu nào khớp.",
  browseStudy: "Học thẻ này",
  browseSeen: "Đã xem",
  browseWeak: "Cần ôn",
  browseStrong: "Vững",
  browseNew: "Mới",
  zipTitle: "Quan chức địa phương (theo ZIP)",
  zipLead:
    "Thượng nghị sĩ, dân biểu, thống đốc và thủ phủ tiểu bang phụ thuộc nơi bạn sống. Nhập ZIP để học đúng tên.",
  zipPlaceholder: "Mã ZIP",
  zipSubmit: "Tra cứu",
  zipLoading: "Đang tra…",
  zipInvalid: "Nhập ZIP Hoa Kỳ gồm 5 chữ số.",
  zipError: "Không tra được ZIP này. Thử lại.",
  zipAmbiguous:
    "ZIP này thuộc nhiều quận Hạ viện — hãy xác nhận quận của bạn trước buổi phỏng vấn.",
  zipSenators: "Thượng nghị sĩ Hoa Kỳ",
  zipRepresentatives: "Dân biểu",
  zipGovernor: "Thống đốc",
  zipCapital: "Thủ phủ tiểu bang",
  zipVerify: "Luôn xác minh quan chức hiện tại trước buổi phỏng vấn.",
  filterAll: "Tất cả",
  progressTitle: "Tiến độ của bạn",
  seen: "Đã xem",
  streak: "Chuỗi",
  bestStreak: "Tốt nhất",
  accuracy: "Độ chính xác",
  weak: "Yếu",
  mastered: "Vững",
  resetProgress: "Đặt lại tiến độ",
  resetConfirm: "Xóa tiến độ đã lưu của phiên bản này?",
  sims: "Mô phỏng đậu",
  seniorBadge: "65/20",
  changingBannerTitle: "Đáp án có thể đổi",
  changingBannerBody:
    "Một số đáp án phụ thuộc bầu cử hoặc bổ nhiệm. Hãy xác minh trước buổi phỏng vấn.",
  changingBannerLink: "Xem cập nhật USCIS",
  changingCardNote: "Đáp án này có thể đổi — xác minh trên USCIS trước buổi phỏng vấn.",
  interviewHowTitle: "Phỏng vấn thật diễn ra thế nào",
  interviewHow1: "Viên chức hỏi miệng từ ngân hàng chính thức.",
  interviewHow2: "Họ dừng khi bạn đạt ngưỡng đậu hoặc rớt.",
  interviewHow3: "Nghĩ đáp án, mở đáp án, rồi đánh dấu trung thực.",
  correctCount: "Đúng",
  wrongCount: "Sai",
  failAt: "Rớt khi",
  passAt: "Đậu khi",
  stoppedPass: "Dừng phỏng vấn — bạn đã đạt điểm đậu.",
  stoppedFail: "Dừng phỏng vấn — quá nhiều câu sai.",
  endTest: "Kết thúc bài thi",
  startSim: "Bắt đầu mô phỏng",
  nextRandom: "Câu ngẫu nhiên tiếp",
  prev: "Trước",
  flip: "Lật",
  nextCard: "Tiếp",
  keyboardHint: "Space mở · Y/N đánh dấu · ← → điều hướng",
  categoryMastery: "Theo chủ đề",
  poolSize: "Trong bộ này",
  noQuestions: "Không có câu với bộ lọc này.",
  saidCorrectly: "Tôi nói đúng",
  gotWrong: "Tôi nói sai",
  moreAnswers: "Đáp án chấp nhận",
  speakQuestion: "Nghe câu hỏi (EN)",
  speakAnswers: "Nghe đáp án (EN)",
  speakPractice: "Hãy nói đáp án bằng tiếng Anh to — buổi phỏng vấn là miệng.",
  navPractice: "Luyện tập",
  navLearn: "Học",
  navCitizenship: "Quốc tịch Hoa Kỳ",
  navCivicsTest: "Bài thi công dân",
  navReadingTest: "Bài thi đọc",
  navWritingTest: "Bài thi viết",
  navTest2025: "Công dân 2025",
  navTest2008: "Công dân 2008",
  navSenior: "65/20",
  menuOpen: "Mở menu",
  menuClose: "Đóng menu",
  navHome: "Trang chủ",
  themeToLight: "Chuyển sang chế độ sáng",
  themeToDark: "Chuyển sang chế độ tối",
  uscisUpdatesPageTitle: "Kiểm tra cập nhật bài thi",
  uscisAlertLabel: "CẢNH BÁO:",
  uscisAlertBody:
    "USCIS đang triển khai bài thi công dân nhập tịch 2025 để phù hợp với Sắc lệnh Hành pháp 14161. Người nộp Mẫu N-400 xin nhập tịch trước ngày 20 tháng 10 năm 2025 sẽ thi bài thi công dân nhập tịch 2008. Người nộp Mẫu N-400 vào hoặc sau ngày 20 tháng 10 năm 2025 sẽ thi bài thi 2025. Bài thi 2025 mới dựa trên bài thi công dân nhập tịch 2020, với một số thay đổi trong cách tổ chức thi.",
  uscisFilingColDate: "Ngày nộp N-400",
  uscisFilingColVersion: "Phiên bản bài thi công dân",
  uscisFilingBefore: "Trước ngày 20/10/2025",
  uscisFilingBeforeVersion: "Bài thi công dân nhập tịch 2008",
  uscisFilingAfter: "Vào hoặc sau ngày 20/10/2025",
  uscisFilingAfterVersion: "Bài thi công dân nhập tịch 2025",
  uscis2008Heading: "Bài thi công dân nhập tịch 2008",
  uscis2008Body:
    "Chúng tôi sẽ tổ chức bài thi công dân nhập tịch 2008 cho người nộp đơn xin nhập tịch bằng Mẫu N-400 trước ngày 20 tháng 10 năm 2025.",
  uscis2025Heading: "Bài thi công dân nhập tịch 2025",
  uscis2025Body:
    "Chúng tôi sẽ tổ chức bài thi công dân nhập tịch 2025 cho người nộp Mẫu N-400 vào hoặc sau ngày 20 tháng 10 năm 2025.",
  uscisResourcesHeading: "Tài nguyên chính thức của USCIS",
  uscisResourcesLead:
    "Tài liệu học tập và cập nhật từ Sở Di trú và Nhập tịch Hoa Kỳ. Chúng tôi chỉ liên kết ra ngoài — không lưu trữ PDF chính thức.",
  uscisStudyTitle: "Ôn thi",
  uscisStudyBlurb: "Tổng quan tiếng Anh + công dân và tài liệu học miễn phí",
  uscisUpdatesTitle: "Kiểm tra cập nhật bài thi",
  uscisUpdatesBlurb: "Quan chức và đáp án thay đổi theo bầu cử",
  uscis2025Title: "Bài thi công dân 2025",
  uscis2025Blurb: "Trang chính sách bài thi công dân nhập tịch 2025",
  uscisExceptionsTitle: "Ngoại lệ & hỗ trợ đặc biệt",
  uscisExceptionsBlurb: "65/20 và ngoại lệ bài thi tiếng Anh",
  uscisN400Title: "Mẫu N-400",
  uscisN400Blurb: "Đơn xin nhập tịch",
  uscisPdf128Title: "PDF 128 câu (2025)",
  uscisPdf128Blurb: "Danh sách hỏi đáp chính thức bằng tiếng Anh",
  uscisPdf100Title: "PDF 100 câu (2008)",
  uscisPdf100Blurb: "Danh sách hỏi đáp chính thức bằng tiếng Anh",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "Trang chính thức của Sở Di trú và Nhập tịch Hoa Kỳ",
  learnTitle: "Hướng dẫn học & FAQ",
  learnLead: "Số liệu then chốt, kiến thức và câu hỏi thường gặp về bài thi công dân.",
  keyNumbersTitle: "Số liệu quan trọng cần nhớ trước",
  faqTitle: "Câu hỏi thường gặp",
  guideBranchesTitle: "Ba nhánh chính quyền",
  guideAmendmentsTitle: "Các tu chính quan trọng",
  guideTipsTitle: "Cách học",
  tip1: "Nói đáp án to — đây là phỏng vấn miệng.",
  tip2: "Luyện 15–20 phút mỗi ngày trong 4–6 tuần.",
  tip3: "Dùng ôn thông minh cho câu yếu, rồi mô phỏng đến khi đậu 3 lần liên tiếp.",
  tip4: "Xác minh đáp án thay đổi trên USCIS trước buổi phỏng vấn.",
  faqQ1: "Tôi thi phiên bản nào?",
  faqA1:
    "Nếu nộp N-400 trước 20/10/2025 → bản 2008 (100 câu). Từ ngày đó trở đi → bản 2025 (128 câu).",
  faqQ2: "Cách tính điểm phỏng vấn?",
  faqA2:
    "2025: tối đa 20 câu, cần 12 đúng; dừng ở 12 đúng hoặc 9 sai. 2008: tối đa 10 câu, cần 6 đúng (dừng ở 6 đúng hoặc 5 sai).",
  faqQ3: "65/20 là gì?",
  faqA3:
    "Từ 65 tuổi và thường trú 20+ năm: chỉ học 20 câu có sao. Viên chức hỏi 10; cần 6 đúng. Có thể thi công dân bằng ngôn ngữ bạn chọn.",
  faqQ4: "Tôi có thể thi công dân bằng ngôn ngữ của mình?",
  faqA4:
    "Thường bằng tiếng Anh. Ngoại lệ: 65/20 (ngôn ngữ tự chọn) và miễn tiếng Anh 50/20 hoặc 55/15 với thông dịch viên cho phần công dân.",
  faqQ5: "Một số đáp án có đổi không?",
  faqA5:
    "Có — tổng thống, phó tổng thống, chủ tịch Hạ viện, chánh án, thượng nghị sĩ, dân biểu, thống đốc và thủ phủ. Kiểm tra USCIS và dùng tra ZIP.",
  federalTitle: "Quan chức liên bang hiện tại",
  federalLead:
    "Các đáp án này thay đổi theo bầu cử hoặc bổ nhiệm. Hãy học đúng tên mà USCIS công nhận.",
  federalPresident: "Tổng thống",
  federalVP: "Phó Tổng thống",
  federalSpeaker: "Chủ tịch Hạ viện",
  federalChief: "Chánh án Tòa án Tối cao",
  federalParty: "Đảng của Tổng thống",
  federalAsOf: "Xác minh vào",
  modeSpeak: "Nói to",
  modeSpeakHint:
    "Nghe câu hỏi tiếng Anh, rồi trả lời bằng micro — như buổi phỏng vấn thật.",
  speakStart: "Nói câu trả lời của tôi",
  speakStop: "Ngừng nghe",
  speakHeard: "Bạn đã nói",
  speakMatch: "Tốt — khớp với một đáp án được chấp nhận.",
  speakNoMatch: "Chưa khớp rõ ràng. Các đáp án được chấp nhận:",
  speakUnsupported:
    "Trình duyệt này không hỗ trợ nhận dạng giọng nói. Hãy thử Chrome, hoặc dùng Nghe đáp án để tự kiểm tra.",
  navEnglish: "Bài thi tiếng Anh",
  englishTitle: "Đọc & viết tiếng Anh",
  englishLead:
    "Luyện tập từ vựng đọc và viết tiếng Anh của USCIS dùng trong phỏng vấn nhập tịch.",
  readingTitle: "Đọc",
  writingTitle: "Viết",
  readingHint: "Đọc to câu này. Nhấn play để nghe trước.",
  writingHint: "Nghe câu rồi gõ lại. Chính tả được tính điểm.",
  writingPrompt: "Viết những gì bạn nghe",
  writingCheck: "Kiểm tra chính tả",
  writingCorrect: "Chính xác!",
  writingTryAgain: "Thử lại — câu mục tiêu",
  nextSentence: "Câu tiếp theo",
  navQuestions: "Câu hỏi",
  navResources: "Tài nguyên",
  seoQuestionsHubTitle: "Câu hỏi công dân USCIS — trang học miễn phí",
  seoQuestionsHubLead:
    "Xem tất cả 100 và 128 câu hỏi công dân chính thức theo phiên bản, chủ đề, 65/20 hoặc các bang hàng đầu — kèm audio miễn phí.",
  seoAll128Title: "Tất cả 128 câu hỏi công dân USCIS (2025)",
  seoAll128Lead: "Đủ 128 câu USCIS 2025 chính thức với audio miễn phí — không đăng ký, vài giây. Rồi mô phỏng phỏng vấn. Hơn 10 ngôn ngữ.",
  seoAll100Title: "Tất cả 100 câu hỏi công dân USCIS (2008)",
  seoAll100Lead: "Ngân hàng 2008 đầy đủ nếu nộp N-400 trước 20/10/2025. Audio miễn phí, không tài khoản — mô phỏng khi sẵn sàng.",
  seoSeniorTitle: "Câu hỏi công dân đặc biệt 65/20",
  seoSeniorLead: "65+ và 20 năm LPR? Chỉ học 20 câu gắn sao (hỏi 10, cần 6 đúng). Audio miễn phí, không đăng ký — vài giây. Hơn 10 ngôn ngữ.",
  seoStartPractice: "Mở phần luyện tập tương tác",
  seoAllLandings: "Tất cả trang câu hỏi",
  seoQuestionsCount: "câu hỏi trên trang này",
  seoBadge2025: "Bài thi 2025 · 128 câu",
  seoBadge2008: "Bài thi 2008 · 100 câu",
  seoTopicsHeading: "Luyện theo chủ đề",
  seoStatesHeading: "Trang học các bang hàng đầu",
  seoStateLead:
    "Ôn lại thủ phủ và thống đốc bang của bạn cho các đáp án công dân hay thay đổi, rồi luyện toàn bộ bộ câu hỏi phỏng vấn. Dùng tra cứu ZIP khi luyện tập để biết thượng nghị sĩ và dân biểu của bạn.",
  seoStateCapital: "Thủ phủ tiểu bang",
  seoStateGovernor: "Thống đốc",
  seoStatePractice: "Luyện công dân cho buổi phỏng vấn của bạn",
  seoReadingTitle: "Luyện đọc tiếng Anh — từ vựng USCIS",
  seoReadingLead:
    "Luyện đọc các câu được xây dựng từ từ vựng đọc tiếng Anh chính thức của USCIS cho buổi phỏng vấn nhập tịch.",
  seoWritingTitle: "Luyện viết tiếng Anh — từ vựng USCIS",
  seoWritingLead:
    "Nghe và viết các câu bằng từ vựng viết tiếng Anh chính thức của USCIS. Chính tả được tính điểm vào ngày thi.",
  learnPostsHeading: "Hướng dẫn & tài nguyên",
  learnPostBack: "Quay lại trang học",
  learnReadMore: "Đọc thêm",
  legalBadge: "Pháp lý & uy tín",
  navAbout: "Giới thiệu",
  navContact: "Liên hệ",
  navPrivacy: "Quyền riêng tư",
  navTerms: "Điều khoản",
  seoDrillsHeading: "Bài luyện chuyên sâu",
  seoDrillsLead:
    "Tập trung vào phần khó nhất: ngày tháng quan trọng, tên nhân vật nổi tiếng, và các quan chức có đáp án thay đổi theo bầu cử — audio miễn phí cho mọi câu hỏi.",
  seoStatesCount: "trang học của các bang và DC",
  questionsSearchLabel: "Tìm câu hỏi công dân",
  questionsSearchSubmit: "Tìm kiếm",
  questionsSearchHint:
    "Tìm theo số câu hỏi, từ khóa hoặc đáp án trong ngân hàng 2008 và 2025.",
  questionsSearchResults: "Kết quả khớp",
  exportProgress: "Xuất tiến độ",
  importProgress: "Nhập tiến độ",
  exportProgressHint: "Lưu tệp sao lưu để chuyển tiến độ sang thiết bị khác.",
  importProgressDone: "Đã nhập tiến độ.",
  importProgressError: "Không thể nhập tệp đó. Hãy dùng tệp xuất từ USCivics Quiz.",
  relatedStudyHeading: "Tiep tuc hoc",
  relatedStudyLead: "Chuyen giua huong dan, danh sach cau hoi va luyen phong van cung chu de.",
  relatedLearn: "Huong dan",
  relatedQuestions: "Danh sach cau hoi",
  relatedPractice: "Luyen tap",
};
