import { completeDict } from "./complete";

export const vi = completeDict({
  brand: "USCivics Quiz",
  siteName: "USCivics Quiz",
  tagline: "Luyện thi công dân Hoa Kỳ miễn phí — bộ câu hỏi USCIS 2008 & 2025.",
  heroSupport:
    "Tìm phiên bản bài thi của bạn, rồi học bằng flashcard, ôn thông minh, luyện nói và mô phỏng phỏng vấn.",
  startEligibility: "Tìm phiên bản của tôi",
  practiceHeading: "Hoặc bắt đầu luyện ngay",
  practice2008: "Phiên bản 2008",
  practice2008Meta: "100 câu · hỏi 10 · cần 6 đúng",
  practice2025: "Phiên bản 2025",
  practice2025Meta: "128 câu · hỏi 20 · cần 12 đúng",
  freeBadge: "Miễn phí · Không cần đăng ký",
  bilingualBadge: "Đa ngôn ngữ",
  officialBadge: "Câu hỏi chính thức USCIS",
  eligibilityTitle: "Bạn thi phiên bản nào?",
  eligibilityLead: "Hai câu hỏi nhanh để đưa bạn tới bộ luyện tập đúng.",
  q1: "Bạn đã nộp Form N-400 trước ngày 20 tháng 10 năm 2025?",
  q2: "Bạn từ 65 tuổi trở lên VÀ là thường trú nhân từ 20 năm trở lên?",
  yes: "Có",
  no: "Không",
  notSure: "Tôi không chắc",
  resultSenior:
    "Bạn đủ điều kiện bài thi 65/20: 10 câu từ bộ 20 câu đánh dấu — cần 6 đúng.",
  result2008: "Bạn thi bản 2008: tối đa 10/100 câu — cần 6 đúng.",
  result2025: "Bạn thi bản 2025: tối đa 20/128 câu — cần 12 đúng.",
  startPractice: "Bắt đầu luyện",
  question: "Câu hỏi",
  of: "/",
  showAnswer: "Hiện đáp án",
  didYouKnow: "Bạn trả lời đúng chứ?",
  next: "Câu tiếp",
  finish: "Kết thúc",
  yourScore: "Điểm của bạn",
  passed: "Bạn đạt ngưỡng đậu phỏng vấn.",
  notPassed: "Tiếp tục — ôn lại và thử vòng khác.",
  tryAgain: "Luyện lại",
  passNeed: "Cần",
  correct: "đúng",
  answersLabel: "Đáp án chấp nhận",
  langSwitch: "Ngôn ngữ",
  backHome: "Trang chủ",
  disclaimer:
    "Không liên kết hoặc được USCIS hay chính phủ Hoa Kỳ chứng nhận. Câu hỏi chỉ để học.",
  stepOf: "Bước",
  modeFlashcards: "Flashcards",
  modeFlashcardsHint: "Học theo thứ tự — lật, đánh dấu, tiếp",
  modeRandom: "Ngẫu nhiên",
  modeRandomHint: "Xáo trộn như ngân hàng thật",
  modeSmart: "Ôn thông minh",
  modeSmartHint: "Ưu tiên câu yếu & chưa thấy",
  modeSimulate: "Mô phỏng phỏng vấn",
  modeSimulateHint: "Dừng khi đậu hoặc rớt — như USCIS",
  modeBrowse: "Xem tất cả",
  modeBrowseHint: "Tìm trong toàn bộ ngân hàng và mở bất kỳ câu nào",
  browseSearch: "Tìm câu hỏi…",
  browseEmpty: "Không có câu nào khớp.",
  browseStudy: "Học thẻ này",
  browseSeen: "Đã xem",
  browseWeak: "Cần ôn",
  browseStrong: "Vững",
  browseNew: "Mới",
  zipTitle: "Quan chức địa phương (theo ZIP)",
  zipLead:
    "Thượng nghị sĩ, dân biểu, thống đốc và thủ phủ tiểu bang phụ thuộc nơi bạn sống. Nhập ZIP để học đúng tên.",
  zipPlaceholder: "Mã ZIP",
  zipSubmit: "Tra cứu",
  zipLoading: "Đang tra…",
  zipInvalid: "Nhập ZIP Hoa Kỳ gồm 5 chữ số.",
  zipError: "Không tra được ZIP này. Thử lại.",
  zipAmbiguous:
    "ZIP này thuộc nhiều quận Hạ viện — hãy xác nhận quận của bạn trước buổi phỏng vấn.",
  zipSenators: "Thượng nghị sĩ Hoa Kỳ",
  zipRepresentatives: "Dân biểu",
  zipGovernor: "Thống đốc",
  zipCapital: "Thủ phủ tiểu bang",
  zipVerify: "Luôn xác minh quan chức hiện tại trước buổi phỏng vấn.",
  filterAll: "Tất cả",
  progressTitle: "Tiến độ của bạn",
  seen: "Đã xem",
  streak: "Chuỗi",
  bestStreak: "Tốt nhất",
  accuracy: "Độ chính xác",
  weak: "Yếu",
  mastered: "Vững",
  resetProgress: "Đặt lại tiến độ",
  resetConfirm: "Xóa tiến độ đã lưu của phiên bản này?",
  sims: "Mô phỏng đậu",
  seniorBadge: "65/20",
  changingBannerTitle: "Đáp án có thể đổi",
  changingBannerBody:
    "Một số đáp án phụ thuộc bầu cử hoặc bổ nhiệm. Hãy xác minh trước buổi phỏng vấn.",
  changingBannerLink: "Xem cập nhật USCIS",
  changingCardNote: "Đáp án này có thể đổi — xác minh trên USCIS trước buổi phỏng vấn.",
  interviewHowTitle: "Phỏng vấn thật diễn ra thế nào",
  interviewHow1: "Viên chức hỏi miệng từ ngân hàng chính thức.",
  interviewHow2: "Họ dừng khi bạn đạt ngưỡng đậu hoặc rớt.",
  interviewHow3: "Nghĩ đáp án, mở đáp án, rồi đánh dấu trung thực.",
  correctCount: "Đúng",
  wrongCount: "Sai",
  failAt: "Rớt khi",
  passAt: "Đậu khi",
  stoppedPass: "Dừng phỏng vấn — bạn đã đạt điểm đậu.",
  stoppedFail: "Dừng phỏng vấn — quá nhiều câu sai.",
  endTest: "Kết thúc bài thi",
  startSim: "Bắt đầu mô phỏng",
  nextRandom: "Câu ngẫu nhiên tiếp",
  prev: "Trước",
  flip: "Lật",
  nextCard: "Tiếp",
  keyboardHint: "Space mở · Y/N đánh dấu · ← → điều hướng",
  categoryMastery: "Theo chủ đề",
  poolSize: "Trong bộ này",
  noQuestions: "Không có câu với bộ lọc này.",
  saidCorrectly: "Tôi nói đúng",
  gotWrong: "Tôi nói sai",
  moreAnswers: "Đáp án chấp nhận",
  speakQuestion: "Nghe câu hỏi (EN)",
  speakAnswers: "Nghe đáp án (EN)",
  speakPractice: "Hãy nói đáp án bằng tiếng Anh to — buổi phỏng vấn là miệng.",
  navPractice: "Luyện tập",
  navLearn: "Học",
  learnTitle: "Hướng dẫn học & FAQ",
  learnLead: "Số liệu then chốt, kiến thức và câu hỏi thường gặp về bài thi công dân.",
  keyNumbersTitle: "Số liệu quan trọng cần nhớ trước",
  faqTitle: "Câu hỏi thường gặp",
  guideBranchesTitle: "Ba nhánh chính quyền",
  guideAmendmentsTitle: "Các tu chính quan trọng",
  guideTipsTitle: "Cách học",
  tip1: "Nói đáp án to — đây là phỏng vấn miệng.",
  tip2: "Luyện 15–20 phút mỗi ngày trong 4–6 tuần.",
  tip3: "Dùng ôn thông minh cho câu yếu, rồi mô phỏng đến khi đậu 3 lần liên tiếp.",
  tip4: "Xác minh đáp án thay đổi trên USCIS trước buổi phỏng vấn.",
  faqQ1: "Tôi thi phiên bản nào?",
  faqA1:
    "Nếu nộp N-400 trước 20/10/2025 → bản 2008 (100 câu). Từ ngày đó trở đi → bản 2025 (128 câu).",
  faqQ2: "Cách tính điểm phỏng vấn?",
  faqA2:
    "2025: tối đa 20 câu, cần 12 đúng; dừng ở 12 đúng hoặc 9 sai. 2008: tối đa 10 câu, cần 6 đúng (dừng ở 6 đúng hoặc 5 sai).",
  faqQ3: "65/20 là gì?",
  faqA3:
    "Từ 65 tuổi và thường trú 20+ năm: chỉ học 20 câu có sao. Viên chức hỏi 10; cần 6 đúng. Có thể thi công dân bằng ngôn ngữ bạn chọn.",
  faqQ4: "Tôi có thể thi công dân bằng ngôn ngữ của mình?",
  faqA4:
    "Thường bằng tiếng Anh. Ngoại lệ: 65/20 (ngôn ngữ tự chọn) và miễn tiếng Anh 50/20 hoặc 55/15 với thông dịch viên cho phần công dân.",
  faqQ5: "Một số đáp án có đổi không?",
  faqA5:
    "Có — tổng thống, phó tổng thống, chủ tịch Hạ viện, chánh án, thượng nghị sĩ, dân biểu, thống đốc và thủ phủ. Kiểm tra USCIS và dùng tra ZIP.",
});
