import type { Dictionary } from "./en";

export const zh: Dictionary = {
  brand: "USCivics Quiz",
  logoSubtitle: "公民测验练习",
  siteName: "USCivics Quiz",
  homeMetaTitle:
    "USCivics Quiz (uscivics-quiz) — 免费 USCIS 公民测验练习",
  homeMetaDescription:
    "USCivics Quiz（uscivics-quiz.com）— 免费 USCIS 入籍公民测验练习。官方 2008 与 2025 题库、音频、闪卡与面试模拟。无需注册。",
  tagline:
    "USCivics Quiz — 免费 USCIS 公民测验练习。先确认 N-400 递交日期（2008 或 2025），几秒即可开始。无需注册。",
  heroSupport:
    "在 uscivics-quiz.com 练习官方题库 — 含音频、闪卡与真实面试模拟，支持 10+ 种语言。",
  startEligibility: "查找我的考试版本",
  practiceHeading: "开始练习",
  practiceCta: "打开练习",
  practice2008: "2008 公民测验练习 — 官方题目",
  practice2008Meta: "100 题 · 考 10 题 · 答对 6 题及格",
  practice2025: "2025 公民测验练习 — 官方题目",
  practice2025Meta: "128 题 · 考 20 题 · 答对 12 题及格",
  freeBadge: "免费 · 无需注册 · 即刻开始",
  bilingualBadge: "10+ 种语言",
  officialBadge: "官方 USCIS 题目",
  practiceHubLead: "无需注册。官方 USCIS 题库含音频与面试模拟 — 几秒即可开始。",
  practiceMetaTitleSuffix: "免费 USCIS 面试模拟",
  diffNoSignup: "免费 · 无需注册 · 几秒开始",
  diffRightBank: "先确认题库：N-400 递交日期（2008 或 2025）或 65/20 老年路径",
  diffOfficialPractice: "官方 USCIS 题目 · 音频 · 面试模拟",
  diffLanguages: "支持 10+ 种语言 — 不止英语",
  diffStripAria: "为何在此练习",
  startInSecondsCta: "几秒开始练习",
  linkN400Filing: "N-400 递交日期（2008 与 2025）",
  link6520: "65/20 特别考量",
  linkHowMany: "会问多少题",
  linkPassScore: "及格分数",
  link2025Changes: "2025 公民测验变化",
  linkPractice2025Senior: "2025 · 65/20 练习",
  linkPractice2008Senior: "2008 · 65/20 练习",
  linkWhichCivicsTest: "我该考哪套测验？",
  linkFailTest: "如果考试未通过",
  linkStudyPlan: "30 天学习计划",
  linkReadingWriting: "英语读写",
  eligibilityTitle: "您应参加哪个公民学考试？",
  eligibilityMetaTitle: "考哪个 USCIS 公民测验？2008、2025 或 65/20",
  eligibilityLead: "两个简短问题。先帮你找到正确题库再学习 — 2008、2025 或 65/20。",
  practiceSeoTitle2008: "2008 公民测验练习 — 免费 USCIS",
  practiceSeoTitle2025: "2025 公民测验练习 — 免费 USCIS",
  dateUpdatedLabel: "更新于",
  q1: "您是否在 2025 年 10 月 20 日之前提交了 N-400 表格？",
  q2: "您是否年满 65 岁且成为永久居民已超过 20 年？",
  yes: "是",
  no: "否",
  notSure: "不确定",
  resultSenior: "您符合 65/20 简化考试：从标注的 20 题中抽 10 题 — 需答对 6 题。",
  result2008: "您参加 2008 版：最多 100 题中抽 10 题 — 需答对 6 题。",
  result2025: "您参加 2025 版：最多 128 题中抽 20 题 — 需答对 12 题。",
  startPractice: "开始练习",
  question: "问题",
  of: "/",
  showAnswer: "显示答案",
  didYouKnow: "您答对了吗？",
  next: "下一题",
  finish: "完成",
  yourScore: "您的分数",
  passed: "您已达到面试及格线。",
  notPassed: "继续加油 — 复习后再练一轮。",
  tryAgain: "再练一次",
  passNeed: "需要",
  correct: "题正确",
  answersLabel: "可接受答案",
  langSwitch: "语言",
  backHome: "首页",
  disclaimer: "本站与 USCIS 或美国政府无关联、无背书。题目仅供学习。",
  stepOf: "步骤",
  modeFlashcards: "闪卡",
  modeFlashcardsHint: "按顺序学习 — 翻转、标记、继续",
  modeRandom: "随机",
  modeRandomHint: "像真实题库一样打乱",
  modeSmart: "智能复习",
  modeSmartHint: "优先薄弱与未见过的题",
  modeSimulate: "模拟面试",
  modeSimulateHint: "及格或不及格即停止 — 如 USCIS",
  modeBrowse: "浏览全部",
  modeBrowseHint: "搜索完整题库并跳转到任意题",
  browseSearch: "搜索题目…",
  browseEmpty: "没有匹配的题目。",
  browseStudy: "学习此卡",
  browseSeen: "已见",
  browseWeak: "需加强",
  browseStrong: "熟练",
  browseNew: "新题",
  zipTitle: "按 ZIP 查找本地官员",
  zipLead: "参议员、众议员、州长和州首府答案取决于您的居住地。输入 ZIP 学习正确姓名。",
  zipPlaceholder: "ZIP 邮编",
  zipSubmit: "查询",
  zipLoading: "查询中…",
  zipInvalid: "请输入有效的 5 位美国 ZIP。",
  zipError: "无法查询此 ZIP，请重试。",
  zipAmbiguous: "此 ZIP 覆盖多个众议院选区 — 面试前请确认您的选区。",
  zipSenators: "美国参议员",
  zipRepresentatives: "众议员",
  zipGovernor: "州长",
  zipCapital: "州首府",
  zipVerify: "面试前请务必核实现任官员。",
  filterAll: "全部",
  progressTitle: "您的进度",
  seen: "已见",
  streak: "连对",
  bestStreak: "最佳",
  accuracy: "正确率",
  weak: "薄弱",
  mastered: "熟练",
  resetProgress: "重置进度",
  resetConfirm: "清除此版本的已存进度？",
  sims: "模拟通过",
  seniorBadge: "65/20",
  changingBannerTitle: "会变化的答案",
  changingBannerBody: "部分答案随选举或任命变化。面试前请核实现任官员。",
  changingBannerLink: "打开测验更新",
  changingCardNote: "此答案可能变化 — 面试前请在 USCIS 核实。",
  interviewHowTitle: "真实面试如何进行",
  interviewHow1: "官员从官方题库口头提问。",
  interviewHow2: "达到及格或不及格线时停止。",
  interviewHow3: "先想答案，再揭晓，然后诚实标记。",
  correctCount: "正确",
  wrongCount: "错误",
  failAt: "不及格线",
  passAt: "及格线",
  stoppedPass: "面试停止 — 已达及格分。",
  stoppedFail: "面试停止 — 错误过多。",
  endTest: "结束考试",
  startSim: "开始模拟",
  nextRandom: "下一道随机",
  prev: "上一题",
  flip: "翻转",
  nextCard: "下一题",
  keyboardHint: "空格揭晓 · Y/N 标记 · ← → 导航",
  categoryMastery: "按类别",
  poolSize: "本题库",
  noQuestions: "此筛选下没有题目。",
  saidCorrectly: "我说对了",
  gotWrong: "我说错了",
  moreAnswers: "可接受答案",
  speakQuestion: "听问题 (英语)",
  speakAnswers: "听答案 (英语)",
  speakPractice: "请用英语大声说出答案 — 面试是口语考试。",
  navPractice: "练习",
  navLearn: "指南",
  navCitizenship: "我的版本",
  navCivicsTest: "公民测试",
  navReadingTest: "阅读测试",
  navWritingTest: "写作测试",
  navTest2025: "2025 公民考试",
  navTest2008: "2008 公民考试",
  navSenior: "65/20",
  menuOpen: "打开菜单",
  menuClose: "关闭菜单",
  navHome: "首页",
  themeToLight: "切换到浅色模式",
  themeToDark: "切换到深色模式",
  uscisUpdatesPageTitle: "查看考试更新",
  uscisAlertLabel: "提醒：",
  uscisAlertBody:
    "USCIS 正在实施 2025 年入籍公民考试，以符合第 14161 号行政命令。在 2025 年 10 月 20 日之前提交 N-400 表格申请入籍者，将参加 2008 年入籍公民考试。在 2025 年 10 月 20 日或之后提交 N-400 表格者，将参加 2025 年考试。新的 2025 年考试基于 2020 年入籍公民考试，并对考试的实施方式做了一些调整。",
  uscisFilingColDate: "N-400 提交日期",
  uscisFilingColVersion: "公民考试版本",
  uscisFilingBefore: "2025 年 10 月 20 日之前",
  uscisFilingBeforeVersion: "2008 年入籍公民考试",
  uscisFilingAfter: "2025 年 10 月 20 日或之后",
  uscisFilingAfterVersion: "2025 年入籍公民考试",
  uscis2008Heading: "2008 年入籍公民考试",
  uscis2008Body:
    "对于在 2025 年 10 月 20 日之前提交 N-400 入籍申请表的申请人，我们将实施 2008 年入籍公民考试。",
  uscis2025Heading: "2025 年入籍公民考试",
  uscis2025Body:
    "对于在 2025 年 10 月 20 日或之后提交 N-400 表格的入籍申请人，我们将实施 2025 年入籍公民考试。",
  uscisResourcesHeading: "USCIS 官方资源",
  uscisResourcesLead: "来自美国公民及移民服务局的学习材料和更新。我们仅提供外部链接 — 不托管官方 PDF。",
  uscisStudyTitle: "备考学习",
  uscisStudyBlurb: "英语与公民学概览及免费学习材料",
  uscisUpdatesTitle: "查看考试更新",
  uscisUpdatesBlurb: "随选举变化的官员和答案",
  uscis2025Title: "2025 公民考试",
  uscis2025Blurb: "2025 年入籍公民考试政策页面",
  uscisExceptionsTitle: "例外与特殊安排",
  uscisExceptionsBlurb: "65/20 与英语考试例外",
  uscisN400Title: "N-400 表格",
  uscisN400Blurb: "入籍申请表",
  uscisPdf128Title: "128 题 PDF（2025）",
  uscisPdf128Blurb: "官方英文问答列表",
  uscisPdf100Title: "100 题 PDF（2008）",
  uscisPdf100Blurb: "官方英文问答列表",
  uscisHomeTitle: "USCIS.gov",
  uscisHomeBlurb: "美国公民及移民服务局官方网站",
  learnTitle: "学习指南与常见问题",
  learnLead: "关键数字、要点，以及公民学考试常见问题解答。",
  keyNumbersTitle: "必须先记住的关键数字",
  faqTitle: "常见问题",
  guideBranchesTitle: "政府三权分立",
  guideAmendmentsTitle: "重要修正案",
  guideTipsTitle: "如何学习",
  tip1: "大声说出答案 — 这是口语面试。",
  tip2: "每天练习 15–20 分钟，坚持 4–6 周。",
  tip3: "用智能复习攻克薄弱题，再连续模拟及格 3 次。",
  tip4: "面试前在 USCIS 核实会变化的答案。",
  faqQ1: "我应参加哪个版本？",
  faqA1: "若在 2025 年 10 月 20 日前提交 N-400，考 2008（100 题）；该日或之后提交则考 2025（128 题）。",
  faqQ2: "面试如何计分？",
  faqA2: "2025：最多 20 题，需 12 对；12 对或 9 错即停。2008：最多 10 题，需 6 对（6 对或 5 错即停）。",
  faqQ3: "什么是 65/20 特别考虑？",
  faqA3: "年满 65 岁且永久居民 20+ 年，只需学习标星的 20 题。官员问 10 题，需答对 6 题。可用自选语言考公民学。",
  faqQ4: "可以用我的语言考公民学吗？",
  faqA4: "通常用英语。例外：65/20（自选语言），以及英语豁免 50/20 或 55/15（可带翻译考公民学）。",
  faqQ5: "有些答案会变吗？",
  faqA5: "会 — 总统、副总统、议长、首席大法官、您的参议员、众议员、州长和州首府。请查 USCIS 更新并用 ZIP 查询。",
  federalTitle: "现任联邦官员",
  federalLead: "这些答案会随选举或任命而变化。请学习 USCIS 认可的姓名。",
  federalPresident: "总统",
  federalVP: "副总统",
  federalSpeaker: "众议院议长",
  federalChief: "首席大法官",
  federalParty: "总统所属政党",
  federalAsOf: "核实截止",
  modeSpeak: "口语作答",
  modeSpeakHint: "先听英语问题，再用麦克风回答 — 就像真实面试一样。",
  speakStart: "说出我的答案",
  speakStop: "停止聆听",
  speakHeard: "您说的是",
  speakMatch: "很好 — 与一个可接受的答案匹配。",
  speakNoMatch: "尚未明确匹配。可接受的答案：",
  speakUnsupported: "此浏览器不支持语音识别。请尝试 Chrome，或使用听答案自行核对。",
  navEnglish: "英语测试",
  englishTitle: "英语阅读与写作",
  englishLead: "练习入籍面试中使用的 USCIS 英语阅读和写作词汇。",
  readingTitle: "阅读",
  writingTitle: "写作",
  readingHint: "大声朗读句子。点击播放先听一遍。",
  writingHint: "听句子然后写下来。拼写很重要。",
  writingPrompt: "写下您听到的内容",
  writingCheck: "检查拼写",
  writingCorrect: "正确！",
  writingTryAgain: "再试一次 — 目标句子",
  nextSentence: "下一句",
  navQuestions: "题库",
  navResources: "资源",
  seoQuestionsHubTitle: "USCIS 公民考题 — 免费学习专区",
  seoQuestionsHubLead: "按版本、主题、65/20 或热门州浏览全部 100 题和 128 题官方公民考题 — 附免费音频。",
  seoAll128Title: "全部 128 道公民题（2025）— 免费",
  seoAll128Lead: "全部 128 道 2025 官方 USCIS 题目，免费音频 — 无需注册，几秒开始。再进行面试模拟。支持 10+ 语言。",
  seoAll100Title: "全部 100 道公民题（2008）— 免费",
  seoAll100Lead: "完整 2008 题库，适用于 2025 年 10 月 20 日前递交 N-400 的申请人。免费音频，无需账号 — 随时模拟面试。",
  seoSeniorTitle: "65/20 标星公民题 — 免费练习",
  seoSeniorLead: "年满 65 且 LPR 满 20 年？只需学习 20 道星标题（问 10 题，需对 6 题）。免费音频，无需注册 — 几秒开始。10+ 语言。",
  seoStartPractice: "打开互动练习",
  seoAllLandings: "全部题库专区",
  seoQuestionsCount: "本页题目数",
  seoBadge2025: "2025 考试 · 128 题",
  seoBadge2008: "2008 考试 · 100 题",
  seoTopicsHeading: "按主题练习",
  seoStatesHeading: "热门州学习页面",
  seoStateLead:
    "复习您所在州的首府和州长以应对会变化的公民答案，然后练习完整面试题库。在练习中使用 ZIP 查询参议员和众议员。",
  seoStateCapital: "州首府",
  seoStateGovernor: "州长",
  seoStatePractice: "为面试练习公民学",
  seoReadingTitle: "英语阅读练习 — USCIS 词汇",
  seoReadingLead: "使用官方 USCIS 入籍面试英语阅读词汇练习朗读句子。",
  seoWritingTitle: "英语写作练习 — USCIS 词汇",
  seoWritingLead: "听写使用官方 USCIS 写作词汇的句子。拼写在考试当天很重要。",
  learnPostsHeading: "指南与资源",
  learnPostBack: "返回学习",
  learnReadMore: "阅读更多",
  legalBadge: "法律与信任",
  navAbout: "关于我们",
  navContact: "联系我们",
  navPrivacy: "隐私政策",
  navTerms: "服务条款",
  seoDrillsHeading: "专项强化训练",
  seoDrillsLead:
    "专注于最难的部分：关键日期、著名人物姓名，以及随选举变化的官员答案 — 每道题都配有免费音频。",
  seoStatesCount: "个州及华盛顿特区学习页面",
  questionsSearchLabel: "搜索公民考题",
  questionsSearchSubmit: "搜索",
  questionsSearchHint: "按题号、关键词或答案在 2008 和 2025 题库中搜索。",
  questionsSearchResults: "匹配结果",
  exportProgress: "导出进度",
  importProgress: "导入进度",
  exportProgressHint: "保存备份文件，以便将进度转移到其他设备。",
  importProgressDone: "进度已导入。",
  importProgressError: "无法导入该文件。请使用 USCivics Quiz 导出的文件。",
  relatedStudyHeading: "继续学习",
  relatedStudyLead: "在同一主题的指南、题库页面和面试练习之间跳转。",
  relatedLearn: "指南",
  relatedQuestions: "题库",
  relatedPractice: "练习",
  premiumWaitlistTitle: "跨设备进度（即将推出）",
  premiumWaitlistLead: "核心练习永久免费。加入候补名单获取可选云同步——题库不设付费墙。",
  premiumWaitlistCta: "上线时通知我",
  premiumWaitlistDone: "已在本设备加入候补名单。",
  navUpdates: "更新",
  govBannerLead: "独立公民测验练习 — 不是美国政府网站。",
  govBannerHow: "如何识别",
  govBannerSecureTitle: "面试前请核实",
  govBannerOfficialTitle: "官方网站使用 .gov",
  govBannerBadge: "非 .gov",
  govBannerOfficial: "USCIS 及其他美国政府网站以 .gov 结尾。本站是免费独立学习工具 — 与 USCIS 无关联、无背书。",
  govBannerSecure: "面试前请务必在 uscis.gov 确认会变化的答案和考试规则。",
  updatesHubTitle: "公民测验更新",
  updatesHubLead: "递交日期（2008 与 2025）、会变化的官员及 ZIP 查询 — 考试变更记录，不是新闻流。",
  updatesPolicyHeading: "政策与考试说明",
  updatesLiveHeading: "实时官员与本地答案",
  updatesLiveBadge: "实时",
  updatesCachedBadge: "缓存",
  updatesVerifyNote: "面试当周请再次确认姓名。选举与任命可能改变可接受答案。",
  homeLiveHeading: "现任官员",
  homeLiveLead: "面试日可用的联邦姓名 — 另有 ZIP 查询参议员、众议员、州长与州府。",
  homeLiveCta: "打开测验更新",
  linkUpdates: "公民测验更新",
  affiliateHeading: "相关备考（可选）",
  affiliateLead: "本站核心练习保持免费。有人也会用实体书或闪卡——以下链接可能为我们带来少量佣金。",
  affiliateDisclosure: "作为 Amazon Associate，我们可能从合格购买中获得佣金。本站与 USCIS 无关联。请始终在 uscis.gov 核实规则。",
  affiliateItemFlashcards: "公民测验闪卡",
  affiliateItemFlashcardsBlurb: "实体卡片，方便离屏口语练习。",
  affiliateItemGuide: "入籍学习指南",
  affiliateItemGuideBlurb: "纸质概览，搭配本站官方 USCIS 题库。",
  affiliateItemEnglish: "入籍英语练习",
  affiliateItemEnglishBlurb: "额外读写支持——也请继续用我们的免费句子练习。",
};
