import { completeDict } from "./complete";

export const zh = completeDict({
  brand: "USCivics Quiz",
  siteName: "USCivics Quiz",
  tagline: "免费美国公民入籍公民学考试练习 — USCIS 2008 与 2025 题库。",
  heroSupport: "先确认考试版本，再用闪卡、智能复习、口语练习和真实模拟准备面试。",
  startEligibility: "查找我的考试版本",
  practiceHeading: "或直接开始练习",
  practice2008: "2008 版",
  practice2008Meta: "100 题 · 考 10 题 · 答对 6 题及格",
  practice2025: "2025 版",
  practice2025Meta: "128 题 · 考 20 题 · 答对 12 题及格",
  freeBadge: "免费 · 无需注册",
  bilingualBadge: "多语言",
  officialBadge: "官方 USCIS 题目",
  eligibilityTitle: "您应参加哪个公民学考试？",
  eligibilityLead: "两个快速问题，帮您找到正确练习题库。",
  q1: "您是否在 2025 年 10 月 20 日之前提交了 N-400 表格？",
  q2: "您是否年满 65 岁且成为永久居民已超过 20 年？",
  yes: "是",
  no: "否",
  notSure: "不确定",
  resultSenior: "您符合 65/20 简化考试：从标注的 20 题中抽 10 题 — 需答对 6 题。",
  result2008: "您参加 2008 版：最多 100 题中抽 10 题 — 需答对 6 题。",
  result2025: "您参加 2025 版：最多 128 题中抽 20 题 — 需答对 12 题。",
  startPractice: "开始练习",
  question: "问题",
  of: "/",
  showAnswer: "显示答案",
  didYouKnow: "您答对了吗？",
  next: "下一题",
  finish: "完成",
  yourScore: "您的分数",
  passed: "您已达到面试及格线。",
  notPassed: "继续加油 — 复习后再练一轮。",
  tryAgain: "再练一次",
  passNeed: "需要",
  correct: "题正确",
  answersLabel: "可接受答案",
  langSwitch: "语言",
  backHome: "首页",
  disclaimer: "本站与 USCIS 或美国政府无关联、无背书。题目仅供学习。",
  stepOf: "步骤",
  modeFlashcards: "闪卡",
  modeFlashcardsHint: "按顺序学习 — 翻转、标记、继续",
  modeRandom: "随机",
  modeRandomHint: "像真实题库一样打乱",
  modeSmart: "智能复习",
  modeSmartHint: "优先薄弱与未见过的题",
  modeSimulate: "模拟面试",
  modeSimulateHint: "及格或不及格即停止 — 如 USCIS",
  modeBrowse: "浏览全部",
  modeBrowseHint: "搜索完整题库并跳转到任意题",
  browseSearch: "搜索题目…",
  browseEmpty: "没有匹配的题目。",
  browseStudy: "学习此卡",
  browseSeen: "已见",
  browseWeak: "需加强",
  browseStrong: "熟练",
  browseNew: "新题",
  zipTitle: "按 ZIP 查找本地官员",
  zipLead: "参议员、众议员、州长和州首府答案取决于您的居住地。输入 ZIP 学习正确姓名。",
  zipPlaceholder: "ZIP 邮编",
  zipSubmit: "查询",
  zipLoading: "查询中…",
  zipInvalid: "请输入有效的 5 位美国 ZIP。",
  zipError: "无法查询此 ZIP，请重试。",
  zipAmbiguous: "此 ZIP 覆盖多个众议院选区 — 面试前请确认您的选区。",
  zipSenators: "美国参议员",
  zipRepresentatives: "众议员",
  zipGovernor: "州长",
  zipCapital: "州首府",
  zipVerify: "面试前请务必核实现任官员。",
  filterAll: "全部",
  progressTitle: "您的进度",
  seen: "已见",
  streak: "连对",
  bestStreak: "最佳",
  accuracy: "正确率",
  weak: "薄弱",
  mastered: "熟练",
  resetProgress: "重置进度",
  resetConfirm: "清除此版本的已存进度？",
  sims: "模拟通过",
  seniorBadge: "65/20",
  changingBannerTitle: "会变化的答案",
  changingBannerBody: "部分答案随选举或任命变化。面试前请核实现任官员。",
  changingBannerLink: "查看 USCIS 更新",
  changingCardNote: "此答案可能变化 — 面试前请在 USCIS 核实。",
  interviewHowTitle: "真实面试如何进行",
  interviewHow1: "官员从官方题库口头提问。",
  interviewHow2: "达到及格或不及格线时停止。",
  interviewHow3: "先想答案，再揭晓，然后诚实标记。",
  correctCount: "正确",
  wrongCount: "错误",
  failAt: "不及格线",
  passAt: "及格线",
  stoppedPass: "面试停止 — 已达及格分。",
  stoppedFail: "面试停止 — 错误过多。",
  endTest: "结束考试",
  startSim: "开始模拟",
  nextRandom: "下一道随机",
  prev: "上一题",
  flip: "翻转",
  nextCard: "下一题",
  keyboardHint: "空格揭晓 · Y/N 标记 · ← → 导航",
  categoryMastery: "按类别",
  poolSize: "本题库",
  noQuestions: "此筛选下没有题目。",
  saidCorrectly: "我说对了",
  gotWrong: "我说错了",
  moreAnswers: "可接受答案",
  speakQuestion: "听问题 (英语)",
  speakAnswers: "听答案 (英语)",
  speakPractice: "请用英语大声说出答案 — 面试是口语考试。",
  navPractice: "练习",
  navLearn: "学习",
  learnTitle: "学习指南与常见问题",
  learnLead: "关键数字、要点，以及公民学考试常见问题解答。",
  keyNumbersTitle: "必须先记住的关键数字",
  faqTitle: "常见问题",
  guideBranchesTitle: "政府三权分立",
  guideAmendmentsTitle: "重要修正案",
  guideTipsTitle: "如何学习",
  tip1: "大声说出答案 — 这是口语面试。",
  tip2: "每天练习 15–20 分钟，坚持 4–6 周。",
  tip3: "用智能复习攻克薄弱题，再连续模拟及格 3 次。",
  tip4: "面试前在 USCIS 核实会变化的答案。",
  faqQ1: "我应参加哪个版本？",
  faqA1: "若在 2025 年 10 月 20 日前提交 N-400，考 2008（100 题）；该日或之后提交则考 2025（128 题）。",
  faqQ2: "面试如何计分？",
  faqA2: "2025：最多 20 题，需 12 对；12 对或 9 错即停。2008：最多 10 题，需 6 对（6 对或 5 错即停）。",
  faqQ3: "什么是 65/20 特别考虑？",
  faqA3: "年满 65 岁且永久居民 20+ 年，只需学习标星的 20 题。官员问 10 题，需答对 6 题。可用自选语言考公民学。",
  faqQ4: "可以用我的语言考公民学吗？",
  faqA4: "通常用英语。例外：65/20（自选语言），以及英语豁免 50/20 或 55/15（可带翻译考公民学）。",
  faqQ5: "有些答案会变吗？",
  faqA5: "会 — 总统、副总统、议长、首席大法官、您的参议员、众议员、州长和州首府。请查 USCIS 更新并用 ZIP 查询。",
});
